import re
import sys

def convert_html_to_jsx(html_str):
    # Fix self-closing tags
    html_str = re.sub(r'<(img|input|br|hr)([^>]*?)(?<!/)>', r'<\1\2 />', html_str)
    
    # Replace class with className
    html_str = html_str.replace(' class="', ' className="')
    
    # Replace for with htmlFor
    html_str = html_str.replace(' for="', ' htmlFor="')
    
    # Replace value with defaultValue in inputs
    html_str = html_str.replace(' value="', ' defaultValue="')
    
    # Replace readonly with readOnly
    html_str = html_str.replace(' readonly=""', ' readOnly')
    html_str = html_str.replace(' readonly', ' readOnly')
    
    # Fix inline styles (if any) like style="width: 74.7%;"
    html_str = re.sub(r'style="width: ([\d.]+)%;"', r'style={{width: "\1%"}}', html_str)
    
    # Fix comments
    html_str = re.sub(r'<!--(.*?)-->', r'{/* \1 */}', html_str)

    # Clean up JSON-LD from the body, as it's already added to page.tsx
    html_str = re.sub(r'<script type="application/ld\+json">.*?</script>', '', html_str, flags=re.DOTALL)

    # Clean up standard JS script block at the bottom
    html_str = re.sub(r'<script>.*?</script>', '', html_str, flags=re.DOTALL)
    
    return html_str

def main():
    with open('/tmp/daily_wage.html', 'r', encoding='utf-8') as f:
        html = f.read()
        
    # Extract the main content inside <main>...</main> and <header> and <footer>
    # Wait, the user provided the full HTML document.
    header_match = re.search(r'<header.*?</header>', html, flags=re.DOTALL)
    main_match = re.search(r'<main.*?</main>', html, flags=re.DOTALL)
    footer_match = re.search(r'<footer.*?</footer>', html, flags=re.DOTALL)
    
    header_jsx = convert_html_to_jsx(header_match.group(0)) if header_match else ""
    main_jsx = convert_html_to_jsx(main_match.group(0)) if main_match else ""
    footer_jsx = convert_html_to_jsx(footer_match.group(0)) if footer_match else ""
    
    # In main_jsx, replace the FAQ accordion container with our React dynamic one
    faq_replacement = """<div className="grid grid-cols-1 md:grid-cols-2 gap-space-sm" id="faq-accordion-container">
  {faqData
    .filter(item => item.q.toLowerCase().includes(faqSearch.toLowerCase()) || item.a.toLowerCase().includes(faqSearch.toLowerCase()))
    .map((item, idx) => (
      <div key={idx} className="faq-item bg-surface-container-lowest rounded-xl p-space-md shadow-sm transition-all">
        <button 
          type="button" 
          className="faq-toggle w-full flex items-center justify-between text-left font-body-md text-body-md font-bold text-on-surface hover:text-primary transition-colors focus:outline-none"
          onClick={() => toggleFaq(idx)}
        >
          <span className="flex items-center gap-2">
            <span className="font-data-mono text-xs text-primary/70">#{idx + 1}</span>
            {item.q}
          </span>
          <span className={`material-symbols-outlined text-[20px] text-on-surface-variant transform transition-transform duration-200 ${openFaqIndices.includes(idx) ? 'rotate-180' : ''}`}>
            expand_more
          </span>
        </button>
        {openFaqIndices.includes(idx) && (
          <div className="faq-answer mt-space-xs font-body-sm text-body-sm text-on-surface-variant leading-relaxed pt-space-xs border-0">
            {item.a}
          </div>
        )}
      </div>
    ))}
  {faqData.filter(item => item.q.toLowerCase().includes(faqSearch.toLowerCase()) || item.a.toLowerCase().includes(faqSearch.toLowerCase())).length === 0 && (
    <div className="col-span-1 md:col-span-2 text-center p-space-lg text-on-surface-variant italic">No FAQs matching "{faqSearch}".</div>
  )}
</div>"""

    # We need to replace the static FAQ container with our dynamic one.
    # The static one is: <div className="grid grid-cols-1 md:grid-cols-2 gap-space-sm" id="faq-accordion-container">{/*  Generated by JavaScript with semantic accessibility  */}</div>
    # Actually wait, convert_html_to_jsx transforms comments.
    main_jsx = re.sub(r'<div className="grid grid-cols-1 md:grid-cols-2 gap-space-sm" id="faq-accordion-container">.*?</div>', faq_replacement, main_jsx, flags=re.DOTALL)
    
    # Also hook up the FAQ search input
    main_jsx = main_jsx.replace('id="faq-search-input"', 'id="faq-search-input" value={faqSearch} onChange={(e) => setFaqSearch(e.target.value)}')
    
    # Remove onclick attributes and let the useEffect bind them, OR replace them if needed.
    # The script has `onclick="window.print()"` and `onclick="setM2DSalary(...)"` and `onclick="loadSalaryIntoTab1(...)"`.
    # It's better to leave them and let the useEffect handle them, or just let them be strings but React expects functions.
    # Let's clean onclick string attributes:
    main_jsx = re.sub(r' onclick="([^"]+)"', r' onClick={() => { \1 }}', main_jsx)

    # Let's read the existing DailyWageClient to keep the state logic and `useEffect`
    with open('app/daily-wage-calculator/DailyWageClient.tsx', 'r') as f:
        existing = f.read()
        
    top_part = existing.split('return (')[0] + 'return (\n    <>\n'
    
    final_content = top_part + header_jsx + '\n' + main_jsx + '\n' + footer_jsx + '\n    </>\n  );\n}'
    
    with open('app/daily-wage-calculator/DailyWageClient.tsx', 'w') as f:
        f.write(final_content)

if __name__ == '__main__':
    main()
