const fs = require('fs');

let content = fs.readFileSync('app/finance/FinanceHubClient.tsx', 'utf-8');

const newScenarioBattles = `
const SCENARIO_BATTLES = [
  {
    id: '401k-vs-roth',
    label: '401(k) vs Roth',
    alpha: {
      name: 'Traditional 401(k)',
      tag: 'Pre-Tax',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Get a tax break now. You pay taxes later when you withdraw in retirement.',
      annual: '$23,000',
      annualLabel: 'Annual Contribution:',
      benefitLabel: 'Immediate Tax Saved:',
      benefitVal: '+$5,520 / yr',
      benefitColor: 'text-primary',
      effectiveCost: '$17,480',
      costLabel: 'Effective Annual Cost:',
      estValue: '$2,376,512',
      note: 'Pre-tax balance',
    },
    beta: {
      name: 'Roth IRA',
      tag: 'Post-Tax',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Pay taxes upfront. Your money grows and is withdrawn completely tax-free.',
      annual: '$23,000',
      annualLabel: 'Annual Contribution:',
      benefitLabel: 'Tax-Free Withdrawals:',
      benefitVal: '100% Tax-Free',
      benefitColor: 'text-outline',
      effectiveCost: '$23,000',
      costLabel: 'Effective Annual Cost:',
      estValue: '$2,376,512',
      note: 'Tax-free balance',
    },
    deltaTitle: 'Net After-Tax Outcome',
    deltaValue: '+$184,210',
    deltaDesc: 'Depending on your tax bracket in retirement, a Traditional 401(k) or Roth can provide more spendable cash.',
    barAlphaPercent: '54%',
    barBetaPercent: '46%',
    barAlphaLabel: 'Traditional 401(k)',
    barBetaLabel: 'Roth IRA',
    link: '/fire-forecaster',
    linkText: 'Compare 401(k) vs Roth →',
  },
  {
    id: 'rent-vs-buy',
    label: 'Rent vs Buy',
    alpha: {
      name: 'Buy a Home',
      tag: 'Build Equity',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Lock in your monthly payment and build wealth through home equity over time.',
      annual: '$32,400',
      annualLabel: 'Annual Housing Cost:',
      benefitLabel: 'Equity Built:',
      benefitVal: '+$11,200 / yr',
      benefitColor: 'text-primary',
      effectiveCost: '$21,200',
      costLabel: 'Sunk Cost (Interest/Tax):',
      estValue: '$1,140,000',
      note: 'Home value in 20 years',
    },
    beta: {
      name: 'Rent & Invest',
      tag: 'Invest Savings',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Avoid home maintenance and property taxes. Invest the savings in the stock market.',
      annual: '$26,400',
      annualLabel: 'Annual Rent:',
      benefitLabel: 'Savings Invested:',
      benefitVal: '+$7,200 / yr',
      benefitColor: 'text-secondary',
      effectiveCost: '$26,400',
      costLabel: 'Sunk Cost (Rent):',
      estValue: '$985,400',
      note: 'Investment value in 20 yrs',
    },
    deltaTitle: 'Buying Edge at Year 15+',
    deltaValue: '+$154,600',
    deltaDesc: 'After several years, buying usually beats renting as rent prices go up and your home builds equity.',
    barAlphaPercent: '58%',
    barBetaPercent: '42%',
    barAlphaLabel: 'Home Equity',
    barBetaLabel: 'Stock Portfolio',
    link: '/finance/mortgage-calculator',
    linkText: 'Run Rent vs Buy Tool →',
  },
  {
    id: 'mortgage-vs-sp500',
    label: 'Pay Off Debt vs Invest',
    alpha: {
      name: 'Pay Down Mortgage',
      tag: 'Guaranteed Return',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Get a risk-free return equal to your mortgage interest rate. Become debt-free faster.',
      annual: '$12,000 extra',
      annualLabel: 'Amount Directed:',
      benefitLabel: 'Interest Saved:',
      benefitVal: '+$124,500 total',
      benefitColor: 'text-primary',
      effectiveCost: 'No Market Risk',
      costLabel: 'Primary Risk Factor:',
      estValue: 'Paid in 14 Yrs',
      note: '15 years of freedom',
    },
    beta: {
      name: 'Invest in S&P 500',
      tag: 'Market Growth',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Invest extra cash in the stock market to take advantage of historically higher average returns.',
      annual: '$12,000 extra',
      annualLabel: 'Amount Directed:',
      benefitLabel: 'Expected Growth:',
      benefitVal: '+$318,000 net',
      benefitColor: 'text-secondary',
      effectiveCost: 'Market Ups & Downs',
      costLabel: 'Primary Risk Factor:',
      estValue: '$482,500',
      note: 'Portfolio in 15 yrs',
    },
    deltaTitle: 'Investment Potential Edge',
    deltaValue: '+$193,500',
    deltaDesc: 'Historically, the stock market earns more over the long run than most mortgage interest rates.',
    barAlphaPercent: '39%',
    barBetaPercent: '61%',
    barAlphaLabel: 'Interest Saved',
    barBetaLabel: 'Market Growth',
    link: '/finance/mortgage-calculator',
    linkText: 'Compare Mortgage vs Investing →',
  },
  {
    id: 'lump-sum-vs-dca',
    label: 'Lump Sum vs DCA',
    alpha: {
      name: 'Lump Sum Investment',
      tag: 'Max Market Time',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Invest all your money at once. Markets go up more often than they go down over time.',
      annual: '$100,000',
      annualLabel: 'Initial Investment:',
      benefitLabel: 'Historical Win Rate:',
      benefitVal: '68% of time',
      benefitColor: 'text-primary',
      effectiveCost: 'Immediate entry',
      costLabel: 'Primary Drawback:',
      estValue: '$259,374',
      note: 'In 10 years',
    },
    beta: {
      name: 'Dollar-Cost Averaging',
      tag: 'Less Regret',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Invest smaller amounts over time. Less stressful if the market drops right after you start.',
      annual: '$8,333 / mo',
      annualLabel: 'Investment Schedule:',
      benefitLabel: 'Risk Protection:',
      benefitVal: 'Lower Volatility',
      benefitColor: 'text-secondary',
      effectiveCost: 'Missed early gains',
      costLabel: 'Primary Drawback:',
      estValue: '$244,120',
      note: 'In 10 years',
    },
    deltaTitle: 'Lump Sum Outperformance',
    deltaValue: '+$15,254',
    deltaDesc: 'Historically, investing everything upfront wins about two-thirds of the time.',
    barAlphaPercent: '68%',
    barBetaPercent: '32%',
    barAlphaLabel: 'Lump Sum Win',
    barBetaLabel: 'DCA Win',
    link: '/investing-and-growth',
    linkText: 'Calculate DCA vs Lump Sum →',
  },
];
`;

content = content.replace(/const SCENARIO_BATTLES = \[[\s\S]*?\];/m, newScenarioBattles.trim());

// Also replace the hardcoded labels
content = content.replace(/<span className="text-on-surface-variant font-body-sm">Annual Contribution:<\/span>/g, '<span className="text-on-surface-variant font-body-sm">{currentBattle.alpha.annualLabel}<\/span>');
content = content.replace(/<span className="text-on-surface-variant font-body-sm">Effective Annual Cost:<\/span>/g, '<span className="text-on-surface-variant font-body-sm">{currentBattle.alpha.costLabel}<\/span>');
// The above is for alpha. Since we replace globally, it will replace both alpha and beta. We need to be careful to change the second one to beta.

fs.writeFileSync('app/finance/FinanceHubClient.tsx', content);
