import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  trailingSlash: false,
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'picsum.photos',
        port: '',
        pathname: '/**',
      },
    ],
  },
  async redirects() {
    return [
      // Finance Subcategories & Aliases
      { source: '/mortgages-and-real-estate', destination: '/finance/mortgages', permanent: true },
      { source: '/mortgages-and-real-estate-debt', destination: '/finance/mortgages', permanent: true },
      { source: '/mortgage-calculators', destination: '/finance/mortgage-calculator', permanent: true },
      { source: '/loans-and-amortization', destination: '/finance/loans', permanent: true },
      { source: '/loans-and-amortization-calculators', destination: '/finance/loans', permanent: true },
      { source: '/banking', destination: '/finance/banking', permanent: true },
      { source: '/banking-calculators', destination: '/finance/banking', permanent: true },
      { source: '/banking-and-cash-accounts', destination: '/finance/banking', permanent: true },
      { source: '/savings', destination: '/finance/savings', permanent: true },
      { source: '/savings-calculators', destination: '/finance/savings', permanent: true },
      { source: '/savings-and-liquidity', destination: '/finance/savings', permanent: true },
      { source: '/credit-cards', destination: '/finance/credit-cards', permanent: true },
      { source: '/credit-cards-and-revolving', destination: '/finance/credit-cards', permanent: true },
      { source: '/credit-card-calculators', destination: '/finance/credit-cards', permanent: true },
      { source: '/credit-cards-and-revolving-credit', destination: '/finance/credit-cards', permanent: true },
      { source: '/tax-calculator', destination: '/finance/taxes', permanent: true },
      { source: '/global-tax-calculator', destination: '/finance/taxes', permanent: true },
      { source: '/tax-engines-global', destination: '/finance/taxes', permanent: true },
      { source: '/tax-calculator/:country', destination: '/finance/taxes', permanent: true },
      { source: '/investing-and-growth', destination: '/finance/investing', permanent: true },
      { source: '/retirement-and-super', destination: '/finance/retirement', permanent: true },
      { source: '/salary-and-payroll', destination: '/finance/salary', permanent: true },
      { source: '/daily-wage-calculator', destination: '/finance/salary', permanent: true },
      { source: '/billable-hours-calculator', destination: '/finance/salary', permanent: true },
      { source: '/freelance-hourly-rate-calculator', destination: '/finance/salary', permanent: true },
      { source: '/business-tools', destination: '/business', permanent: true },
      { source: '/business-tools-calculators', destination: '/business', permanent: true },

      // Time & Date Tools & Aliases
      { source: '/time-date-calculators', destination: '/time-date', permanent: true },
      { source: '/date-time', destination: '/time-date', permanent: true },
      { source: '/event-countdown', destination: '/time-date/event-countdown', permanent: true },
      { source: '/event-countdowns', destination: '/time-date/event-countdown', permanent: true },
      { source: '/event-countdown-calculator', destination: '/time-date/event-countdown', permanent: true },
      { source: '/time-date/event-countdowns', destination: '/time-date/event-countdown', permanent: true },
      { source: '/focus-and-break-timer', destination: '/time-date/focus-and-break-timers', permanent: true },
      { source: '/focus-and-break-timers', destination: '/time-date/focus-and-break-timers', permanent: true },
      { source: '/time-date/focus-and-break-timer', destination: '/time-date/focus-and-break-timers', permanent: true },
      { source: '/retirement-countdown-in-workdays', destination: '/time-date/retirement-countdown', permanent: true },
      { source: '/retirement-countdown', destination: '/time-date/retirement-countdown', permanent: true },
      { source: '/time-date/retirement-countdown-in-workdays', destination: '/time-date/retirement-countdown', permanent: true },
      { source: '/add-subtract-time', destination: '/time-date/add-subtract-time-calculator', permanent: true },
      { source: '/add-subtract-time-calculator', destination: '/time-date/add-subtract-time-calculator', permanent: true },
      { source: '/time-date/add-subtract-time', destination: '/time-date/add-subtract-time-calculator', permanent: true },
      { source: '/time-date/time-calculator', destination: '/time-date/add-subtract-time-calculator', permanent: true },
      { source: '/julian-day-number-calculator', destination: '/time-date/julian-day-calculator', permanent: true },
      { source: '/julian-day-calculator', destination: '/time-date/julian-day-calculator', permanent: true },
      { source: '/time-date/julian-day-number-calculator', destination: '/time-date/julian-day-calculator', permanent: true },
      { source: '/leap-year-validator-and-counter', destination: '/time-date/leap-year-calculator', permanent: true },
      { source: '/leap-year-calculator', destination: '/time-date/leap-year-calculator', permanent: true },
      { source: '/time-date/leap-year-validator-and-counter', destination: '/time-date/leap-year-calculator', permanent: true },
      { source: '/military-time-converter', destination: '/time-date/military-time-converter', permanent: true },
      { source: '/unix-timestamp-converter', destination: '/time-date/unix-timestamp-converter', permanent: true },
      { source: '/date-difference-calculator', destination: '/time-date/date-difference', permanent: true },
      { source: '/time-date/date-difference-calculator', destination: '/time-date/date-difference', permanent: true },
      { source: '/time-date/days-between-dates', destination: '/time-date/date-difference', permanent: true },
      { source: '/time-date/days-calculator', destination: '/time-date/date-difference', permanent: true },
      { source: '/business-days-calculator', destination: '/time-date/work-hours', permanent: true },
      { source: '/running-pace-calculator', destination: '/time-date/running-pace-calculator', permanent: true },
      { source: '/running-pace-and-lap-split-calculator', destination: '/time-date/running-pace-calculator', permanent: true },
      { source: '/time-date/running-pace-and-lap-split-calculator', destination: '/time-date/running-pace-calculator', permanent: true },
      { source: '/work-hours-payroll-calculator', destination: '/time-date/work-hours', permanent: true },
      { source: '/time-date/work-hours-payroll-calculator', destination: '/time-date/work-hours', permanent: true },
      { source: '/time-card-calculator', destination: '/time-date/work-hours', permanent: true },
      { source: '/pet-age-converter', destination: '/time-date/pet-age-converter', permanent: true },
      { source: '/moon-phase-calculator', destination: '/time-date/moon-phase-calculator', permanent: true },
      { source: '/solar-eclipse-calculator', destination: '/time-date/solar-eclipse-calculator', permanent: true },
      { source: '/sunrise-sunset-calculator', destination: '/time-date/sunrise-sunset-calculator', permanent: true },
      { source: '/equinox-solstice-calculator', destination: '/time-date/equinox-solstice-calculator', permanent: true },
      { source: '/day-night-world-map', destination: '/time-date/day-night-world-map', permanent: true },
      { source: '/countdown-timer', destination: '/time-date/countdown-timer', permanent: true },
      { source: '/90-minute-ultradian-rhythm-planner', destination: '/time-date/90-minute-ultradian-rhythm-planner', permanent: true },
      { source: '/ultradian-rhythm-planner', destination: '/time-date/90-minute-ultradian-rhythm-planner', permanent: true },
      { source: '/time-date/ultradian-rhythm-planner', destination: '/time-date/90-minute-ultradian-rhythm-planner', permanent: true },
      { source: '/plan-a-project-calculator', destination: '/time-date/plan-a-project-calculator', permanent: true },

      // Math Tools & Aliases
      { source: '/percentage-calculator', destination: '/math/percentage-calculator', permanent: true },
      { source: '/scientific-calculator', destination: '/math/scientific-calculator', permanent: true },

      // Health & Fitness Tools & Aliases
      { source: '/bmi-calculator', destination: '/health-fitness-calculators/bmi', permanent: true },
      { source: '/health/bmi', destination: '/health-fitness-calculators/bmi', permanent: true },
      { source: '/health', destination: '/health-fitness-calculators', permanent: true },
      { source: '/health-fitness', destination: '/health-fitness-calculators', permanent: true },

      // Unit Conversions standardizing on /conversions/
      { source: '/conversion-center', destination: '/conversions', permanent: true },
      { source: '/convert', destination: '/conversions', permanent: true },
      { source: '/conversion', destination: '/conversions', permanent: true },
      { source: '/unit-converters', destination: '/conversions', permanent: true },
      { source: '/unit-converters/volume', destination: '/conversions/volume', permanent: true },
      { source: '/unit-converter-conversion-tools', destination: '/conversions', permanent: true },
      { source: '/length-converter', destination: '/conversions/length', permanent: true },
      { source: '/weight-converter', destination: '/conversions/mass', permanent: true },
      { source: '/weight-mass-converter', destination: '/conversions/mass', permanent: true },
      { source: '/volume-converter', destination: '/conversions/volume', permanent: true },
      { source: '/capacity-converter', destination: '/conversions/volume', permanent: true },
      { source: '/volume-and-capacity-converter', destination: '/conversions/volume', permanent: true },
      { source: '/temperature-converter', destination: '/conversions/temperature', permanent: true },
      { source: '/speed-converter', destination: '/conversions/speed', permanent: true },
      { source: '/speed-velocity-converter', destination: '/conversions/speed', permanent: true },
      { source: '/area-converter', destination: '/conversions/area', permanent: true },
      { source: '/pressure-converter', destination: '/conversions/pressure', permanent: true },
      { source: '/energy-converter', destination: '/conversions/energy', permanent: true },
      { source: '/energy-work-converter', destination: '/conversions/energy', permanent: true },
      { source: '/power-converter', destination: '/conversions/power', permanent: true },
      { source: '/data-storage-converter', destination: '/conversions/data-storage', permanent: true },
      { source: '/data-transfer-converter', destination: '/conversions/data-transfer', permanent: true },
      { source: '/data-transfer-rate-converter', destination: '/conversions/data-transfer', permanent: true },
      { source: '/fuel-economy-converter', destination: '/conversions/fuel-economy', permanent: true },
      { source: '/cooking-converter', destination: '/conversions/cooking', permanent: true },
      { source: '/frequency-converter', destination: '/conversions/frequency', permanent: true },
      { source: '/electrical-converter', destination: '/conversions/electrical', permanent: true },
      { source: '/engineering-converter', destination: '/conversions/engineering', permanent: true },
      { source: '/torque-converter', destination: '/conversions/torque', permanent: true },
      { source: '/number-systems-converter', destination: '/conversions/number-systems', permanent: true },
      { source: '/scientific-converter', destination: '/conversions/scientific', permanent: true },
      { source: '/time-converter', destination: '/conversions/time', permanent: true },
      { source: '/convert/:slug', destination: '/conversions/:slug', permanent: true },
      { source: '/conversion/:slug', destination: '/conversions/:slug', permanent: true },

      // Engineering & Industry Categories
      { source: '/electrical-calculators-sizing-tools', destination: '/electrical', permanent: true },
      { source: '/electrical-tools', destination: '/electrical', permanent: true },
      { source: '/automotive-calculators-estimators', destination: '/automotive', permanent: true },
      { source: '/gear-ratio-speed-at-rpm', destination: '/automotive', permanent: true },
      { source: '/gear-ratio-calculator', destination: '/automotive', permanent: true },
      { source: '/home-construction-calculators', destination: '/home-construction', permanent: true },
      { source: '/education-calculators-academic-planning-tools', destination: '/education', permanent: true },
      { source: '/science-calculators-scientific-tools', destination: '/science', permanent: true },
      { source: '/science-calculators', destination: '/science', permanent: true },
      { source: '/technology-calculators', destination: '/technology', permanent: true },
    ];
  },
};

export default nextConfig;
