const fs = require('fs');
let content = fs.readFileSync('app/finance/FinanceHubClient.tsx', 'utf-8');

const sIdx = content.indexOf('const SCENARIO_BATTLES = [');
const eIdx = content.indexOf('export default function FinanceHubClient()');

if (sIdx !== -1 && eIdx !== -1) {
    const newContent = `const SCENARIO_BATTLES = [
  {
    id: '401k-vs-roth',
    label: '401(k) vs Roth',
    alpha: {
      name: 'Traditional 401(k)',
      tag: 'Pre-Tax',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Get a tax break now. You pay taxes later when you withdraw in retirement.',
      annual: '$23,000',
      benefitLabel: 'Immediate Tax Saved:',
      benefitVal: '+$5,520 / yr',
      benefitColor: 'text-primary',
      effectiveCost: '$17,480',
      estValue: '$2,376,512',
      note: 'Pre-tax balance',
    },
    beta: {
      name: 'Roth IRA',
      tag: 'Post-Tax',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Pay taxes upfront. Your money grows and is withdrawn completely tax-free.',
      annual: '$23,000',
      benefitLabel: 'Tax-Free Withdrawals:',
      benefitVal: '100% Tax-Free',
      benefitColor: 'text-outline',
      effectiveCost: '$23,000',
      estValue: '$2,376,512',
      note: 'Tax-free balance',
    },
    deltaTitle: 'Net After-Tax Outcome',
    deltaValue: '+$184,210',
    deltaDesc: 'Depending on your tax bracket in retirement, a Traditional 401(k) or Roth can provide more spendable cash.',
    barAlphaPercent: '54%',
    barBetaPercent: '46%',
    barAlphaLabel: 'Traditional 401(k)',
    barBetaLabel: 'Roth IRA',
    link: '/fire-forecaster',
    linkText: 'Compare 401(k) vs Roth →',
  },
  {
    id: 'rent-vs-buy',
    label: 'Rent vs Buy',
    alpha: {
      name: 'Buy a Home',
      tag: 'Build Equity',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Lock in your monthly payment and build wealth through home equity over time.',
      annual: '$32,400',
      benefitLabel: 'Equity Built:',
      benefitVal: '+$11,200 / yr',
      benefitColor: 'text-primary',
      effectiveCost: '$21,200 (Interest+Taxes)',
      estValue: '$1,140,000',
      note: 'Home value in 20 years',
    },
    beta: {
      name: 'Rent & Invest',
      tag: 'Invest Savings',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Avoid home maintenance and property taxes. Invest the savings in the stock market.',
      annual: '$26,400',
      benefitLabel: 'Savings Invested:',
      benefitVal: '+$7,200 / yr',
      benefitColor: 'text-secondary',
      effectiveCost: '$26,400',
      estValue: '$985,400',
      note: 'Investment value in 20 yrs',
    },
    deltaTitle: 'Buying Edge at Year 15+',
    deltaValue: '+$154,600',
    deltaDesc: 'After several years, buying usually beats renting as rent prices go up and your home builds equity.',
    barAlphaPercent: '58%',
    barBetaPercent: '42%',
    barAlphaLabel: 'Home Equity',
    barBetaLabel: 'Stock Portfolio',
    link: '/finance/mortgage-calculator',
    linkText: 'Run Rent vs Buy Tool →',
  },
  {
    id: 'mortgage-vs-sp500',
    label: 'Pay Off Debt vs Invest',
    alpha: {
      name: 'Pay Down Mortgage',
      tag: 'Guaranteed Return',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Get a risk-free return equal to your mortgage interest rate. Become debt-free faster.',
      annual: '$12,000 extra',
      benefitLabel: 'Interest Saved:',
      benefitVal: '+$124,500 total',
      benefitColor: 'text-primary',
      effectiveCost: 'No Market Risk',
      estValue: 'Paid in 14 Yrs',
      note: '15 years of freedom',
    },
    beta: {
      name: 'Invest in S&P 500',
      tag: 'Market Growth',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Invest extra cash in the stock market to take advantage of historically higher average returns.',
      annual: '$12,000 extra',
      benefitLabel: 'Expected Growth:',
      benefitVal: '+$318,000 net',
      benefitColor: 'text-secondary',
      effectiveCost: 'Market Ups & Downs',
      estValue: '$482,500',
      note: 'Portfolio in 15 yrs',
    },
    deltaTitle: 'Investment Potential Edge',
    deltaValue: '+$193,500',
    deltaDesc: 'Historically, the stock market earns more over the long run than most mortgage interest rates.',
    barAlphaPercent: '39%',
    barBetaPercent: '61%',
    barAlphaLabel: 'Interest Saved',
    barBetaLabel: 'Market Growth',
    link: '/finance/mortgage-calculator',
    linkText: 'Compare Mortgage vs Investing →',
  },
  {
    id: 'lump-sum-vs-dca',
    label: 'Lump Sum vs DCA',
    alpha: {
      name: 'Lump Sum Investment',
      tag: 'Max Market Time',
      tagColor: 'bg-primary/10 text-primary',
      desc: 'Invest all your money at once. Markets go up more often than they go down over time.',
      annual: '$100,000 upfront',
      benefitLabel: 'Historical Win Rate:',
      benefitVal: '68% of time',
      benefitColor: 'text-primary',
      effectiveCost: 'Immediate entry',
      estValue: '$259,374',
      note: 'In 10 years',
    },
    beta: {
      name: 'Dollar-Cost Averaging',
      tag: 'Less Regret',
      tagColor: 'bg-secondary/10 text-secondary',
      desc: 'Invest smaller amounts over time. Less stressful if the market drops right after you start.',
      annual: '$8,333 / month',
      benefitLabel: 'Risk Protection:',
      benefitVal: 'Lower Volatility',
      benefitColor: 'text-secondary',
      effectiveCost: 'Missed early gains',
      estValue: '$244,120',
      note: 'In 10 years',
    },
    deltaTitle: 'Lump Sum Outperformance',
    deltaValue: '+$15,254',
    deltaDesc: 'Historically, investing everything upfront wins about two-thirds of the time.',
    barAlphaPercent: '68%',
    barBetaPercent: '32%',
    barAlphaLabel: 'Lump Sum Win',
    barBetaLabel: 'DCA Win',
    link: '/investing-and-growth',
    linkText: 'Calculate DCA vs Lump Sum →',
  },
];

const PRESET_AI_SCENARIOS = [
  {
    label: '"Retire at 50 with $2M"',
    query: 'Retire at 50 with $2,000,000',
    steps: [
      {
        num: '01',
        title: 'Retirement Planner',
        badge: 'Goal Tracking',
        badgeColor: 'text-primary',
        numColor: 'bg-primary/10 text-primary',
        desc: 'Find out how much you need to save each month to reach $2M by age 50.',
        link: '/fire-forecaster',
      },
      {
        num: '02',
        title: 'Roth vs 401(k) Planner',
        badge: 'Tax Saving',
        badgeColor: 'text-secondary',
        numColor: 'bg-secondary/10 text-secondary',
        desc: 'Compare the tax benefits of a Roth IRA and a traditional 401(k) account.',
        link: '/fire-forecaster',
      },
      {
        num: '03',
        title: 'Investment Growth',
        badge: 'Growth Estimate',
        badgeColor: 'text-tertiary',
        numColor: 'bg-tertiary/10 text-tertiary',
        desc: 'See how your investments can grow using historical stock market returns.',
        link: '/investing-and-growth',
      },
    ],
  },
  {
    label: '"Buy $550k home vs Rent"',
    query: 'Compare buying a $550k home vs renting',
    steps: [
      {
        num: '01',
        title: 'Monthly Mortgage Payment',
        badge: 'Payment Estimate',
        badgeColor: 'text-primary',
        numColor: 'bg-primary/10 text-primary',
        desc: 'Calculate your full monthly payment including interest, taxes, and insurance.',
        link: '/finance/mortgage-calculator',
      },
      {
        num: '02',
        title: 'Rent vs Buy Compare',
        badge: 'Decision Tool',
        badgeColor: 'text-secondary',
        numColor: 'bg-secondary/10 text-secondary',
        desc: 'Compare the true cost of renting versus building equity as a homeowner.',
        link: '/finance/mortgage-calculator',
      },
      {
        num: '03',
        title: 'Home Equity Tracker',
        badge: 'Net Worth',
        badgeColor: 'text-tertiary',
        numColor: 'bg-tertiary/10 text-tertiary',
        desc: 'See how fast you will build home equity as you pay down your loan over the years.',
        link: '/finance/mortgage-calculator',
      },
    ],
  },
  {
    label: '"Pay off debt vs Save"',
    query: 'Should I pay off student debt or save in a 401(k)?',
    steps: [
      {
        num: '01',
        title: '401(k) Employer Match',
        badge: 'Free Money',
        badgeColor: 'text-primary',
        numColor: 'bg-primary/10 text-primary',
        desc: 'Calculate the free money you gain by contributing enough to get the employer match.',
        link: '/fire-forecaster',
      },
      {
        num: '02',
        title: 'Debt Payoff Calculator',
        badge: 'Interest Saver',
        badgeColor: 'text-secondary',
        numColor: 'bg-secondary/10 text-secondary',
        desc: 'Find the fastest way to pay off your loans and minimize interest costs.',
        link: '/finance/emi-calculator',
      },
      {
        num: '03',
        title: 'Tax Deduction Check',
        badge: 'Tax Benefit',
        badgeColor: 'text-tertiary',
        numColor: 'bg-tertiary/10 text-tertiary',
        desc: 'See if you can deduct student loan interest from your taxes to save even more.',
        link: '/global-tax-calculator',
      },
    ],
  },
];

`;

    content = content.slice(0, sIdx) + newContent + content.slice(eIdx);
    fs.writeFileSync('app/finance/FinanceHubClient.tsx', content);
    console.log("Successfully replaced scenarios block.");
} else {
    console.log("Failed to find start or end index.");
}
