export interface PercentageCurrency {
  code: string;
  symbol: string;
  name: string;
  flag: string;
  locale: string;
  defaultCOGS: number;
  defaultPrice: number;
  defaultRetail: number;
  defaultInvoice: number;
  vatRate: number;
  vatName: string;
}

export const PERCENTAGE_CURRENCIES: PercentageCurrency[] = [
  {
    code: 'USD',
    symbol: '$',
    name: 'United States Dollar',
    flag: '🇺🇸',
    locale: 'en-US',
    defaultCOGS: 40,
    defaultPrice: 100,
    defaultRetail: 240,
    defaultInvoice: 230,
    vatRate: 8.25,
    vatName: 'State / Local Sales Tax',
  },
  {
    code: 'EUR',
    symbol: '€',
    name: 'Euro (Europe)',
    flag: '🇪🇺',
    locale: 'de-DE',
    defaultCOGS: 35,
    defaultPrice: 95,
    defaultRetail: 220,
    defaultInvoice: 200,
    vatRate: 19,
    vatName: 'EU Standard VAT / MwSt',
  },
  {
    code: 'GBP',
    symbol: '£',
    name: 'British Pound',
    flag: '🇬🇧',
    locale: 'en-GB',
    defaultCOGS: 30,
    defaultPrice: 85,
    defaultRetail: 180,
    defaultInvoice: 175,
    vatRate: 20,
    vatName: 'UK Standard VAT',
  },
  {
    code: 'INR',
    symbol: '₹',
    name: 'Indian Rupee',
    flag: '🇮🇳',
    locale: 'en-IN',
    defaultCOGS: 1500,
    defaultPrice: 3500,
    defaultRetail: 8500,
    defaultInvoice: 12500,
    vatRate: 18,
    vatName: 'Standard GST',
  },
  {
    code: 'CAD',
    symbol: 'C$',
    name: 'Canadian Dollar',
    flag: '🇨🇦',
    locale: 'en-CA',
    defaultCOGS: 50,
    defaultPrice: 125,
    defaultRetail: 290,
    defaultInvoice: 280,
    vatRate: 13,
    vatName: 'HST / Combined GST',
  },
  {
    code: 'AUD',
    symbol: 'A$',
    name: 'Australian Dollar',
    flag: '🇦🇺',
    locale: 'en-AU',
    defaultCOGS: 55,
    defaultPrice: 135,
    defaultRetail: 320,
    defaultInvoice: 300,
    vatRate: 10,
    vatName: 'Federal GST',
  },
  {
    code: 'JPY',
    symbol: '¥',
    name: 'Japanese Yen',
    flag: '🇯🇵',
    locale: 'ja-JP',
    defaultCOGS: 4000,
    defaultPrice: 10000,
    defaultRetail: 24000,
    defaultInvoice: 32000,
    vatRate: 10,
    vatName: 'Consumption Tax (Shouhizei)',
  },
  {
    code: 'AED',
    symbol: 'AED ',
    name: 'UAE Dirham',
    flag: '🇦🇪',
    locale: 'en-AE',
    defaultCOGS: 150,
    defaultPrice: 350,
    defaultRetail: 800,
    defaultInvoice: 950,
    vatRate: 5,
    vatName: 'Federal VAT',
  },
  {
    code: 'SGD',
    symbol: 'S$',
    name: 'Singapore Dollar',
    flag: '🇸🇬',
    locale: 'en-SG',
    defaultCOGS: 50,
    defaultPrice: 120,
    defaultRetail: 280,
    defaultInvoice: 300,
    vatRate: 9,
    vatName: 'Singapore GST',
  },
  {
    code: 'CHF',
    symbol: 'CHF ',
    name: 'Swiss Franc',
    flag: '🇨🇭',
    locale: 'de-CH',
    defaultCOGS: 40,
    defaultPrice: 110,
    defaultRetail: 260,
    defaultInvoice: 250,
    vatRate: 8.1,
    vatName: 'Swiss MWST / TVA',
  },
  {
    code: 'NZD',
    symbol: 'NZ$',
    name: 'New Zealand Dollar',
    flag: '🇳🇿',
    locale: 'en-NZ',
    defaultCOGS: 60,
    defaultPrice: 145,
    defaultRetail: 340,
    defaultInvoice: 310,
    vatRate: 15,
    vatName: 'New Zealand GST',
  },
  {
    code: 'ZAR',
    symbol: 'R ',
    name: 'South African Rand',
    flag: '🇿🇦',
    locale: 'en-ZA',
    defaultCOGS: 450,
    defaultPrice: 1200,
    defaultRetail: 2800,
    defaultInvoice: 3500,
    vatRate: 15,
    vatName: 'Standard VAT',
  },
  {
    code: 'BRL',
    symbol: 'R$ ',
    name: 'Brazilian Real',
    flag: '🇧🇷',
    locale: 'pt-BR',
    defaultCOGS: 120,
    defaultPrice: 320,
    defaultRetail: 750,
    defaultInvoice: 900,
    vatRate: 17,
    vatName: 'Standard ICMS / IVA',
  },
  {
    code: 'PHP',
    symbol: '₱',
    name: 'Philippine Peso',
    flag: '🇵🇭',
    locale: 'en-PH',
    defaultCOGS: 1200,
    defaultPrice: 3000,
    defaultRetail: 7000,
    defaultInvoice: 8500,
    vatRate: 12,
    vatName: 'Value-Added Tax (VAT)',
  },
];

export function getPercentageCurrency(code: string): PercentageCurrency {
  return PERCENTAGE_CURRENCIES.find((c) => c.code === code) || PERCENTAGE_CURRENCIES[0];
}
