/**
 * SolveItCalculator Authoritative Platform Registry
 * Single Source of Truth for all Categories, Subcategories, Canonical Calculators, and Counts.
 * All tool counts, category counts, formulas, and verified standards are derived directly from this file.
 */

export interface CanonicalSubcategory {
  id: string;
  name: string;
  path: string;
  description: string;
}

export interface CanonicalCategory {
  id: string;
  name: string;
  slug: string;
  path: string;
  icon: string;
  description: string;
  standardsBody: string;
  subcategories?: CanonicalSubcategory[];
}

export interface CanonicalTool {
  id: string;
  title: string;
  name: string;
  canonicalPath: string;
  category: string;
  subcategory?: string;
  badge: string;
  desc: string;
  keywords: string[];
  formulaDisplay: string;
  calculationStandard: string;
  lastUpdated: string;
}

export const CANONICAL_CATEGORIES: CanonicalCategory[] = [
  {
    id: 'finance',
    name: 'Finance & Banking',
    slug: 'finance',
    path: '/finance',
    icon: 'account_balance',
    description: 'High-precision computational models for mortgages, loans, compound interest, payroll, and statutory tax calculations.',
    standardsBody: 'CFPB (12 CFR Part 1026), IRS Publication 15-T, US Federal Reserve Regulations',
    subcategories: [
      { id: 'mortgages', name: 'Mortgages & Real Estate', path: '/finance/mortgages', description: 'Amortization, PITI, PMI, down payments, and home equity.' },
      { id: 'loans', name: 'Loans & Amortization', path: '/finance/loans', description: 'Equated Monthly Installment (EMI), personal loans, and debt payoff.' },
      { id: 'investing', name: 'Investing & Compound Growth', path: '/finance/investing', description: 'Compound interest, SIP returns, and portfolio trajectory.' },
      { id: 'retirement', name: 'Retirement & Long-Term Planning', path: '/finance/retirement', description: 'FIRE forecasting, safe withdrawal rates, and 401(k) models.' },
      { id: 'taxes', name: 'Tax Engines & Statutory Models', path: '/finance/taxes', description: 'Marginal tax brackets, GST, VAT, and paycheck deductions.' },
      { id: 'banking', name: 'Banking & Cash Accounts', path: '/finance/banking', description: 'APY compound interest, liquidity, and CDs.' },
      { id: 'savings', name: 'Savings & Liquidity', path: '/finance/savings', description: 'Emergency funds, goal accumulation, and compound savings.' },
      { id: 'credit-cards', name: 'Credit Cards & Revolving Credit', path: '/finance/credit-cards', description: 'Minimum payments, interest payoff schedules, and debt snowball.' },
      { id: 'salary', name: 'Salary & Payroll', path: '/finance/salary', description: 'Gross to net pay, hourly wages, and shift compensation.' },
    ],
  },
  {
    id: 'time-date',
    name: 'Date, Time & Productivity',
    slug: 'time-date',
    path: '/time-date',
    icon: 'schedule',
    description: 'Chronological engines, payroll timesheets, astronomical calculators, and global timezone coordination tools.',
    standardsBody: 'ISO 8601 (Time & Date Representation), IERS (Julian Dates), US FLSA (Work Hours)',
    subcategories: [
      { id: 'work-time', name: 'Work Hours & Timesheets', path: '/time-date/work-hours', description: 'Payroll timesheets, break tracking, and overtime under FLSA.' },
      { id: 'calendar', name: 'Calendar & Chronometry', path: '/time-date/age-calculator', description: 'Age in days, date differences, leap years, and Julian dates.' },
      { id: 'astronomy', name: 'Astronomical & Ephemeris', path: '/time-date/solar-eclipse-calculator', description: 'Solar eclipses, moon phases, and equinox calculations.' },
      { id: 'timers', name: 'Timers & Productivity', path: '/time-date/focus-and-break-timers', description: 'Pomodoro rhythms, countdown clocks, and ultradian cycles.' },
    ],
  },
  {
    id: 'math',
    name: 'Mathematics & Statistics',
    slug: 'math',
    path: '/math',
    icon: 'calculate',
    description: 'Deterministic mathematical engines for percentages, statistical distributions, algebra, and scientific notation.',
    standardsBody: 'IEEE 754 Floating-Point Arithmetic & NIST Statistical References',
  },
  {
    id: 'conversions',
    name: 'Universal Unit Conversions',
    slug: 'conversions',
    path: '/conversions',
    icon: 'swap_horiz',
    description: 'Standardized unit conversions across length, mass, volume, temperature, and engineering dimensions.',
    standardsBody: 'NIST SP 811 (Guide for the Use of the International System of Units) & ISO 80000',
  },
  {
    id: 'health-fitness',
    name: 'Health & Physiology',
    slug: 'health-fitness',
    path: '/health-fitness',
    icon: 'favorite',
    description: 'Evidence-based physiological estimators for BMI, BMR, TDEE, body composition, and cardiac training zones.',
    standardsBody: 'American College of Sports Medicine (ACSM), World Health Organization (WHO), CDC Guidelines',
  },
  {
    id: 'electrical',
    name: 'Electrical & Power',
    slug: 'electrical',
    path: '/electrical',
    icon: 'bolt',
    description: 'Wire sizing, voltage drop, Ohm’s law, electricity bills, and circuit breaker calculations.',
    standardsBody: 'National Electrical Code (NEC / NFPA 70 Guidelines) & IEEE Standards',
    subcategories: [
      { id: 'home-wiring', name: 'Home Wiring & Conductors', path: '/electrical', description: 'Wire gauge sizing (AWG), voltage drop, conduit fill, box volume, and breaker ratings.' },
      { id: 'circuits', name: 'Circuits & Fundamentals', path: '/electrical', description: 'Ohm’s law (V, I, R, P), series/parallel resistors, LED resistors, and AC RMS voltage.' },
      { id: 'energy-cost', name: 'Energy & Utility Costs', path: '/electrical', description: 'Electricity bills per kWh, appliance power usage, solar arrays, and generator sizing.' },
      { id: 'electronics-conversions', name: 'Electronic Components & Conversions', path: '/electrical', description: 'Capacitance, inductance, resistor color bands, SMD codes, and unit conversions.' },
    ],
  },
  {
    id: 'automotive',
    name: 'Automotive & Mechanical',
    slug: 'automotive',
    path: '/automotive',
    icon: 'directions_car',
    description: 'Gear ratios, engine RPM at speed, fuel economy, and mechanical estimations.',
    standardsBody: 'SAE International Mechanical & Automotive Standards',
  },
  {
    id: 'home-construction',
    name: 'Home & Construction',
    slug: 'home-construction',
    path: '/home-construction',
    icon: 'home_work',
    description: 'Concrete slab volume, framing lumber, roofing shingles, and square footage calculators.',
    standardsBody: 'International Residential Code (IRC) & ASTM Material Standards',
  },
  {
    id: 'education',
    name: 'Education & Academics',
    slug: 'education',
    path: '/education',
    icon: 'school',
    description: 'GPA calculations, final grade estimators, and academic planning workbenches.',
    standardsBody: 'Standardized Academic Grading Scales (4.0 Scale & Weighted Honors/AP)',
  },
  {
    id: 'science',
    name: 'Science & Physics',
    slug: 'science',
    path: '/science',
    icon: 'science',
    description: 'Kinematics, thermodynamics, wave equations, and fundamental scientific constants.',
    standardsBody: 'CODATA Recommended Values of the Fundamental Physical Constants',
  },
  {
    id: 'technology',
    name: 'Technology & Networking',
    slug: 'technology',
    path: '/technology',
    icon: 'memory',
    description: 'Data transfer rates, storage capacity conversions, and subnet calculators.',
    standardsBody: 'IEEE 802 Standards & IEC 80000-13 Binary Data Prefixes (KiB, MiB, GiB)',
  },
];

export const CANONICAL_TOOLS: CanonicalTool[] = [
  // --- FINANCE SUITE ---
  {
    id: 'mortgage-calculator',
    title: 'Mortgage Calculator',
    name: 'Mortgage Payment & Amortization Calculator',
    canonicalPath: '/finance/mortgage-calculator',
    category: 'finance',
    subcategory: 'mortgages',
    badge: 'PITI & Amortization',
    desc: 'Calculate exact monthly principal and interest, property taxes, home insurance, PMI, and complete amortization schedules.',
    keywords: ['mortgage calculator', 'monthly mortgage payment', 'home loan calculator', 'amortization schedule', 'pmi calculator'],
    formulaDisplay: 'M = P[r(1+r)^n] / [(1+r)^n - 1]',
    calculationStandard: 'CFPB Fixed-Rate Amortization Standard (12 CFR Part 1026)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'compound-interest-calculator',
    title: 'Compound Interest Calculator',
    name: 'Compound Interest & Future Value Calculator',
    canonicalPath: '/finance/compound-interest-calculator',
    category: 'finance',
    subcategory: 'investing',
    badge: 'Compounding Law',
    desc: 'Forecast compound interest growth over time with regular monthly or annual contributions and inflation adjustments.',
    keywords: ['compound interest calculator', 'investment growth', 'future value', 'compound annual growth rate', 'cagr'],
    formulaDisplay: 'A = P(1 + r/n)^(nt) + PMT × [((1 + r/n)^(nt) - 1) / (r/n)]',
    calculationStandard: 'Standard Financial Mathematics & Continuous Compounding Equations',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'investment-calculator',
    title: 'Investment Calculator',
    name: 'Investment & SIP Growth Calculator',
    canonicalPath: '/finance/investment-calculator',
    category: 'finance',
    subcategory: 'investing',
    badge: 'Portfolio Growth',
    desc: 'Calculate investment growth, return on investment (ROI), systematic investment plans (SIP), and asset allocation trajectories.',
    keywords: ['investment calculator', 'sip calculator', 'roi calculator', 'portfolio return', 'mutual fund calculator'],
    formulaDisplay: 'FV = P × (1 + r)^t + PMT × [((1 + r)^t - 1) / r]',
    calculationStandard: 'FINRA Investor Guidelines & Time Value of Money Theory',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'emi-calculator',
    title: 'EMI Calculator',
    name: 'Equated Monthly Installment (EMI) Calculator',
    canonicalPath: '/finance/emi-calculator',
    category: 'finance',
    subcategory: 'loans',
    badge: 'Loan Repayment',
    desc: 'Calculate equated monthly installments for personal, auto, and student loans with total interest breakdown.',
    keywords: ['emi calculator', 'loan installment calculator', 'personal loan emi', 'car loan calculator', 'loan repayment'],
    formulaDisplay: 'E = [P × r × (1 + r)^n] / [(1 + r)^n - 1]',
    calculationStandard: 'Standard Amortizing Loan Reduction Model',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'fire-forecaster',
    title: 'FIRE Calculator',
    name: 'Financial Independence, Retire Early (FIRE) Forecaster',
    canonicalPath: '/finance/fire-forecaster',
    category: 'finance',
    subcategory: 'retirement',
    badge: 'FIRE & SWR',
    desc: 'Estimate your FIRE number, safe withdrawal rate (SWR), and timeline to financial independence based on annual expenditures.',
    keywords: ['fire calculator', 'financial independence retire early', 'safe withdrawal rate', '4 percent rule', 'retirement nest egg'],
    formulaDisplay: 'FIRE Number = Annual Expenses × (1 / SWR) (Standard 25× for 4% Rule)',
    calculationStandard: 'Bengen (1994) & Trinity Study Safe Withdrawal Rate Research',
    lastUpdated: '2026-09-15',
  },

  // --- TIME & DATE SUITE ---
  {
    id: 'age-calculator',
    title: 'Age Calculator',
    name: 'Chronological Age & Milestone Calculator',
    canonicalPath: '/time-date/age-calculator',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Exact Age in Days',
    desc: 'Calculate chronological age in years, months, days, hours, and minutes with leap year adjustment and milestone forecasts.',
    keywords: ['age calculator', 'how old am i', 'exact age calculator', 'age in days', 'chronological age'],
    formulaDisplay: 'Δt = Date(Target) - Date(Birth) with Gregorian Leap Year Calendar Compensation',
    calculationStandard: 'ISO 8601 Calendar & Gregorian Intercalary Cycle',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'work-hours',
    title: 'Work Hours Calculator',
    name: 'Work Hours, Timesheet & Overtime Calculator',
    canonicalPath: '/time-date/work-hours',
    category: 'time-date',
    subcategory: 'work-time',
    badge: 'Timesheet & FLSA',
    desc: 'Track daily shifts, unpaid lunch deductions, total weekly hours, and 1.5× overtime pay according to labor standards.',
    keywords: ['work hours calculator', 'timesheet calculator', 'overtime calculator', 'flsa work hours', 'clock in clock out'],
    formulaDisplay: 'Gross Hours = Σ(ClockOut - ClockIn) - Deductible Breaks; OT = max(0, Hours - 40)',
    calculationStandard: 'US Fair Labor Standards Act (FLSA 29 CFR Part 778)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'date-difference-calculator',
    title: 'Date Difference Calculator',
    name: 'Days Between Dates & Difference Calculator',
    canonicalPath: '/time-date/date-difference-calculator',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Calendar Span',
    desc: 'Calculate the exact number of days, weeks, months, and business days between any two dates in history or the future.',
    keywords: ['date difference calculator', 'days between dates', 'days counter', 'how many days between', 'calendar duration'],
    formulaDisplay: 'Span = |TargetDate - BaseDate| in milliseconds converted to solar days (86,400 s/day)',
    calculationStandard: 'Gregorian Calendar Astronomical Algorithm',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'countdown-timer',
    title: 'Countdown Timer',
    name: 'Live Countdown Timer & Event Chronometer',
    canonicalPath: '/time-date/countdown-timer',
    category: 'time-date',
    subcategory: 'timers',
    badge: 'Live Ticking Clock',
    desc: 'Create accurate down-to-the-second countdowns for deadlines, exams, birthdays, and product launches with sound notifications.',
    keywords: ['countdown timer', 'online countdown', 'timer with seconds', 'event countdown', 'stopwatch and timer'],
    formulaDisplay: 'T_remaining = max(0, TargetEpoch - CurrentEpoch)',
    calculationStandard: 'W3C High Resolution Time & Performance API',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'event-countdown',
    title: 'Event Countdown',
    name: 'Event Countdown & Milestone Chronometer',
    canonicalPath: '/time-date/event-countdown',
    category: 'time-date',
    subcategory: 'timers',
    badge: 'Milestone Tracker',
    desc: 'Track exact days and hours left until weddings, vacations, retirement, or milestones with business days filtering.',
    keywords: ['event countdown', 'wedding countdown', 'vacation countdown', 'days until event', 'milestone tracker'],
    formulaDisplay: 'Days_left = ceil((EventDate - Now) / 86400000)',
    calculationStandard: 'Gregorian Astronomical Calendar Standards',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'focus-and-break-timers',
    title: 'Focus & Break Timer',
    name: 'Pomodoro & 52/17 Focus & Break Timer',
    canonicalPath: '/time-date/focus-and-break-timers',
    category: 'time-date',
    subcategory: 'timers',
    badge: 'Pomodoro & 52/17',
    desc: 'Optimize cognitive focus and mental recovery using classic 25/5 Pomodoro intervals and 52/17 desk rhythms.',
    keywords: ['focus timer', 'pomodoro timer', '52 17 timer', 'break timer', 'productivity timer'],
    formulaDisplay: 'Work Block: 25/50/52 min; Break Block: 5/10/17 min cyclically scheduled',
    calculationStandard: 'Ergonomic Desk Productivity Studies & Pomodoro Technique Standard',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'retirement-countdown',
    title: 'Retirement Countdown',
    name: 'Retirement Countdown in Workdays & Shifts',
    canonicalPath: '/time-date/retirement-countdown',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Workdays to Retirement',
    desc: 'Calculate exact remaining workdays, shifts, and working hours until retirement after factoring in PTO balance and paid holidays.',
    keywords: ['retirement countdown in workdays', 'workdays until retirement', 'retirement shift counter', 'final working day', 'pto deduction'],
    formulaDisplay: 'Net Workdays = Total Calendar Workdays - Annual PTO - Statutory Paid Holidays',
    calculationStandard: 'Standard Shift Scheduling & BLS Annual Workday Metrics',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'add-subtract-time-calculator',
    title: 'Add or Subtract Time Calculator',
    name: 'Time Addition & Subtraction Calculator',
    canonicalPath: '/time-date/add-subtract-time-calculator',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Time Arithmetic',
    desc: 'Add or subtract days, hours, minutes, and seconds from any date and time with 24-hour rollover precision.',
    keywords: ['add time calculator', 'subtract time calculator', 'time math', 'date plus hours', 'time addition and subtraction'],
    formulaDisplay: 'T_final = T_base ± (Δd × 86400 + Δh × 3600 + Δm × 60 + Δs)',
    calculationStandard: 'Sexagesimal (Base-60) Mathematical Arithmetic & ISO 8601',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'military-time-converter',
    title: 'Military Time Converter',
    name: 'Military Time & 24-Hour Clock Converter',
    canonicalPath: '/time-date/military-time-converter',
    category: 'time-date',
    subcategory: 'calendar',
    badge: '24-Hour & NATO DTG',
    desc: 'Convert between 12-hour civilian time, 24-hour military notation, NATO phonetic pronunciation, and Date-Time Groups (DTG).',
    keywords: ['military time converter', '24 hour time converter', 'nato phonetic time', 'date time group dtg', 'civilian to military time'],
    formulaDisplay: 'PM Hours = 12:00 PM to 11:59 PM → Add 12 to hour (except 12:00 PM = 1200); AM Hours = 12:00 AM → 0000',
    calculationStandard: 'STANAG 2211 & ACP 121(I) International Defense Standards',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'unix-timestamp-converter',
    title: 'Unix Timestamp Converter',
    name: 'Unix Epoch Time & Timestamp Converter',
    canonicalPath: '/time-date/unix-timestamp-converter',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'POSIX Epoch Seconds',
    desc: 'Convert Unix epoch timestamps (seconds and milliseconds) to human-readable UTC and local date formats.',
    keywords: ['unix timestamp converter', 'epoch time', 'posix timestamp', 'timestamp to date', 'epoch converter'],
    formulaDisplay: 'Timestamp = Seconds elapsed since 1970-01-01 00:00:00 UTC (excluding leap seconds)',
    calculationStandard: 'POSIX.1-2017 (IEEE Std 1003.1-2017)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'julian-day-calculator',
    title: 'Julian Day Calculator',
    name: 'Julian Day Number (JDN) & Modified Julian Date (MJD) Calculator',
    canonicalPath: '/time-date/julian-day-calculator',
    category: 'time-date',
    subcategory: 'astronomy',
    badge: 'Astronomical JDN',
    desc: 'Calculate Julian Day Numbers (JDN), Modified Julian Dates (MJD), and day of year with astronomical ephemeris precision.',
    keywords: ['julian day calculator', 'julian day number', 'jdn', 'mjd', 'modified julian date', 'astronomical day of year'],
    formulaDisplay: 'JDN = [367Y - 7(Y + (M + 9)/12)/4 + 275M/9 + D + 1721013.5]',
    calculationStandard: 'IERS Conventions & Astronomical Algorithms (Meeus, 1998)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'leap-year-calculator',
    title: 'Leap Year Calculator',
    name: 'Leap Year Validator & 400-Year Cycle Counter',
    canonicalPath: '/time-date/leap-year-calculator',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Gregorian Intercalary',
    desc: 'Verify whether any year is a leap year under the Gregorian 400-year cycle rule and count intercalary days between dates.',
    keywords: ['leap year calculator', 'is it a leap year', 'next leap year', 'february 29', '400 year cycle'],
    formulaDisplay: 'IsLeap = (Year mod 4 == 0 AND Year mod 100 != 0) OR (Year mod 400 == 0)',
    calculationStandard: 'Papal Bull Inter Gravissimas (1582) & ISO 8601 Calendar Rules',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'running-pace-calculator',
    title: 'Running Pace Calculator',
    name: 'Running Pace, Lap Splits & Race Finish Estimator',
    canonicalPath: '/time-date/running-pace-calculator',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Splits & Finish Time',
    desc: 'Calculate your required running pace per mile or kilometer for 5K, 10K, half marathon, and full marathon finish targets.',
    keywords: ['running pace calculator', 'pace per mile', '5k pace', 'marathon pace calculator', 'lap splits estimator'],
    formulaDisplay: 'Pace = Total Time / Total Distance; Time = Pace × Distance',
    calculationStandard: 'World Athletics Standard Track & Field Measurement Standards',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'pet-age-converter',
    title: 'Pet Age Converter',
    name: 'Dog & Cat Age in Human Years Calculator',
    canonicalPath: '/time-date/pet-age-converter',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Epigenetic Clock',
    desc: 'Convert canine and feline chronological ages to physiological human years using canine DNA methylation epigenetic algorithms.',
    keywords: ['dog age calculator', 'cat age calculator', 'dog years to human years', 'pet age in human years'],
    formulaDisplay: 'Human Age = 16 × ln(Dog Age) + 31 (UC San Diego Canine Epigenetics Model)',
    calculationStandard: 'Wang et al. (2020) Quantitative Translation of Dog-to-Human Aging (Cell Systems)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'moon-phase-calculator',
    title: 'Moon Phase Calculator',
    name: 'Moon Phase, Lunar Illumination & Cycle Calculator',
    canonicalPath: '/time-date/moon-phase-calculator',
    category: 'time-date',
    subcategory: 'astronomy',
    badge: 'Synodic Month',
    desc: 'Calculate the current moon phase, percentage illumination, and dates of the next full, new, and quarter moons.',
    keywords: ['moon phase calculator', 'current moon phase', 'lunar illumination', 'next full moon date', 'synodic lunar cycle'],
    formulaDisplay: 'Lunar Age = (JDN - KnownNewMoonJDN) mod 29.53058867 days',
    calculationStandard: 'US Naval Observatory (USNO) Astronomical Ephemeris',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'solar-eclipse-calculator',
    title: 'Solar Eclipse Calculator',
    name: 'Solar Eclipse Path & Geometry Calculator',
    canonicalPath: '/time-date/solar-eclipse-calculator',
    category: 'time-date',
    subcategory: 'astronomy',
    badge: 'Saros Series',
    desc: 'Compute solar eclipse contacts, totality durations, Saros cycle numbers, and solar filter requirements.',
    keywords: ['solar eclipse calculator', 'solar eclipse totality', 'saros cycle', 'eclipse path and duration'],
    formulaDisplay: 'Besselian Elements & Umbral Geometry Calculations',
    calculationStandard: 'NASA Eclipse Ephemeris & ISO 12312-2 Eye Safety Standards',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'sunrise-sunset-calculator',
    title: 'Sunrise Sunset Calculator',
    name: 'Sunrise, Sunset & Solar Noon Ephemeris',
    canonicalPath: '/time-date/sunrise-sunset-calculator',
    category: 'time-date',
    subcategory: 'astronomy',
    badge: 'Solar Zenith',
    desc: 'Calculate precise sunrise, sunset, solar noon, and civil dawn times based on geographic latitude and longitude coordinates.',
    keywords: ['sunrise sunset calculator', 'solar noon calculator', 'daylight hours', 'civil twilight dawn'],
    formulaDisplay: 'cos(ω) = (sin(a) - sin(φ)sin(δ)) / (cos(φ)cos(δ)) where a = -0.833°',
    calculationStandard: 'NOAA Solar Calculation Algorithm (Jean Meeus Astronomical Algorithms)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'equinox-solstice-calculator',
    title: 'Equinox & Solstice Calculator',
    name: 'Equinox & Solstice Astronomical Calculator',
    canonicalPath: '/time-date/equinox-solstice-calculator',
    category: 'time-date',
    subcategory: 'astronomy',
    badge: 'Solar Declination',
    desc: 'Calculate the exact astronomical timestamps for the vernal equinox, summer solstice, autumnal equinox, and winter solstice.',
    keywords: ['equinox calculator', 'solstice calculator', 'first day of spring timestamp', 'summer solstice date'],
    formulaDisplay: 'Apparent Ecliptic Longitude λ = 0° (Vernal), 90° (Summer), 180° (Autumnal), 270° (Winter)',
    calculationStandard: 'VSOP87 Planetary Theory & Bureau des Longitudes',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'day-night-world-map',
    title: 'Day and Night World Map',
    name: 'Live Solar Terminator & Day-Night World Map',
    canonicalPath: '/time-date/day-night-world-map',
    category: 'time-date',
    subcategory: 'astronomy',
    badge: 'Solar Terminator',
    desc: 'Interactive world map illustrating the live solar terminator, subsolar point, and regions experiencing daylight versus darkness.',
    keywords: ['day night world map', 'solar terminator map', 'daylight map', 'subsolar point live'],
    formulaDisplay: 'Terminator Curve: tan(δ) = -cos(λ - λ_sub) / tan(φ)',
    calculationStandard: 'Astronomical Solar Coordinates & Spherical Trigonometry',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'world-clock-grid',
    title: 'World Clock Grid',
    name: 'Global World Clock & UTC Offset Grid',
    canonicalPath: '/time-date/world-clock-grid',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'IANA Timezones',
    desc: 'Display real-time synchronized local clocks across major financial and metropolitan hubs with active daylight saving alerts.',
    keywords: ['world clock grid', 'global time zones', 'utc offset clock', 'international meeting clock'],
    formulaDisplay: 'Local Time = UTC + Offset(tz, currentInstant)',
    calculationStandard: 'IANA Time Zone Database (tzdb 2026) & Olson Database',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'time-zone-converter',
    title: 'Time Zone Converter',
    name: 'Interactive Time Zone Meeting Planner',
    canonicalPath: '/time-date/time-zone-converter',
    category: 'time-date',
    subcategory: 'calendar',
    badge: 'Meeting Planner',
    desc: 'Convert times across global cities and identify overlapping working hours for cross-border collaboration.',
    keywords: ['time zone converter', 'timezone meeting planner', 'convert est to pst', 'convert gmt to local time'],
    formulaDisplay: 'Time_Target = Time_Source + (Offset_Target - Offset_Source)',
    calculationStandard: 'IANA TZ Database & ISO 8601 UTC Designations',
    lastUpdated: '2026-09-15',
  },
  {
    id: '90-minute-ultradian-rhythm-planner',
    title: '90-Minute Ultradian Rhythm Planner',
    name: '90-Minute Basic Rest-Activity Cycle (BRAC) Planner',
    canonicalPath: '/time-date/90-minute-ultradian-rhythm-planner',
    category: 'time-date',
    subcategory: 'timers',
    badge: 'BRAC Chronobiology',
    desc: 'Plan daily deep work blocks synchronized with the biological 90-minute Basic Rest-Activity Cycle and 20-minute refractory pauses.',
    keywords: ['ultradian rhythm planner', '90 minute focus cycle', 'basic rest activity cycle brac', 'deep work blocks'],
    formulaDisplay: 'Cycle = 90 min Beta/Gamma Peak Focus + 20 min Parasympathetic Recovery',
    calculationStandard: 'Kleitman Chronobiology BRAC Literature (1963) & Ericsson Deliberate Practice Models',
    lastUpdated: '2026-09-15',
  },

  // --- MATHEMATICS SUITE ---
  {
    id: 'percentage-calculator',
    title: 'Percentage Calculator',
    name: 'Comprehensive Percentage & Percentage Change Calculator',
    canonicalPath: '/math/percentage-calculator',
    category: 'math',
    badge: '3-Way Variations',
    desc: 'Solve percentage increases, percentage decreases, differences between two numbers, and fraction-to-percentage conversions.',
    keywords: ['percentage calculator', 'percent increase calculator', 'percent decrease', 'percentage difference', 'what percent of'],
    formulaDisplay: 'Percent = (Part / Whole) × 100; % Change = ((New - Old) / Old) × 100',
    calculationStandard: 'Standard Elementary Algebra & IEEE 754 High-Precision Math',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'standard-deviation-calculator',
    title: 'Standard Deviation Calculator',
    name: 'Sample & Population Standard Deviation Calculator',
    canonicalPath: '/math/standard-deviation-calculator',
    category: 'math',
    badge: 'Sample & Population',
    desc: 'Compute sample standard deviation (s), population standard deviation (σ), variance, mean, and sum of squares with step-by-step math.',
    keywords: ['standard deviation calculator', 'sample standard deviation', 'variance calculator', 'population standard deviation', 'standard error'],
    formulaDisplay: 's = √[Σ(x_i - x̄)² / (n - 1)]; σ = √[Σ(x_i - μ)² / N]',
    calculationStandard: 'NIST/SEMATECH e-Handbook of Statistical Methods',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'scientific-calculator',
    title: 'Scientific Calculator',
    name: 'Full High-Precision Scientific Calculator',
    canonicalPath: '/math/scientific-calculator',
    category: 'math',
    badge: 'Trigonometry & Log',
    desc: 'High-precision scientific evaluation engine supporting trigonometry, logarithms, factorials, roots, and scientific notation.',
    keywords: ['scientific calculator', 'online scientific calculator', 'trig calculator', 'logarithm calculator', 'fraction solver'],
    formulaDisplay: 'Algebraic Order of Operations (PEMDAS / BODMAS) with IEEE 754 Double Precision',
    calculationStandard: 'IEEE 754 Standard for Floating-Point Arithmetic',
    lastUpdated: '2026-09-15',
  },

  // --- HEALTH & FITNESS SUITE ---
  {
    id: 'bmi-calculator',
    title: 'BMI Calculator',
    name: 'Body Mass Index (BMI) & Prime Index Calculator',
    canonicalPath: '/health-fitness/bmi-calculator',
    category: 'health-fitness',
    badge: 'WHO Clinical Standards',
    desc: 'Calculate Body Mass Index (BMI) and healthy weight ranges for adults with WHO classification thresholds and metric/imperial toggles.',
    keywords: ['bmi calculator', 'body mass index', 'bmi categories', 'healthy weight range', 'bmi formula'],
    formulaDisplay: 'BMI = Weight (kg) / [Height (m)]² or (Weight (lb) / [Height (in)]²) × 703',
    calculationStandard: 'World Health Organization (WHO) Technical Report Series 854',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'tdee-calculator',
    title: 'TDEE Calculator',
    name: 'Total Daily Energy Expenditure (TDEE) Calculator',
    canonicalPath: '/health-fitness/tdee',
    category: 'health-fitness',
    badge: 'Mifflin-St Jeor',
    desc: 'Calculate Total Daily Energy Expenditure (TDEE) and target maintenance calories using the clinical Mifflin-St Jeor equation.',
    keywords: ['tdee calculator', 'total daily energy expenditure', 'maintenance calories', 'calorie deficit', 'bmr and tdee'],
    formulaDisplay: 'TDEE = BMR × Physical Activity Level (PAL 1.2 to 1.9)',
    calculationStandard: 'Mifflin-St Jeor Equation (1990) & WHO Energy Requirements',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'body-fat-calculator',
    title: 'Body Fat Calculator',
    name: 'U.S. Navy Body Fat Percentage Calculator',
    canonicalPath: '/health-fitness/body-fat',
    category: 'health-fitness',
    badge: 'US Navy Circumference',
    desc: 'Estimate body fat percentage and fat-free mass using circumference measurements developed by the Naval Health Research Center.',
    keywords: ['body fat calculator', 'navy body fat formula', 'body fat percentage', 'lean mass calculator'],
    formulaDisplay: 'Men: 495 / (1.0324 - 0.19077·log(waist - neck) + 0.15456·log(height)) - 450',
    calculationStandard: 'Hodgdon & Beckett (1984) Naval Health Research Center Standard',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'ideal-body-weight',
    title: 'Ideal Body Weight Calculator',
    name: 'Ideal Body Weight (IBW) Calculator',
    canonicalPath: '/health-fitness/ideal-body-weight',
    category: 'health-fitness',
    badge: 'Clinical Formulas',
    desc: 'Compare ideal body weight estimates across validated medical formulas: Devine, Robinson, Miller, and Hamwi.',
    keywords: ['ideal body weight calculator', 'ibw devine formula', 'healthy weight for height', 'hamwi formula'],
    formulaDisplay: 'Devine (Men): 50.0 kg + 2.3 kg per inch over 5 feet; Women: 45.5 kg + 2.3 kg per inch',
    calculationStandard: 'Devine (1974) & Hamwi (1964) Pharmacokinetic Dosing Guidelines',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'max-heart-rate',
    title: 'Target Heart Rate Calculator',
    name: 'Target Heart Rate Zones & Karvonen Formula Calculator',
    canonicalPath: '/health-fitness/target-heart-rate',
    category: 'health-fitness',
    badge: 'Karvonen Heart Reserve',
    desc: 'Calculate aerobic, anaerobic, and Zone 2 cardiovascular training zones using the Karvonen heart rate reserve formula.',
    keywords: ['target heart rate calculator', 'heart rate training zones', 'karvonen formula', 'zone 2 cardio', 'max heart rate'],
    formulaDisplay: 'THR = ((HR_max - HR_rest) × %Intensity) + HR_rest where HR_max = 208 - (0.7 × Age)',
    calculationStandard: 'Tanaka et al. (2001) & American College of Sports Medicine (ACSM)',
    lastUpdated: '2026-09-15',
  },

  // --- UNIVERSAL CONVERSIONS SUITE ---
  {
    id: 'length-converter',
    title: 'Length Converter',
    name: 'Universal Length & Distance Unit Converter',
    canonicalPath: '/conversions/length',
    category: 'conversions',
    badge: 'NIST Standards',
    desc: 'Convert length and distance between inches, feet, yards, miles, centimeters, meters, and kilometers.',
    keywords: ['length converter', 'inches to cm', 'feet to meters', 'miles to km', 'distance converter'],
    formulaDisplay: 'Metric Base: Meter (m); 1 Inch = exactly 0.0254 m (1959 International Yard & Pound Agreement)',
    calculationStandard: 'NIST Special Publication 811 & ISO 80000-3',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'mass-converter',
    title: 'Weight & Mass Converter',
    name: 'Universal Weight & Mass Unit Converter',
    canonicalPath: '/conversions/mass',
    category: 'conversions',
    badge: 'NIST Standards',
    desc: 'Convert weight and mass between grams, kilograms, milligrams, pounds, ounces, stones, and metric tonnes.',
    keywords: ['weight converter', 'mass converter', 'pounds to kg', 'grams to ounces', 'kg to lbs'],
    formulaDisplay: 'Base: Kilogram (kg); 1 Pound (avoirdupois) = exactly 0.45359237 kg',
    calculationStandard: 'NIST Special Publication 811 & 26th General Conference on Weights and Measures (CGPM)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'volume-converter',
    title: 'Volume & Capacity Converter',
    name: 'Universal Volume & Fluid Capacity Converter',
    canonicalPath: '/conversions/volume',
    category: 'conversions',
    badge: 'NIST Standards',
    desc: 'Convert fluid ounces, cups, tablespoons, teaspoons, milliliters, liters, gallons, and cubic meters.',
    keywords: ['volume converter', 'liters to gallons', 'milliliters to fluid ounces', 'cups to ml', 'tablespoons to teaspoons'],
    formulaDisplay: 'Base: Liter (L); 1 US Gallon = exactly 231 cubic inches = 3.785411784 L',
    calculationStandard: 'NIST Handbook 44 & US Customary System Definitions',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'temperature-converter',
    title: 'Temperature Converter',
    name: 'Celsius, Fahrenheit & Kelvin Temperature Converter',
    canonicalPath: '/conversions/temperature',
    category: 'conversions',
    badge: 'ITS-90 Scale',
    desc: 'Convert temperatures between Celsius (°C), Fahrenheit (°F), Kelvin (K), and Rankine (°R) with step-by-step arithmetic.',
    keywords: ['temperature converter', 'celsius to fahrenheit', 'fahrenheit to celsius', 'kelvin to celsius', 'temp conversion formula'],
    formulaDisplay: '°F = (°C × 9/5) + 32; °C = (°F - 32) × 5/9; K = °C + 273.15',
    calculationStandard: 'International Temperature Scale of 1990 (ITS-90)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'area-converter',
    title: 'Area Converter',
    name: 'Universal Area & Surface Measure Converter',
    canonicalPath: '/conversions/area',
    category: 'conversions',
    badge: 'NIST Standards',
    desc: 'Convert square feet, square meters, acres, hectares, square miles, and square kilometers.',
    keywords: ['area converter', 'square feet to square meters', 'acres to hectares', 'sq ft to acres'],
    formulaDisplay: '1 Acre = 43,560 sq ft = 4,046.8564224 m²; 1 Hectare = 10,000 m²',
    calculationStandard: 'NIST SP 811 & ISO 80000-3',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'speed-converter',
    title: 'Speed Converter',
    name: 'Universal Speed & Velocity Converter',
    canonicalPath: '/conversions/speed',
    category: 'conversions',
    badge: 'SI & Nautical',
    desc: 'Convert miles per hour (mph), kilometers per hour (km/h), knots, and meters per second (m/s).',
    keywords: ['speed converter', 'mph to kmh', 'kmh to mph', 'knots to mph', 'meters per second to kmh'],
    formulaDisplay: '1 Knot = 1 Nautical Mile/hour = exactly 1.852 km/h; 1 mph = 1.609344 km/h',
    calculationStandard: 'International Hydrographic Organization & NIST SP 811',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'pressure-converter',
    title: 'Pressure Converter',
    name: 'Pressure & Stress Unit Converter',
    canonicalPath: '/conversions/pressure',
    category: 'conversions',
    badge: 'SI Pascal',
    desc: 'Convert psi, bar, pascals (Pa), kilopascals (kPa), atmospheres (atm), and millimeters of mercury (mmHg).',
    keywords: ['pressure converter', 'psi to bar', 'bar to psi', 'kpa to psi', 'atm to pascals'],
    formulaDisplay: '1 Standard Atmosphere (atm) = exactly 101,325 Pa; 1 bar = 100,000 Pa; 1 psi ≈ 6,894.757 Pa',
    calculationStandard: 'ISO 80000-4 & International Standard Atmosphere (ISA)',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'energy-converter',
    title: 'Energy Converter',
    name: 'Energy, Work & Heat Converter',
    canonicalPath: '/conversions/energy',
    category: 'conversions',
    badge: 'Joules & Calories',
    desc: 'Convert joules (J), kilojoules (kJ), calories, kilocalories (dietary calories), watt-hours (Wh), and British Thermal Units (BTU).',
    keywords: ['energy converter', 'joules to calories', 'kj to kcal', 'btu to joules', 'kwh to joules'],
    formulaDisplay: '1 Thermochemical Calorie = 4.184 J; 1 kWh = exactly 3,600,000 J; 1 BTU_IT ≈ 1,055.056 J',
    calculationStandard: 'NIST SP 811 & ISO 80000-5',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'power-converter',
    title: 'Power Converter',
    name: 'Power & Mechanical Energy Rate Converter',
    canonicalPath: '/conversions/power',
    category: 'conversions',
    badge: 'Watts & Horsepower',
    desc: 'Convert watts (W), kilowatts (kW), megawatts (MW), mechanical horsepower (hp), and metric horsepower (PS).',
    keywords: ['power converter', 'watts to horsepower', 'kw to hp', 'horsepower to watts', 'megawatts to kilowatts'],
    formulaDisplay: '1 Mechanical Horsepower (550 ft·lbf/s) = 745.69987158227022 W; 1 Metric HP (PS) = 735.49875 W',
    calculationStandard: 'NIST SP 811 & ISO 80000-5',
    lastUpdated: '2026-09-15',
  },
  {
    id: 'grams-to-tablespoons',
    title: 'Grams to Tablespoons',
    name: 'Grams to Tablespoons Culinary Metrology Converter',
    canonicalPath: '/conversions/grams-to-tablespoons',
    category: 'conversions',
    badge: 'USDA Bulk Density',
    desc: 'Convert grams to tablespoons with ingredient-specific bulk densities for flour, sugar, butter, oil, honey, and salt.',
    keywords: ['grams to tablespoons', 'convert grams to tablespoons', 'butter grams to tbsp', 'flour grams to tablespoons'],
    formulaDisplay: 'Tablespoons = Grams / (Density (g/ml) × 14.7868 ml/tbsp)',
    calculationStandard: 'USDA FoodData Central Bulk Density Calibration',
    lastUpdated: '2026-09-15',
  },

  // --- ELECTRICAL & ELECTRONICS SUITE (MATCHING INCH CALCULATOR CATALOG) ---
  {
    id: 'wire-size-calculator',
    title: 'Wire Size & Gauge Calculator',
    name: 'Wire Gauge (AWG) & Cable Thickness Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'home-wiring',
    badge: 'NEC Standard',
    desc: 'Find the safest American Wire Gauge (AWG) thickness for copper and aluminum conductors based on amps and continuous load.',
    keywords: ['wire size calculator', 'wire gauge calculator', 'awg calculator', 'electrical wire size', 'cable sizing'],
    formulaDisplay: 'Circular Mils = (2 × K × I × L) / Max Allowable Voltage Drop',
    calculationStandard: 'NEC Chapter 9 Table 8 & NEC Table 310.16 Ampacity Standard',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'voltage-drop-calculator',
    title: 'Voltage Drop Calculator',
    name: 'Single-Phase & 3-Phase Voltage Loss Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'home-wiring',
    badge: '3% Safety Rule',
    desc: 'Calculate voltage lost over long wire distances to prevent motor overheating and ensure NEC 3% compliance.',
    keywords: ['voltage drop calculator', 'voltage loss calculator', 'single phase voltage drop', '3 phase voltage drop', 'nec voltage drop'],
    formulaDisplay: '1-Phase: VD = (2 × K × I × L) / CM ; 3-Phase: VD = (√3 × K × I × L) / CM',
    calculationStandard: 'National Electrical Code (NEC Informational Note 210.19(A))',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'conduit-fill-calculator',
    title: 'Conduit Fill & Wire Capacity',
    name: 'Conduit Fill & Pipe Capacity Sizer',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'home-wiring',
    badge: 'NEC Chapter 9',
    desc: 'Calculate how many wires can safely fit into EMT, PVC, IMC, or Rigid conduit without exceeding 40% fill limits.',
    keywords: ['conduit fill calculator', 'pipe fill calculator', 'emt conduit fill', 'pvc conduit sizing', 'wire capacity conduit'],
    formulaDisplay: 'Conduit Fill % = (Total Area of All Conductors / Total Internal Area of Conduit) × 100%',
    calculationStandard: 'NEC Chapter 9 Table 1 (40% Maximum Fill for 3+ Conductors)',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'electrical-box-fill-calculator',
    title: 'Electrical Box Volume & Fill',
    name: 'Electrical Box Fill & Cubic Inch Capacity Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'home-wiring',
    badge: 'NEC 314.16',
    desc: 'Calculate total volume allowances for conductors, clamps, switches, receptacles, and grounding wires in junction boxes.',
    keywords: ['electrical box fill calculator', 'box volume calculator', 'junction box fill', 'nec box sizing', 'gang box volume'],
    formulaDisplay: 'Total Volume Required = Σ (Conductor Equivalents × Volume Allowance per Gauge in cu in)',
    calculationStandard: 'NEC Article 314.16(B) Box Volume Calculations',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'circuit-breaker-calculator',
    title: 'Circuit Breaker & Continuous Load Sizer',
    name: 'Circuit Breaker Ampacity & Safety Sizer',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'home-wiring',
    badge: '80% Safety Rule',
    desc: 'Size 15A, 20A, 30A, 50A breakers and verify that continuous loads running for 3+ hours do not exceed 80% capacity.',
    keywords: ['circuit breaker calculator', 'breaker size calculator', 'continuous load calculator', '15 amp vs 20 amp breaker'],
    formulaDisplay: 'Minimum Breaker Rating = (Continuous Load Amps × 1.25) + Non-Continuous Load Amps',
    calculationStandard: 'NEC Article 210.20 & Article 215.3 Overcurrent Protection',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'ohms-law-calculator',
    title: 'Ohm’s Law Calculator (V, I, R, P)',
    name: 'Ohm’s Law & Electrical Power Solver',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'circuits',
    badge: 'Core Formula',
    desc: 'Calculate Voltage (Volts), Current (Amps), Resistance (Ohms), and Power (Watts) instantly from any two known values.',
    keywords: ['ohms law calculator', 'voltage current resistance', 'volts amps watts calculator', 'power wheel calculator', 'v ir formula'],
    formulaDisplay: 'V = I × R ; P = V × I = I² × R = V² / R',
    calculationStandard: 'Fundamental Ohm & Joule Thermodynamic Equations',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'series-parallel-resistor-calculator',
    title: 'Series & Parallel Resistor Calculator',
    name: 'Series and Parallel Circuit Resistance Solver',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'circuits',
    badge: 'Network Solver',
    desc: 'Calculate total equivalent resistance for any number of resistors connected in series or parallel branches.',
    keywords: ['parallel resistor calculator', 'series resistor calculator', 'equivalent resistance', 'resistor network calculator'],
    formulaDisplay: 'Series: R_total = R₁ + R₂ + ... ; Parallel: 1/R_total = 1/R₁ + 1/R₂ + ...',
    calculationStandard: 'Kirchhoff’s Current & Voltage Laws (KCL & KVL)',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'led-resistor-calculator',
    title: 'LED Current-Limiting Resistor Calculator',
    name: 'LED Ballast Resistor & Power Dissipation Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'circuits',
    badge: 'LED Protection',
    desc: 'Calculate the exact resistor ohms and minimum wattage required to safely power single or multiple LEDs without burnout.',
    keywords: ['led resistor calculator', 'led series resistor', 'current limiting resistor', 'led power calculator', 'forward voltage drop'],
    formulaDisplay: 'Resistor (Ω) = (Supply Voltage - LED Forward Voltage) / Desired LED Current (A)',
    calculationStandard: 'Standard Diode Forward-Bias Circuit Modeling',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'ac-rms-peak-voltage-calculator',
    title: 'Peak, RMS & Peak-to-Peak Voltage Calculator',
    name: 'AC Waveform RMS & Peak Voltage Converter',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'circuits',
    badge: 'AC Waveform',
    desc: 'Convert between Root Mean Square (RMS) voltage, peak voltage ($V_{pk}$), and peak-to-peak voltage ($V_{pp}$) for sine waves.',
    keywords: ['rms voltage calculator', 'peak voltage calculator', 'peak to peak voltage', 'ac to dc voltage', 'sine wave voltage'],
    formulaDisplay: 'V_RMS = V_Peak / √2 ≈ 0.7071 × V_Peak ; V_Peak-to-Peak = 2 × V_Peak',
    calculationStandard: 'IEEE Standard for Sinusoidal Alternating Current Metrics',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'power-factor-calculator',
    title: 'Power Factor & Real vs Apparent Power',
    name: 'AC Power Factor, Real (kW) & Apparent (kVA) Sizer',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'circuits',
    badge: 'Power Triangle',
    desc: 'Calculate power factor, active power (kW), reactive power (kVAR), and total apparent power (kVA) in AC electrical systems.',
    keywords: ['power factor calculator', 'kw to kva calculator', 'apparent power calculator', 'reactive power kvar', 'ac power factor'],
    formulaDisplay: 'Power Factor (PF) = Real Power (kW) / Apparent Power (kVA) = cos(θ)',
    calculationStandard: 'IEEE Standard 1459 AC Electric Power Definitions',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'coulombs-law-calculator',
    title: 'Coulomb’s Law & Electrostatic Force',
    name: 'Coulomb’s Law Electric Charge & Force Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'circuits',
    badge: 'Physics Law',
    desc: 'Calculate electrostatic attraction or repulsion force between two point charges separated by a known distance.',
    keywords: ['coulombs law calculator', 'electrostatic force calculator', 'electric charge force', 'coulombs constant'],
    formulaDisplay: 'F = k_e × (|q₁ × q₂|) / r² (where k_e ≈ 8.98755 × 10⁹ N·m²/C²)',
    calculationStandard: 'NIST CODATA Recommended Constants for Electromagnetism',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'electricity-cost-calculator',
    title: 'Electricity Bill & Running Cost Calculator',
    name: 'Appliance & Household Electricity Bill Estimator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'energy-cost',
    badge: 'Energy Savings',
    desc: 'Calculate how much any appliance costs to run per hour, per day, per month, and per year based on your local kWh rate.',
    keywords: ['electricity cost calculator', 'appliance running cost', 'kwh cost calculator', 'power bill calculator', 'energy cost per month'],
    formulaDisplay: 'Cost = (Appliance Watts × Hours Used / 1,000) × Electricity Rate ($/kWh)',
    calculationStandard: 'US Energy Information Administration (EIA) Utility Billing Standards',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'appliance-energy-calculator',
    title: 'Appliance Energy Consumption Calculator',
    name: 'Appliance Power Usage & Carbon Footprint Estimator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'energy-cost',
    badge: 'Home Efficiency',
    desc: 'Compare electricity consumption across air conditioners, space heaters, refrigerators, computers, and water heaters.',
    keywords: ['appliance energy calculator', 'refrigerator power cost', 'space heater electricity cost', 'air conditioner power usage'],
    formulaDisplay: 'Monthly kWh = (Watts × Daily Hours × 30) / 1,000',
    calculationStandard: 'EPA Energy Star Appliance Test Procedures',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'lighting-energy-calculator',
    title: 'Lighting Energy & LED Savings Calculator',
    name: 'Lighting Energy Cost & LED Retrofit Savings Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'energy-cost',
    badge: 'LED Upgrade',
    desc: 'Calculate annual cost savings and payback time when upgrading incandescent or fluorescent bulbs to high-efficiency LEDs.',
    keywords: ['lighting energy calculator', 'led savings calculator', 'incandescent vs led cost', 'lighting electricity cost'],
    formulaDisplay: 'Annual Savings = [((Watts_Old - Watts_LED) × Hours/Day × 365) / 1,000] × Rate/kWh',
    calculationStandard: 'Department of Energy (DOE) Solid-State Lighting Standards',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'solar-battery-calculator',
    title: 'Solar Array & Battery Storage Sizer',
    name: 'Solar Panel System & Battery Backup Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'energy-cost',
    badge: 'Solar & Storage',
    desc: 'Calculate how many solar panels and how much battery storage (kWh / Ah) you need for off-grid or home backup power.',
    keywords: ['solar calculator', 'solar battery calculator', 'off grid solar sizer', 'battery storage capacity', 'solar panel requirements'],
    formulaDisplay: 'Battery Storage (Ah) = (Daily Wh × Days of Autonomy) / (Battery Voltage × Depth of Discharge)',
    calculationStandard: 'IEEE Standard 1013 Recommended Practice for Sizing Lead-Acid/Lithium Batteries',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'generator-sizing-calculator',
    title: 'Home Backup Generator Sizing Calculator',
    name: 'Emergency Generator Wattage & Load Sizer',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'energy-cost',
    badge: 'Backup Power',
    desc: 'Calculate starting (surge) watts and running (continuous) watts needed to power your critical household appliances during an outage.',
    keywords: ['generator sizing calculator', 'generator wattage calculator', 'home backup generator', 'starting vs running watts'],
    formulaDisplay: 'Generator Size (Watts) = Highest Starting Surge Watts + Total Running Watts of All Loads',
    calculationStandard: 'NFPA 110 Standard for Emergency and Standby Power Systems',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'capacitance-calculator',
    title: 'Capacitance & Capacitor Energy Solver',
    name: 'Capacitance, Stored Energy & Plate Area Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'electronics-conversions',
    badge: 'Energy Storage',
    desc: 'Calculate capacitance in farads/microfarads, parallel plate dimensions, and total energy stored in a charged capacitor.',
    keywords: ['capacitance calculator', 'capacitor energy calculator', 'parallel plate capacitance', 'microfarads to farads'],
    formulaDisplay: 'C = (ε_r × ε_0 × Area) / Distance ; Stored Energy E = ½ × C × V²',
    calculationStandard: 'Standard Electrostatic Permittivity Modeling',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'inductance-calculator',
    title: 'Inductance & Coil Inductor Calculator',
    name: 'Coil Inductance & Magnetic Energy Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'electronics-conversions',
    badge: 'Magnetics',
    desc: 'Calculate single-layer air core coil inductance in microhenries (µH) and energy stored in an inductor ($E = ½LI^2$).',
    keywords: ['inductance calculator', 'coil inductance', 'inductor energy calculator', 'microhenries calculator'],
    formulaDisplay: 'L (µH) = (d² × n²) / (18d + 40l) (Wheeler’s Formula for Air-Core Coils)',
    calculationStandard: 'Wheeler Standard Formula for RF Single-Layer Solenoids',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'resistor-color-code-calculator',
    title: 'Resistor Color Code Calculator',
    name: '4-Band, 5-Band & 6-Band Resistor Color Code Decoder',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'electronics-conversions',
    badge: 'Color Decoder',
    desc: 'Decode resistor color bands to find resistance in ohms, tolerance percentage, and temperature coefficient (ppm/K).',
    keywords: ['resistor color code calculator', '4 band resistor', '5 band resistor', 'resistor color bands', 'resistor decoder'],
    formulaDisplay: 'Resistance = (Band 1 & 2 digits) × 10^(Multiplier Band) ± Tolerance %',
    calculationStandard: 'IEC 60062 Resistor & Capacitor Marking Codes',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'smd-resistor-code-calculator',
    title: 'SMD Resistor Code Calculator',
    name: 'Surface Mount (SMD) Resistor Code Calculator',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'electronics-conversions',
    badge: 'SMD Decoder',
    desc: 'Calculate resistance values from 3-digit, 4-digit, and EIA-96 precision surface-mount resistor codes.',
    keywords: ['smd resistor code calculator', 'smd code decoder', 'eia-96 code calculator', 'surface mount resistor values'],
    formulaDisplay: '3-Digit: AB × 10^C ; 4-Digit: ABC × 10^D ; EIA-96: Value Code Lookup × 10^Multiplier Code',
    calculationStandard: 'EIA-96 Precision 1% SMD Resistor Marking Standard',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'amps-to-watts-converter',
    title: 'Amps to Watts / Volts / kVA Converter',
    name: 'Amps to Watts, Volts, and kVA Electrical Converter',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'electronics-conversions',
    badge: 'Unit Conversion',
    desc: 'Instantly convert Amperes (Current) to Watts (Power), Kilowatts (kW), and Volts across DC, 1-Phase AC, and 3-Phase AC.',
    keywords: ['amps to watts converter', 'watts to amps calculator', 'amps to kva', 'amps to volts converter', 'electrical conversion'],
    formulaDisplay: 'Watts = Amps × Volts × Power Factor (1-Phase AC) ; Watts = √3 × Amps × Volts × PF (3-Phase AC)',
    calculationStandard: 'IEEE Standard 141 Electrical Engineering Conversion Factors',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'horsepower-to-kw-converter',
    title: 'Horsepower (HP) to Kilowatts (kW) Converter',
    name: 'Motor Horsepower (HP) to Kilowatts (kW) Converter',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'electronics-conversions',
    badge: 'Motor Power',
    desc: 'Convert electric motor mechanical horsepower (HP) to electrical kilowatts (kW) and calculate full load amps.',
    keywords: ['horsepower to kw converter', 'hp to kw calculator', 'kw to hp converter', 'electric motor power converter'],
    formulaDisplay: '1 Mechanical HP = 0.74569987 kW ; kW = HP × 0.7457 ; HP = kW / 0.7457',
    calculationStandard: 'NEMA MG 1 Motors and Generators Standard',
    lastUpdated: '2026-10-01',
  },
  {
    id: 'dbm-to-watts-converter',
    title: 'dBm to Watts & Milliwatts Converter',
    name: 'dBm to Watts & RF Signal Power Converter',
    canonicalPath: '/electrical',
    category: 'electrical',
    subcategory: 'electronics-conversions',
    badge: 'Signal Power',
    desc: 'Convert decibel-milliwatts (dBm) to milliwatts (mW) and Watts (W) for audio, radio frequency (RF), and Wi-Fi signals.',
    keywords: ['dbm to watts converter', 'dbm to mw calculator', 'rf power converter', 'watts to dbm conversion'],
    formulaDisplay: 'Power (mW) = 10^(dBm / 10) ; Power (Watts) = 10^((dBm - 30) / 10)',
    calculationStandard: 'Telecommunications Industry Association (TIA) RF Power Metrology',
    lastUpdated: '2026-10-01',
  },
];

// AUTHORITATIVE STATISTICAL GETTERS (NEVER HARDCODE COUNTS)
export const TOTAL_CALCULATORS_COUNT = CANONICAL_TOOLS.length;
export const TOTAL_CATEGORIES_COUNT = CANONICAL_CATEGORIES.length;

export function getToolsByCategory(categoryId: string): CanonicalTool[] {
  return CANONICAL_TOOLS.filter((t) => t.category === categoryId);
}

export function getCategoryCount(categoryId: string): number {
  return getToolsByCategory(categoryId).length;
}

export function getToolByPath(path: string): CanonicalTool | undefined {
  const clean = path.replace(/\/$/, '');
  return CANONICAL_TOOLS.find((t) => t.canonicalPath === clean);
}

export function getAllCanonicalPaths(): string[] {
  const toolPaths = CANONICAL_TOOLS.map((t) => t.canonicalPath);
  const catPaths = CANONICAL_CATEGORIES.map((c) => c.path);
  return Array.from(new Set([...catPaths, ...toolPaths]));
}
