export interface BreedInfo {
  id: string;
  name: string;
  species: 'canine' | 'feline' | 'rabbit' | 'pocket' | 'avian';
  tier: 'small' | 'medium' | 'large' | 'giant';
  sizeCategory: string; // e.g. "Toy / Small (<20 lbs)"
  weightRange: string; // e.g. "3 - 6 lbs"
  expectedLifespan: string; // e.g. "14 - 17 Years"
  minYears: number;
  maxYears: number;
  medianYears: number;
  seniorAge: number; // age in calendar years pet enters senior stage
  agingRatePerYear: number; // human years per calendar year after age 2
  healthFocus: string;
  longevitySummary: string;
}

export const CANINE_BREEDS: BreedInfo[] = [
  // --- TOY & SMALL BREEDS (< 20 lbs) ---
  {
    id: 'chihuahua',
    name: 'Chihuahua',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '3 - 6 lbs',
    expectedLifespan: '15 - 18 Years',
    minYears: 15,
    maxYears: 18,
    medianYears: 16.5,
    seniorAge: 11,
    agingRatePerYear: 3.8,
    healthFocus: 'Periodontal disease, mitral valve disease, patellar luxation, hypoglycemia.',
    longevitySummary: 'One of the longest-lived canine breeds. Metabolic decline occurs much later than in larger dogs.',
  },
  {
    id: 'yorkshire-terrier',
    name: 'Yorkshire Terrier (Yorkie)',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '4 - 7 lbs',
    expectedLifespan: '14 - 16 Years',
    minYears: 14,
    maxYears: 16,
    medianYears: 15.0,
    seniorAge: 10.5,
    agingRatePerYear: 4.0,
    healthFocus: 'Dental tartar accumulation, tracheal collapse, portosystemic shunts.',
    longevitySummary: 'Excellent longevity with consistent preventive dental cleanings and harness walking to protect the trachea.',
  },
  {
    id: 'toy-poodle',
    name: 'Toy Poodle',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '4 - 9 lbs',
    expectedLifespan: '14 - 17 Years',
    minYears: 14,
    maxYears: 17,
    medianYears: 15.5,
    seniorAge: 11,
    agingRatePerYear: 3.9,
    healthFocus: 'Cataracts, progressive retinal atrophy (PRA), patellar luxation, Cushing’s disease.',
    longevitySummary: 'High cognitive vitality and cellular longevity; consistently ranks among the top 5 longest-living breeds.',
  },
  {
    id: 'pomeranian',
    name: 'Pomeranian',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '3 - 7 lbs',
    expectedLifespan: '13 - 16 Years',
    minYears: 13,
    maxYears: 16,
    medianYears: 14.5,
    seniorAge: 10.5,
    agingRatePerYear: 4.1,
    healthFocus: 'Tracheal collapse, alopecia X, dental disease, luxating patellas.',
    longevitySummary: 'Robust toy breed longevity when managed with weight control and dental hygiene.',
  },
  {
    id: 'shih-tzu',
    name: 'Shih Tzu',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '9 - 16 lbs',
    expectedLifespan: '13 - 16 Years',
    minYears: 13,
    maxYears: 16,
    medianYears: 14.5,
    seniorAge: 10,
    agingRatePerYear: 4.2,
    healthFocus: 'Brachycephalic ocular syndrome, dry eye (KCS), ear infections, intervertebral disc disease.',
    longevitySummary: 'Enjoys long adult and senior vitality; require eye protection and temperature regulation.',
  },
  {
    id: 'dachshund-mini',
    name: 'Dachshund (Miniature)',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '8 - 11 lbs',
    expectedLifespan: '14 - 17 Years',
    minYears: 14,
    maxYears: 17,
    medianYears: 15.5,
    seniorAge: 11,
    agingRatePerYear: 3.9,
    healthFocus: 'Intervertebral Disc Disease (IVDD), obesity, dental disease, cardiac murmurs.',
    longevitySummary: 'Very high biological lifespan potential; ramp usage and strict weight management prevent spinal compression.',
  },
  {
    id: 'dachshund-standard',
    name: 'Dachshund (Standard)',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '16 - 32 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.4,
    healthFocus: 'IVDD spinal protection, dental disease, heart disease.',
    longevitySummary: 'Long-lived hound with durable cellular resilience provided spinal mechanics are safeguarded.',
  },
  {
    id: 'jack-russell',
    name: 'Jack Russell / Parson Russell Terrier',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '13 - 17 lbs',
    expectedLifespan: '14 - 17 Years',
    minYears: 14,
    maxYears: 17,
    medianYears: 15.5,
    seniorAge: 11,
    agingRatePerYear: 3.9,
    healthFocus: 'Lens luxation, deafness, patellar luxation, arthritis.',
    longevitySummary: 'Exemplifies extraordinary functional vitality, often remaining physically nimble well past age 12.',
  },
  {
    id: 'maltese',
    name: 'Maltese',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '4 - 7 lbs',
    expectedLifespan: '14 - 16 Years',
    minYears: 14,
    maxYears: 16,
    medianYears: 15.0,
    seniorAge: 10.5,
    agingRatePerYear: 4.0,
    healthFocus: 'Dental disease, white shaker dog syndrome, mitral valve disease.',
    longevitySummary: 'Gentle toy companion with low cancer incidence and high longevity trajectory.',
  },
  {
    id: 'bichon-frise',
    name: 'Bichon Frise',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '12 - 18 lbs',
    expectedLifespan: '13 - 15 Years',
    minYears: 13,
    maxYears: 15,
    medianYears: 14.0,
    seniorAge: 10,
    agingRatePerYear: 4.3,
    healthFocus: 'Bladder stones (calcium oxalate), allergies, cataracts, dental disease.',
    longevitySummary: 'Enjoys a long lifespan; regular urinalysis and urinary hydration preserve renal health.',
  },
  {
    id: 'havanese',
    name: 'Havanese',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '7 - 13 lbs',
    expectedLifespan: '14 - 16 Years',
    minYears: 14,
    maxYears: 16,
    medianYears: 15.0,
    seniorAge: 10.5,
    agingRatePerYear: 4.0,
    healthFocus: 'Heart murmurs, patellar luxation, eye cataracts, liver shunts.',
    longevitySummary: 'Sturdy small breed with slow cellular senescence and high cognitive resilience.',
  },
  {
    id: 'papillon',
    name: 'Papillon',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '5 - 10 lbs',
    expectedLifespan: '14 - 16 Years',
    minYears: 14,
    maxYears: 16,
    medianYears: 15.0,
    seniorAge: 11,
    agingRatePerYear: 3.9,
    healthFocus: 'Dental disease, patellar luxation, fontanelle closure, PRA.',
    longevitySummary: 'Ranked near the top for intelligence and biological lifespan among toy dogs.',
  },
  {
    id: 'cavalier',
    name: 'Cavalier King Charles Spaniel',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '13 - 18 lbs',
    expectedLifespan: '9 - 12 Years',
    minYears: 9,
    maxYears: 12,
    medianYears: 10.5,
    seniorAge: 8,
    agingRatePerYear: 5.5,
    healthFocus: 'Myxomatous Mitral Valve Disease (MMVD), syringomyelia, episodic falling.',
    longevitySummary: 'Shorter expected lifespan than typical toy breeds due to hereditary cardiovascular MMVD genetics.',
  },
  {
    id: 'boston-terrier',
    name: 'Boston Terrier',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '12 - 25 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 9,
    agingRatePerYear: 4.6,
    healthFocus: 'Brachycephalic obstructive airway syndrome (BOAS), corneal ulcers, allergies.',
    longevitySummary: 'Good longevity for a flat-faced breed; benefits greatly from keeping lean and avoiding heat stress.',
  },
  {
    id: 'pug',
    name: 'Pug',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '14 - 18 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.4,
    healthFocus: 'BOAS airway compromise, pug dog encephalitis (PDE), corneal ulcers, obesity.',
    longevitySummary: 'Can live to 14+ when weight is carefully controlled to prevent airway constriction.',
  },
  {
    id: 'miniature-pinscher',
    name: 'Miniature Pinscher (Min Pin)',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '8 - 10 lbs',
    expectedLifespan: '13 - 16 Years',
    minYears: 13,
    maxYears: 16,
    medianYears: 14.5,
    seniorAge: 10,
    agingRatePerYear: 4.1,
    healthFocus: 'Legg-Calve-Perthes disease, patellar luxation, progressive retinal atrophy.',
    longevitySummary: 'High-energy terrier-like vitality with long juvenile-to-adult health spans.',
  },
  {
    id: 'italian-greyhound',
    name: 'Italian Greyhound',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '7 - 14 lbs',
    expectedLifespan: '13 - 15 Years',
    minYears: 13,
    maxYears: 15,
    medianYears: 14.0,
    seniorAge: 10,
    agingRatePerYear: 4.3,
    healthFocus: 'Periodontal disease, bone fragility (leg fractures), autoimmune disorders.',
    longevitySummary: 'Naturally lean with healthy heart function; requires strict periodontal and cold-weather protection.',
  },
  {
    id: 'westie',
    name: 'West Highland White Terrier (Westie)',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '15 - 20 lbs',
    expectedLifespan: '13 - 15 Years',
    minYears: 13,
    maxYears: 15,
    medianYears: 14.0,
    seniorAge: 10,
    agingRatePerYear: 4.3,
    healthFocus: 'Atopic dermatitis, pulmonary fibrosis (Westie lung), Addison’s disease.',
    longevitySummary: 'Durable Scottish terrier stock with solid middle and senior stage health.',
  },
  {
    id: 'mixed-small',
    name: 'Mixed Breed / Mutt (Small <20 lbs)',
    species: 'canine',
    tier: 'small',
    sizeCategory: 'Toy / Small (<20 lbs)',
    weightRange: '5 - 20 lbs',
    expectedLifespan: '14 - 17 Years',
    minYears: 14,
    maxYears: 17,
    medianYears: 15.5,
    seniorAge: 11,
    agingRatePerYear: 3.9,
    healthFocus: 'Dental tartar, patellar stability, general geriatric wellness.',
    longevitySummary: 'Benefits from heterosis (hybrid vigor), avoiding concentrated breed-specific recessive diseases.',
  },

  // --- MEDIUM BREEDS (21 - 50 lbs) ---
  {
    id: 'french-bulldog',
    name: 'French Bulldog',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '20 - 28 lbs',
    expectedLifespan: '9 - 11 Years',
    minYears: 9,
    maxYears: 11,
    medianYears: 10.0,
    seniorAge: 7.5,
    agingRatePerYear: 5.6,
    healthFocus: 'BOAS airway stenosis, hemivertebrae / IVDD, allergic dermatitis, ear otitis.',
    longevitySummary: 'Significant brachycephalic physiological strain accelerates biological senescence compared to other medium dogs.',
  },
  {
    id: 'english-bulldog',
    name: 'English Bulldog',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '40 - 50 lbs',
    expectedLifespan: '8 - 10 Years',
    minYears: 8,
    maxYears: 10,
    medianYears: 9.0,
    seniorAge: 6.5,
    agingRatePerYear: 6.2,
    healthFocus: 'Severe BOAS, hip dysplasia, cardiac ventricular defects, skin fold dermatitis.',
    longevitySummary: 'Lowest average life expectancy among medium dogs; enters senior physiological state by age 6.5.',
  },
  {
    id: 'beagle',
    name: 'Beagle',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '20 - 30 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.6,
    healthFocus: 'Obesity, intervertebral disc disease, hypothyroidism, epilepsy.',
    longevitySummary: 'Hardy scent hound with reliable longevity; weight control is the single biggest factor for reaching 15+.',
  },
  {
    id: 'border-collie',
    name: 'Border Collie',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '30 - 45 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.6,
    healthFocus: 'Collie eye anomaly (CEA), epilepsy, hip dysplasia, multi-drug resistance (MDR1).',
    longevitySummary: 'Remarkable physical stamina and lean metabolism sustain slow biological aging into double digits.',
  },
  {
    id: 'australian-shepherd',
    name: 'Australian Shepherd (Aussie)',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '40 - 55 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.7,
    healthFocus: 'MDR1 mutation, cataracts, hemangiosarcoma, hip dysplasia.',
    longevitySummary: 'High energy and natural working physiology support an active, resilient senior phase.',
  },
  {
    id: 'australian-cattle-dog',
    name: 'Australian Cattle Dog (Blue Heeler)',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '35 - 50 lbs',
    expectedLifespan: '13 - 16 Years',
    minYears: 13,
    maxYears: 16,
    medianYears: 14.5,
    seniorAge: 10,
    agingRatePerYear: 4.2,
    healthFocus: 'Progressive retinal atrophy, congenital deafness, hip and elbow dysplasia.',
    longevitySummary: 'Legendary toughness; holds historical longevity records (Bluey lived to 29 years, 5 months).',
  },
  {
    id: 'cocker-spaniel',
    name: 'Cocker Spaniel (American / English)',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '25 - 35 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 9,
    agingRatePerYear: 4.8,
    healthFocus: 'Chronic ear otitis externa, cataracts, glaucoma, autoimmune hemolytic anemia (AIHA).',
    longevitySummary: 'Moderate aging velocity; diligent ear canal care and ocular exams preserve quality of life.',
  },
  {
    id: 'pembroke-corgi',
    name: 'Pembroke Welsh Corgi',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '24 - 30 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 9,
    agingRatePerYear: 4.8,
    healthFocus: 'Degenerative Myelopathy (DM), IVDD, hip dysplasia, obesity.',
    longevitySummary: 'Chondrodystrophic physique requires back-care and strict calorie control to avoid early mobility loss.',
  },
  {
    id: 'shiba-inu',
    name: 'Shiba Inu',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '17 - 23 lbs',
    expectedLifespan: '13 - 16 Years',
    minYears: 13,
    maxYears: 16,
    medianYears: 14.5,
    seniorAge: 10,
    agingRatePerYear: 4.2,
    healthFocus: 'Allergies / atopy, glaucoma, patellar luxation, hip dysplasia.',
    longevitySummary: 'Ancient basal lineage with very low cancer incidence and exceptional longevity in clean environments.',
  },
  {
    id: 'basset-hound',
    name: 'Basset Hound',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '40 - 65 lbs',
    expectedLifespan: '10 - 12 Years',
    minYears: 10,
    maxYears: 12,
    medianYears: 11.0,
    seniorAge: 8,
    agingRatePerYear: 5.2,
    healthFocus: 'Gastric dilatation-volvulus (bloat), IVDD, ear infections, glaucoma, joint arthritis.',
    longevitySummary: 'Heavily boned frame puts significant stress on joints; enters senior care around age 8.',
  },
  {
    id: 'whippet',
    name: 'Whippet',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '25 - 40 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.6,
    healthFocus: 'Cardiac murmurs, skin tears (thin skin), dental health, hypothermia.',
    longevitySummary: 'Naturally lean sight hound with low cardiac load and strong cellular health.',
  },
  {
    id: 'brittany-spaniel',
    name: 'Brittany Spaniel',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '30 - 40 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 9,
    agingRatePerYear: 4.8,
    healthFocus: 'Hip dysplasia, epilepsy, hypothyroidism, eye cataracts.',
    longevitySummary: 'Energetic sporting dog that maintains muscle mass and stamina well into mature years.',
  },
  {
    id: 'staffordshire-bull-terrier',
    name: 'Staffordshire Bull Terrier (Staffy)',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '24 - 38 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 9,
    agingRatePerYear: 4.8,
    healthFocus: 'Skin allergies, cataracts, L-2-hydroxyglutaric aciduria (L2HGA), joint wear.',
    longevitySummary: 'Muscular, durable companion with typical medium-breed aging progression.',
  },
  {
    id: 'mixed-medium',
    name: 'Mixed Breed / Mutt (Medium 21-50 lbs)',
    species: 'canine',
    tier: 'medium',
    sizeCategory: 'Medium (21-50 lbs)',
    weightRange: '25 - 50 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.6,
    healthFocus: 'Joint care, dental health, routine senior lab panels.',
    longevitySummary: 'Strong genetic variance yields above-average organ longevity compared to purebred peers.',
  },

  // --- LARGE BREEDS (51 - 90 lbs) ---
  {
    id: 'labrador-retriever',
    name: 'Labrador Retriever',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '55 - 80 lbs',
    expectedLifespan: '11 - 13 Years',
    minYears: 11,
    maxYears: 13,
    medianYears: 12.0,
    seniorAge: 7.5,
    agingRatePerYear: 5.3,
    healthFocus: 'Obesity (POMC gene deletion), hip/elbow dysplasia, arthritis, cruciate ligament tears, cancer.',
    longevitySummary: 'Studies show Labs kept at an ideal lean body condition live an average of 1.8 years longer.',
  },
  {
    id: 'golden-retriever',
    name: 'Golden Retriever',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '55 - 75 lbs',
    expectedLifespan: '10 - 12 Years',
    minYears: 10,
    maxYears: 12,
    medianYears: 11.0,
    seniorAge: 7.5,
    agingRatePerYear: 5.5,
    healthFocus: 'Hemangiosarcoma, lymphoma, hip/elbow dysplasia, subaortic stenosis, pigmentary uveitis.',
    longevitySummary: 'High oncological predisposition (~60% cancer mortality in US lines) pulls the senior frontier earlier.',
  },
  {
    id: 'german-shepherd',
    name: 'German Shepherd Dog (GSD)',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '50 - 90 lbs',
    expectedLifespan: '9 - 11 Years',
    minYears: 9,
    maxYears: 11,
    medianYears: 10.0,
    seniorAge: 7,
    agingRatePerYear: 5.8,
    healthFocus: 'Degenerative Myelopathy, hip/elbow dysplasia, bloat (GDV), hemangiosarcoma, pancreatic insufficiency.',
    longevitySummary: 'Large skeletal load and neurological DM susceptibility demand early senior joint and mobility support.',
  },
  {
    id: 'boxer',
    name: 'Boxer',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '55 - 70 lbs',
    expectedLifespan: '9 - 11 Years',
    minYears: 9,
    maxYears: 11,
    medianYears: 10.0,
    seniorAge: 7,
    agingRatePerYear: 5.8,
    healthFocus: 'Arrhythmogenic Right Ventricular Cardiomyopathy (Boxer ARVC), mast cell tumors, lymphoma, BOAS.',
    longevitySummary: 'Cardiac arrhythmias and cancer vulnerability make proactive semi-annual vet screenings critical by age 6.',
  },
  {
    id: 'standard-poodle',
    name: 'Standard Poodle',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '45 - 70 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 8,
    agingRatePerYear: 4.9,
    healthFocus: 'Gastric dilatation-volvulus (bloat), Addison’s disease, sebaceous adenitis, hip dysplasia.',
    longevitySummary: 'One of the longest-living large dog breeds; benefits from a deep-chested gastropexy preventive procedure.',
  },
  {
    id: 'siberian-husky',
    name: 'Siberian Husky',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '35 - 60 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 8.5,
    agingRatePerYear: 4.9,
    healthFocus: 'Cataracts, corneal dystrophy, zinc-responsive dermatosis, hip dysplasia.',
    longevitySummary: 'Primitive arctic metabolism and lean frame support higher longevity than typical large working breeds.',
  },
  {
    id: 'rottweiler',
    name: 'Rottweiler',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '80 - 135 lbs',
    expectedLifespan: '8 - 10 Years',
    minYears: 8,
    maxYears: 10,
    medianYears: 9.0,
    seniorAge: 6.5,
    agingRatePerYear: 6.4,
    healthFocus: 'Osteosarcoma (bone cancer), subaortic stenosis, hip/elbow dysplasia, bloat.',
    longevitySummary: 'Heavy bone mass and high cancer prevalence accelerate biological senescence after age 6.',
  },
  {
    id: 'doberman-pinscher',
    name: 'Doberman Pinscher',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '60 - 90 lbs',
    expectedLifespan: '9 - 11 Years',
    minYears: 9,
    maxYears: 11,
    medianYears: 10.0,
    seniorAge: 7,
    agingRatePerYear: 5.9,
    healthFocus: 'Dilated Cardiomyopathy (DCM in ~58% of population), von Willebrand disease, cervical spondylomyelopathy (Wobbler).',
    longevitySummary: 'Cardiac Holter monitoring and echocardiograms starting at age 4 are vital for longevity.',
  },
  {
    id: 'bernese-mountain-dog',
    name: 'Bernese Mountain Dog',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '70 - 115 lbs',
    expectedLifespan: '6 - 8 Years',
    minYears: 6,
    maxYears: 8,
    medianYears: 7.0,
    seniorAge: 5.5,
    agingRatePerYear: 8.2,
    healthFocus: 'Malignant histiocytosis (histiocytic sarcoma), hip/elbow dysplasia, bloat.',
    longevitySummary: 'Tragically short biological timeline due to aggressive histiocytic cancer genetics; enters senior care by age 5.',
  },
  {
    id: 'weimaraner',
    name: 'Weimaraner',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '55 - 85 lbs',
    expectedLifespan: '10 - 13 Years',
    minYears: 10,
    maxYears: 13,
    medianYears: 11.5,
    seniorAge: 7.5,
    agingRatePerYear: 5.4,
    healthFocus: 'Gastric dilatation-volvulus (bloat), hip dysplasia, factor XI deficiency, hyperuricosuria.',
    longevitySummary: 'Deep-chested athletic dog; proactive preventive gastropexy and joint support prolong life.',
  },
  {
    id: 'vizsla',
    name: 'Vizsla (Hungarian Pointer)',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '45 - 65 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 8.5,
    agingRatePerYear: 4.9,
    healthFocus: 'Epilepsy, lymphosarcoma, hip dysplasia, sebaceous adenitis.',
    longevitySummary: 'Lean, agile pointing breed with superior endurance and solid late-life mobility.',
  },
  {
    id: 'belgian-malinois',
    name: 'Belgian Malinois',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '40 - 80 lbs',
    expectedLifespan: '12 - 14 Years',
    minYears: 12,
    maxYears: 14,
    medianYears: 13.0,
    seniorAge: 8.5,
    agingRatePerYear: 4.9,
    healthFocus: 'Hip/elbow dysplasia, progressive retinal atrophy, cataracts.',
    longevitySummary: 'High-drive working breed with exceptional athletic stamina and slow physiological decay.',
  },
  {
    id: 'akita',
    name: 'Akita (American / Japanese)',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '70 - 130 lbs',
    expectedLifespan: '10 - 12 Years',
    minYears: 10,
    maxYears: 12,
    medianYears: 11.0,
    seniorAge: 7,
    agingRatePerYear: 5.6,
    healthFocus: 'Bloat, hip dysplasia, progressive retinal atrophy, autoimmune thyroiditis.',
    longevitySummary: 'Dignified spitz breed; heavy frame necessitates weight vigilance and joint supplements.',
  },
  {
    id: 'greyhound',
    name: 'Greyhound',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '60 - 75 lbs',
    expectedLifespan: '10 - 13 Years',
    minYears: 10,
    maxYears: 13,
    medianYears: 11.5,
    seniorAge: 7.5,
    agingRatePerYear: 5.3,
    healthFocus: 'Osteosarcoma, bloat, dental disease, sensitivity to anesthesia.',
    longevitySummary: 'Athletic heart with low resting heart rate; watch for osteosarcoma screening around age 7-8.',
  },
  {
    id: 'mixed-large',
    name: 'Mixed Breed / Mutt (Large 51-90 lbs)',
    species: 'canine',
    tier: 'large',
    sizeCategory: 'Large (51-90 lbs)',
    weightRange: '51 - 90 lbs',
    expectedLifespan: '10 - 13 Years',
    minYears: 10,
    maxYears: 13,
    medianYears: 11.5,
    seniorAge: 7.5,
    agingRatePerYear: 5.3,
    healthFocus: 'Hip stability, arthritis management, cardiac health.',
    longevitySummary: 'Higher genetic diversity provides resilience against specific cancer clusters found in purebred lines.',
  },

  // --- GIANT BREEDS (> 90 lbs) ---
  {
    id: 'great-dane',
    name: 'Great Dane',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '110 - 175 lbs',
    expectedLifespan: '6 - 8 Years',
    minYears: 6,
    maxYears: 8,
    medianYears: 7.0,
    seniorAge: 5,
    agingRatePerYear: 8.5,
    healthFocus: 'Gastric dilatation-volvulus (#1 cause of death), dilated cardiomyopathy, osteosarcoma, wobbler syndrome.',
    longevitySummary: 'Rapid puppy cellular growth correlates with early oxidative aging; senior care starts as early as age 5.',
  },
  {
    id: 'english-mastiff',
    name: 'English Mastiff',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '120 - 230 lbs',
    expectedLifespan: '6 - 8 Years',
    minYears: 6,
    maxYears: 8,
    medianYears: 7.0,
    seniorAge: 5,
    agingRatePerYear: 8.5,
    healthFocus: 'Massive joint loading, osteosarcoma, cystinuria, bloat, dilated cardiomyopathy.',
    longevitySummary: 'Enormous body mass places tremendous mechanical wear on cardiac output and joint cartilage.',
  },
  {
    id: 'saint-bernard',
    name: 'Saint Bernard',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '120 - 180 lbs',
    expectedLifespan: '7 - 9 Years',
    minYears: 7,
    maxYears: 9,
    medianYears: 8.0,
    seniorAge: 5.5,
    agingRatePerYear: 7.8,
    healthFocus: 'Bloat, hip and elbow dysplasia, osteosarcoma, cardiomyopathy, entropion/ectropion.',
    longevitySummary: 'Alpine giant requiring strict temperature monitoring and early senior arthritic support.',
  },
  {
    id: 'newfoundland',
    name: 'Newfoundland',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '100 - 150 lbs',
    expectedLifespan: '8 - 10 Years',
    minYears: 8,
    maxYears: 10,
    medianYears: 9.0,
    seniorAge: 6,
    agingRatePerYear: 7.2,
    healthFocus: 'Subaortic stenosis (SAS), cystinuria, hip/elbow dysplasia, bloat.',
    longevitySummary: 'Relatively good lifespan among giant breeds when cardiac SAS clearance is established.',
  },
  {
    id: 'irish-wolfhound',
    name: 'Irish Wolfhound',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '105 - 180 lbs',
    expectedLifespan: '6 - 8 Years',
    minYears: 6,
    maxYears: 8,
    medianYears: 7.0,
    seniorAge: 5,
    agingRatePerYear: 8.5,
    healthFocus: 'Dilated cardiomyopathy, osteosarcoma, bloat (GDV), pneumonia.',
    longevitySummary: 'Tallest dog breed with rapid skeletal development; senior considerations apply from age 5.',
  },
  {
    id: 'cane-corso',
    name: 'Cane Corso (Italian Mastiff)',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '90 - 110 lbs',
    expectedLifespan: '8 - 10 Years',
    minYears: 8,
    maxYears: 10,
    medianYears: 9.0,
    seniorAge: 6,
    agingRatePerYear: 7.2,
    healthFocus: 'Hip dysplasia, bloat, idiopathic epilepsy, eyelid abnormalities (cherry eye).',
    longevitySummary: 'Athletic mastiff with solid muscular frame; requires joint preservation protocols.',
  },
  {
    id: 'bullmastiff',
    name: 'Bullmastiff',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '100 - 130 lbs',
    expectedLifespan: '7 - 9 Years',
    minYears: 7,
    maxYears: 9,
    medianYears: 8.0,
    seniorAge: 5.5,
    agingRatePerYear: 7.8,
    healthFocus: 'Bloat, lymphoma, osteosarcoma, subaortic stenosis, hip dysplasia.',
    longevitySummary: 'High cancer and cardiac incidence pull median life expectancy down to ~8 years.',
  },
  {
    id: 'great-pyrenees',
    name: 'Great Pyrenees',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '85 - 120 lbs',
    expectedLifespan: '9 - 11 Years',
    minYears: 9,
    maxYears: 11,
    medianYears: 10.0,
    seniorAge: 6.5,
    agingRatePerYear: 6.8,
    healthFocus: 'Osteosarcoma, bloat, patellar luxation, entropion, hip dysplasia.',
    longevitySummary: 'Remarkable calm livestock-guardian demeanor gives this giant slightly higher longevity than other mastiff types.',
  },
  {
    id: 'mixed-giant',
    name: 'Mixed Breed / Mutt (Giant >90 lbs)',
    species: 'canine',
    tier: 'giant',
    sizeCategory: 'Giant (>90 lbs)',
    weightRange: '90 - 150 lbs',
    expectedLifespan: '7 - 10 Years',
    minYears: 7,
    maxYears: 10,
    medianYears: 8.5,
    seniorAge: 6,
    agingRatePerYear: 7.4,
    healthFocus: 'Joint care, heart monitoring, bloat prevention.',
    longevitySummary: 'Giant-size cellular mass requires joint and cardiac vigilance starting in mid-life.',
  },
];

export const FELINE_BREEDS: BreedInfo[] = [
  {
    id: 'domestic-shorthair',
    name: 'Domestic Shorthair / Moggy',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '7 - 12 lbs',
    expectedLifespan: '14 - 18 Years',
    minYears: 14,
    maxYears: 18,
    medianYears: 16.0,
    seniorAge: 11,
    agingRatePerYear: 4.0,
    healthFocus: 'Chronic kidney disease (CKD), dental resorption, hyperthyroidism, diabetes.',
    longevitySummary: 'Genetic diversity and indoor living grant outstanding longevity, frequently reaching 18-20 years.',
  },
  {
    id: 'siamese',
    name: 'Siamese',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '6 - 10 lbs',
    expectedLifespan: '15 - 20 Years',
    minYears: 15,
    maxYears: 20,
    medianYears: 17.5,
    seniorAge: 12,
    agingRatePerYear: 3.7,
    healthFocus: 'Amyloidosis, feline asthma, progressive retinal atrophy, dental disease.',
    longevitySummary: 'Consistently documented as one of the longest-living domestic cat breeds.',
  },
  {
    id: 'maine-coon',
    name: 'Maine Coon',
    species: 'feline',
    tier: 'large',
    sizeCategory: 'Large Feline',
    weightRange: '11 - 20 lbs',
    expectedLifespan: '11 - 14 Years',
    minYears: 11,
    maxYears: 14,
    medianYears: 12.5,
    seniorAge: 9,
    agingRatePerYear: 4.8,
    healthFocus: 'Hypertrophic cardiomyopathy (HCM - MYBPC3 gene), hip dysplasia, spinal muscular atrophy.',
    longevitySummary: 'Large skeletal mass and HCM risk give Maine Coons a slightly shorter lifespan than smaller cats.',
  },
  {
    id: 'persian',
    name: 'Persian',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '7 - 12 lbs',
    expectedLifespan: '12 - 16 Years',
    minYears: 12,
    maxYears: 16,
    medianYears: 14.0,
    seniorAge: 10,
    agingRatePerYear: 4.3,
    healthFocus: 'Polycystic Kidney Disease (PKD1), brachycephalic airway, eye epiphora, dental crowding.',
    longevitySummary: 'Modern genetic screening for PKD has substantially improved senior Persian longevity.',
  },
  {
    id: 'ragdoll',
    name: 'Ragdoll',
    species: 'feline',
    tier: 'large',
    sizeCategory: 'Large Feline',
    weightRange: '10 - 18 lbs',
    expectedLifespan: '13 - 17 Years',
    minYears: 13,
    maxYears: 17,
    medianYears: 15.0,
    seniorAge: 10.5,
    agingRatePerYear: 4.1,
    healthFocus: 'Hypertrophic cardiomyopathy (HCM), bladder stones, obesity.',
    longevitySummary: 'Gentle, low-stress indoor disposition protects against stress-related metabolic disease.',
  },
  {
    id: 'british-shorthair',
    name: 'British Shorthair',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '9 - 16 lbs',
    expectedLifespan: '13 - 17 Years',
    minYears: 13,
    maxYears: 17,
    medianYears: 15.0,
    seniorAge: 10.5,
    agingRatePerYear: 4.1,
    healthFocus: 'Hypertrophic cardiomyopathy, obesity, arthritis in later years.',
    longevitySummary: 'Placid temperament and robust constitution yield solid, steady aging.',
  },
  {
    id: 'bengal',
    name: 'Bengal',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '8 - 15 lbs',
    expectedLifespan: '13 - 16 Years',
    minYears: 13,
    maxYears: 16,
    medianYears: 14.5,
    seniorAge: 10,
    agingRatePerYear: 4.2,
    healthFocus: 'Progressive retinal atrophy (PRA-b), erythrocyte pyruvate kinase deficiency (PK-Def), HCM.',
    longevitySummary: 'Active hybrid heritage preserves lean muscle and cardiovascular endurance well into senior years.',
  },
  {
    id: 'sphynx',
    name: 'Sphynx',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '6 - 12 lbs',
    expectedLifespan: '12 - 15 Years',
    minYears: 12,
    maxYears: 15,
    medianYears: 13.5,
    seniorAge: 9.5,
    agingRatePerYear: 4.5,
    healthFocus: 'HCM, skin urticaria pigmentosa, ear wax buildup, hypothermia vulnerability.',
    longevitySummary: 'Higher basal metabolic rate due to heat loss; regular cardiac ultrasounds are critical.',
  },
  {
    id: 'russian-blue',
    name: 'Russian Blue',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '7 - 12 lbs',
    expectedLifespan: '15 - 18 Years',
    minYears: 15,
    maxYears: 18,
    medianYears: 16.5,
    seniorAge: 11,
    agingRatePerYear: 3.8,
    healthFocus: 'Bladder stones, obesity, periodontal hygiene.',
    longevitySummary: 'Naturally hardy breed with very low rates of inherited congenital diseases.',
  },
  {
    id: 'scottish-fold',
    name: 'Scottish Fold',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '6 - 11 lbs',
    expectedLifespan: '11 - 14 Years',
    minYears: 11,
    maxYears: 14,
    medianYears: 12.5,
    seniorAge: 9,
    agingRatePerYear: 4.8,
    healthFocus: 'Osteochondrodysplasia (painful progressive joint & cartilage disease), PKD, cardiomyopathy.',
    longevitySummary: 'The fold cartilage gene causes generalized cartilage defects that require lifelong arthritis management.',
  },
  {
    id: 'burmese',
    name: 'Burmese',
    species: 'feline',
    tier: 'medium',
    sizeCategory: 'Standard Feline',
    weightRange: '8 - 12 lbs',
    expectedLifespan: '15 - 18 Years',
    minYears: 15,
    maxYears: 18,
    medianYears: 16.5,
    seniorAge: 11.5,
    agingRatePerYear: 3.7,
    healthFocus: 'Diabetes mellitus, hypokalemia, cranial facial defect in certain lines.',
    longevitySummary: 'Celebrated longevity record; closely related to Siamese with prolonged healthy senior stages.',
  },
  {
    id: 'norwegian-forest-cat',
    name: 'Norwegian Forest Cat',
    species: 'feline',
    tier: 'large',
    sizeCategory: 'Large Feline',
    weightRange: '10 - 18 lbs',
    expectedLifespan: '12 - 16 Years',
    minYears: 12,
    maxYears: 16,
    medianYears: 14.0,
    seniorAge: 10,
    agingRatePerYear: 4.3,
    healthFocus: 'Glycogen Storage Disease Type IV (GSD IV), HCM, hip dysplasia.',
    longevitySummary: 'Sturdy Scandinavian natural breed with excellent constitutional hardiness.',
  },
];

export const OTHER_PET_BREEDS: BreedInfo[] = [
  {
    id: 'holland-lop',
    name: 'Holland Lop Rabbit',
    species: 'rabbit',
    tier: 'small',
    sizeCategory: 'Dwarf Lagomorph',
    weightRange: '2 - 4 lbs',
    expectedLifespan: '8 - 12 Years',
    minYears: 8,
    maxYears: 12,
    medianYears: 10.0,
    seniorAge: 6,
    agingRatePerYear: 7.0,
    healthFocus: 'Dental malocclusion, GI stasis, ear otitis interna, uterine adenocarcinoma.',
    longevitySummary: 'Enjoys long companionship when spayed/neutered and fed a 90% hay diet.',
  },
  {
    id: 'netherland-dwarf',
    name: 'Netherland Dwarf Rabbit',
    species: 'rabbit',
    tier: 'small',
    sizeCategory: 'Miniature Lagomorph',
    weightRange: '1.5 - 2.5 lbs',
    expectedLifespan: '10 - 12 Years',
    minYears: 10,
    maxYears: 12,
    medianYears: 11.0,
    seniorAge: 6.5,
    agingRatePerYear: 6.5,
    healthFocus: 'Dental spurs, brachycephalic epiphora, digestive stasis.',
    longevitySummary: 'One of the longest-living rabbit varieties due to diminutive body size.',
  },
  {
    id: 'flemish-giant',
    name: 'Flemish Giant Rabbit',
    species: 'rabbit',
    tier: 'large',
    sizeCategory: 'Giant Lagomorph',
    weightRange: '13 - 22 lbs',
    expectedLifespan: '5 - 7 Years',
    minYears: 5,
    maxYears: 7,
    medianYears: 6.0,
    seniorAge: 4,
    agingRatePerYear: 11.0,
    healthFocus: 'Pododermatitis (sore hocks), cardiac failure, joint arthritis.',
    longevitySummary: 'Similar to giant dogs, large rabbit breeds age significantly faster than dwarfs.',
  },
  {
    id: 'syrian-hamster',
    name: 'Syrian / Golden Hamster',
    species: 'pocket',
    tier: 'small',
    sizeCategory: 'Pocket Rodent',
    weightRange: '4 - 7 oz',
    expectedLifespan: '2 - 3 Years',
    minYears: 2,
    maxYears: 3,
    medianYears: 2.5,
    seniorAge: 1.5,
    agingRatePerYear: 30.0,
    healthFocus: 'Wet tail (proliferative ileitis), heart failure / cardiomyopathy, tumors.',
    longevitySummary: 'Very high metabolic pace; 1 calendar year equates to approximately 30-35 human biological years.',
  },
  {
    id: 'guinea-pig',
    name: 'Guinea Pig (Cavy)',
    species: 'pocket',
    tier: 'medium',
    sizeCategory: 'Pocket Rodent',
    weightRange: '1.5 - 2.6 lbs',
    expectedLifespan: '5 - 8 Years',
    minYears: 5,
    maxYears: 8,
    medianYears: 6.5,
    seniorAge: 4,
    agingRatePerYear: 12.0,
    healthFocus: 'Vitamin C deficiency (scurvy), dental malocclusion, urinary stones, ovarian cysts.',
    longevitySummary: 'Longer lived than hamsters; requires mandatory dietary vitamin C and timothy hay.',
  },
  {
    id: 'cockatiel',
    name: 'Cockatiel',
    species: 'avian',
    tier: 'small',
    sizeCategory: 'Small Psittacine',
    weightRange: '75 - 125 g',
    expectedLifespan: '15 - 20 Years',
    minYears: 15,
    maxYears: 20,
    medianYears: 17.5,
    seniorAge: 12,
    agingRatePerYear: 4.0,
    healthFocus: 'Egg binding in females, respiratory aerosol toxicity (Teflon/PTFE), atherosclerosis.',
    longevitySummary: 'Exceptional avian longevity; protected avian telomeres resist cellular aging.',
  },
  {
    id: 'budgie',
    name: 'Budgerigar (Parakeet)',
    species: 'avian',
    tier: 'small',
    sizeCategory: 'Small Psittacine',
    weightRange: '30 - 40 g',
    expectedLifespan: '7 - 12 Years',
    minYears: 7,
    maxYears: 12,
    medianYears: 9.5,
    seniorAge: 6.5,
    agingRatePerYear: 7.5,
    healthFocus: 'Tumors (renal / reproductive), obesity from all-seed diets, iodine deficiency goiter.',
    longevitySummary: 'Can live to 12+ on a varied pellet and fresh sprout/vegetable diet.',
  },
  {
    id: 'african-grey',
    name: 'African Grey Parrot',
    species: 'avian',
    tier: 'large',
    sizeCategory: 'Large Psittacine',
    weightRange: '400 - 550 g',
    expectedLifespan: '40 - 60 Years',
    minYears: 40,
    maxYears: 60,
    medianYears: 50.0,
    seniorAge: 35,
    agingRatePerYear: 1.5,
    healthFocus: 'Hypocalcemia syndrome, feather picking / psychological stress, aspergillosis.',
    longevitySummary: 'True lifetime companion; outlives many human caretakers with slow, steady aging.',
  },
];

export function getBreedsForSpecies(species: 'canine' | 'feline' | 'rabbit' | 'pocket' | 'avian'): BreedInfo[] {
  if (species === 'canine') return CANINE_BREEDS;
  if (species === 'feline') return FELINE_BREEDS;
  return OTHER_PET_BREEDS.filter((b) => b.species === species);
}

export function findBreedByName(name: string): BreedInfo | undefined {
  const all = [...CANINE_BREEDS, ...FELINE_BREEDS, ...OTHER_PET_BREEDS];
  const query = name.toLowerCase().trim();
  return all.find((b) => b.name.toLowerCase() === query || b.id === query || b.name.toLowerCase().includes(query));
}
