import { TimeToolDefinition } from './types';

export const CORE_TIME_TOOLS: TimeToolDefinition[] = [
  {
    slug: 'time-calculator',
    canonicalPath: '/time-date/time-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Time Calculator',
    shortTitle: 'Time Calculator',
    metaTitle: 'Time Calculator | Add, Subtract & Compute Time Durations',
    metaDescription: 'Free online time calculator to add, subtract, and calculate total hours, minutes, and seconds between timestamps with decimal precision.',
    keywords: ['time calculator', 'add time', 'subtract time', 'hours and minutes calculator', 'time math'],
    searchIntent: 'calculator',
    calculatorType: 'time-duration',
    formula: 'Duration = End Time - Start Time - Break Deduction',
    variableDefinitions: [
      { symbol: 'T_start', label: 'Start Time', description: 'Starting clock timestamp (HH:MM:SS)' },
      { symbol: 'T_end', label: 'End Time', description: 'Ending clock timestamp (HH:MM:SS)' },
      { symbol: 'T_break', label: 'Break Deduction', description: 'Unpaid intermission or rest period in minutes' },
    ],
    workedExample: {
      scenario: 'Calculating total shift duration from 08:30 AM to 05:15 PM with a 45-minute lunch break.',
      steps: [
        'Convert 08:30 AM to 24-hour time: 08:30:00 (510 minutes).',
        'Convert 05:15 PM to 24-hour time: 17:15:00 (1035 minutes).',
        'Calculate gross elapsed time: 1035 - 510 = 525 minutes (8 hours 45 minutes).',
        'Deduct 45-minute lunch break: 525 - 45 = 480 minutes.',
        'Convert to hours and decimal: 8 hours 00 minutes = 8.00 decimal hours.',
      ],
      conclusion: 'Net work time is exactly 8 hours 0 minutes (8.00 hours).',
    },
    assumptions: ['Default clock calculations assume standard 24-hour day rollover for overnight shifts.'],
    relatedSlugs: ['time-duration-calculator', 'add-time-calculator', 'time-card-calculator', 'work-time-calculator'],
    faqs: [
      {
        question: 'Does this calculator support shifts that cross midnight?',
        acceptedAnswer: 'Yes. If the end time is numerically earlier than the start time, the algorithm automatically adds 24 hours to accommodate overnight shifts.',
      } as unknown as { question: string; answer: string },
    ],
  },
  {
    slug: 'time-duration-calculator',
    canonicalPath: '/time-date/time-duration-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Time Duration Calculator',
    shortTitle: 'Time Duration',
    metaTitle: 'Time Duration Calculator | Calculate Elapsed Time Between Two Times',
    metaDescription: 'Calculate the exact elapsed time duration in hours, minutes, seconds, and decimal format between any two clock times.',
    keywords: ['time duration calculator', 'elapsed time calculator', 'time between two times', 'hours between times'],
    searchIntent: 'calculator',
    calculatorType: 'time-duration',
    formula: '\\Delta t = t_2 - t_1',
    variableDefinitions: [
      { symbol: 't_1', label: 'Start Time', description: 'Initial time marker' },
      { symbol: 't_2', label: 'End Time', description: 'Final time marker' },
    ],
    workedExample: {
      scenario: 'Determining the elapsed duration of a conference call starting at 10:15 AM and ending at 11:42 AM.',
      steps: [
        'Initial time = 10 hours, 15 minutes (615 minutes from midnight).',
        'Final time = 11 hours, 42 minutes (702 minutes from midnight).',
        'Elapsed duration = 702 - 615 = 87 minutes.',
        'Decompose into hours and minutes: 87 / 60 = 1 hour with 27 minutes remaining.',
      ],
      conclusion: 'The total call duration was 1 hour 27 minutes (1.45 hours).',
    },
    relatedSlugs: ['time-calculator', 'hours-calculator', 'minutes-calculator', 'average-time-calculator'],
    faqs: [
      {
        question: 'How do I convert elapsed time to decimal hours for billing?',
        answer: 'Divide the minute portion by 60 and add it to the hours (e.g. 1 hour 27 minutes = 1 + 27/60 = 1.45 hours).',
      },
    ],
  },
  {
    slug: 'add-time-calculator',
    canonicalPath: '/time-date/add-time-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Add Time Calculator',
    shortTitle: 'Add Time',
    metaTitle: 'Add Time Calculator | Sum Hours, Minutes & Seconds',
    metaDescription: 'Easily add together multiple hours, minutes, and seconds durations to calculate cumulative totals and time sheet sums.',
    keywords: ['add time calculator', 'time addition', 'sum hours and minutes', 'add timestamps'],
    searchIntent: 'calculator',
    calculatorType: 'add-subtract-time',
    formula: 'T_{total} = \\sum_{i=1}^n (H_i \\times 3600 + M_i \\times 60 + S_i)',
    variableDefinitions: [
      { symbol: 'H_i', label: 'Hours', description: 'Hour component of each time entry' },
      { symbol: 'M_i', label: 'Minutes', description: 'Minute component of each time entry' },
      { symbol: 'S_i', label: 'Seconds', description: 'Second component of each time entry' },
    ],
    workedExample: {
      scenario: 'Adding two video clip durations: 2h 45m 30s and 1h 25m 45s.',
      steps: [
        'Sum seconds: 30s + 45s = 75s (1 minute, 15 seconds).',
        'Sum minutes with carry: 45m + 25m + 1m = 71m (1 hour, 11 minutes).',
        'Sum hours with carry: 2h + 1h + 1h = 4 hours.',
      ],
      conclusion: 'Total combined video length is 4 hours 11 minutes 15 seconds.',
    },
    relatedSlugs: ['subtract-time-calculator', 'time-calculator', 'hours-calculator', 'time-card-calculator'],
    faqs: [
      {
        question: 'Can I add more than two time entries?',
        answer: 'Yes, you can dynamically add multiple time intervals to sum up complex playlists, sprint blocks, or project timesheets.',
      },
    ],
  },
  {
    slug: 'subtract-time-calculator',
    canonicalPath: '/time-date/subtract-time-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Subtract Time Calculator',
    shortTitle: 'Subtract Time',
    metaTitle: 'Subtract Time Calculator | Deduct Hours, Minutes & Seconds',
    metaDescription: 'Subtract time durations, deduct break periods from work shifts, and calculate remaining time balances accurately.',
    keywords: ['subtract time calculator', 'deduct hours', 'time subtraction', 'time difference calculator'],
    searchIntent: 'calculator',
    calculatorType: 'add-subtract-time',
    formula: 'T_{net} = T_{base} - T_{deduction}',
    variableDefinitions: [
      { symbol: 'T_{base}', label: 'Base Duration', description: 'Initial time interval' },
      { symbol: 'T_{deduction}', label: 'Deducted Duration', description: 'Time interval being subtracted' },
    ],
    workedExample: {
      scenario: 'Deducting a 50-minute workout from a 3-hour available schedule.',
      steps: [
        'Base duration: 3 hours 00 minutes.',
        'Borrow 1 hour (60 minutes): 2 hours 60 minutes.',
        'Subtract minutes: 60 - 50 = 10 minutes.',
      ],
      conclusion: 'Remaining schedule balance is 2 hours 10 minutes.',
    },
    relatedSlugs: ['add-time-calculator', 'time-calculator', 'time-card-calculator'],
    faqs: [
      {
        question: 'What happens if the subtracted time is greater than the base time?',
        answer: 'The calculator outputs a negative duration formatted with a minus sign (e.g. -01:30:00).',
      },
    ],
  },
  {
    slug: 'hours-calculator',
    canonicalPath: '/time-date/hours-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Hours Calculator',
    shortTitle: 'Hours Calculator',
    metaTitle: 'Hours Calculator | Calculate Total Elapsed & Decimal Hours',
    metaDescription: 'Fast online hours calculator for work hours, elapsed time, overtime tracking, and decimal hours conversion.',
    keywords: ['hours calculator', 'calculate hours', 'total hours', 'decimal hours calculator'],
    searchIntent: 'calculator',
    calculatorType: 'time-duration',
    formula: 'H_{decimal} = \\text{Hours} + \\frac{\\text{Minutes}}{60} + \\frac{\\text{Seconds}}{3600}',
    relatedSlugs: ['minutes-calculator', 'seconds-calculator', 'time-card-calculator', 'work-time-calculator'],
    faqs: [
      {
        question: 'How do you calculate 7 hours and 30 minutes in decimal?',
        answer: 'Divide 30 by 60 = 0.5. Add 7 to get 7.50 decimal hours.',
      },
    ],
  },
  {
    slug: 'minutes-calculator',
    canonicalPath: '/time-date/minutes-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Minutes Calculator',
    shortTitle: 'Minutes Calculator',
    metaTitle: 'Minutes Calculator | Calculate Minutes Between Times',
    metaDescription: 'Calculate total elapsed minutes, add/subtract minute intervals, and convert minute blocks to standard clock time.',
    keywords: ['minutes calculator', 'total minutes', 'minutes between times', 'minute counter'],
    searchIntent: 'calculator',
    calculatorType: 'time-duration',
    formula: 'M_{total} = (H \\times 60) + M + (S / 60)',
    relatedSlugs: ['hours-calculator', 'seconds-calculator', 'time-calculator'],
    faqs: [
      {
        question: 'How many minutes are in 8.25 hours?',
        answer: '8.25 multiplied by 60 equals exactly 495 minutes.',
      },
    ],
  },
  {
    slug: 'seconds-calculator',
    canonicalPath: '/time-date/seconds-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Seconds Calculator',
    shortTitle: 'Seconds Calculator',
    metaTitle: 'Seconds Calculator | Precision Time Calculations in Seconds',
    metaDescription: 'High precision seconds calculator to measure elapsed seconds, compute millisecond intervals, and sum high-frequency time metrics.',
    keywords: ['seconds calculator', 'total seconds', 'calculate seconds', 'time in seconds'],
    searchIntent: 'calculator',
    calculatorType: 'time-duration',
    formula: 'S_{total} = (H \\times 3600) + (M \\times 60) + S',
    relatedSlugs: ['minutes-calculator', 'hours-calculator', 'time-calculator'],
    faqs: [
      {
        question: 'How many seconds are in one standard 24-hour day?',
        answer: 'One standard solar day contains 24 x 60 x 60 = 86,400 seconds.',
      },
    ],
  },
  {
    slug: 'average-time-calculator',
    canonicalPath: '/time-date/average-time-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Average Time Calculator',
    shortTitle: 'Average Time',
    metaTitle: 'Average Time Calculator | Compute Mean & Average Pace',
    metaDescription: 'Compute the exact mathematical average of multiple time values, race lap times, or daily task durations.',
    keywords: ['average time calculator', 'mean time calculator', 'average lap time', 'calculate average time'],
    searchIntent: 'calculator',
    calculatorType: 'average-time',
    formula: 'T_{avg} = \\frac{\\sum_{i=1}^n T_i}{n}',
    variableDefinitions: [
      { symbol: 'T_i', label: 'Time Value', description: 'Each individual duration in seconds' },
      { symbol: 'n', label: 'Count', description: 'Total number of sample time entries' },
    ],
    workedExample: {
      scenario: 'Finding the average time of 3 running splits: 05:20, 05:45, and 05:10.',
      steps: [
        'Convert to seconds: 320s, 345s, 310s.',
        'Sum total seconds: 320 + 345 + 310 = 975 seconds.',
        'Divide by count (3): 975 / 3 = 325 seconds.',
        'Convert back to minutes and seconds: 325 / 60 = 5 minutes 25 seconds.',
      ],
      conclusion: 'The average split time is 05:25.',
    },
    relatedSlugs: ['time-calculator', 'hours-calculator', 'time-duration-calculator'],
    faqs: [
      {
        question: 'How does average time calculation handle different units?',
        answer: 'All input values are normalized to base seconds before computing the arithmetic mean, ensuring zero rounding distortion.',
      },
    ],
  },
  {
    slug: 'work-time-calculator',
    canonicalPath: '/time-date/work-time-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Work Time Calculator',
    shortTitle: 'Work Time',
    metaTitle: 'Work Time Calculator | Calculate Shift Hours, Breaks & Gross Pay',
    metaDescription: 'Calculate net work shift hours, unpaid break deductions, regular versus overtime hours, and estimated gross earnings.',
    keywords: ['work time calculator', 'shift hours calculator', 'work hours and pay', 'overtime calculator'],
    searchIntent: 'calculator',
    calculatorType: 'work-hours',
    formula: '\\text{Gross Pay} = (H_{reg} \\times R) + (H_{OT} \\times R \\times 1.5)',
    variableDefinitions: [
      { symbol: 'H_{reg}', label: 'Regular Hours', description: 'Hours up to standard threshold (e.g. 8h/day or 40h/week)' },
      { symbol: 'H_{OT}', label: 'Overtime Hours', description: 'Hours exceeding regular threshold' },
      { symbol: 'R', label: 'Base Hourly Rate', description: 'Hourly pay wage in currency units' },
    ],
    workedExample: {
      scenario: 'A shift from 08:00 to 18:30 (10.5h gross) with a 30m break at $25.00/hr base with 1.5x OT after 8h.',
      steps: [
        'Net hours = 10.5 - 0.5 = 10.0 hours.',
        'Regular hours = 8.0 hours. Overtime hours = 2.0 hours.',
        'Regular pay = 8.0 * $25.00 = $200.00.',
        'Overtime pay = 2.0 * ($25.00 * 1.5) = $75.00.',
        'Total gross earnings = $200.00 + $75.00 = $275.00.',
      ],
      conclusion: 'Total earnings for the shift are $275.00 across 10 net working hours.',
    },
    relatedSlugs: ['time-card-calculator', 'hours-calculator', 'business-day-calculator'],
    faqs: [
      {
        question: 'How are lunch breaks calculated in work shifts?',
        answer: 'Unpaid breaks are deducted directly from the gross elapsed duration between clock-in and clock-out.',
      },
    ],
  },
  {
    slug: 'time-card-calculator',
    canonicalPath: '/time-date/time-card-calculator',
    category: 'core',
    subcategoryTitle: 'Core Time Calculators',
    name: 'Time Card Calculator',
    shortTitle: 'Time Card',
    metaTitle: 'Time Card Calculator | Weekly Timesheet & Payroll Hours Calculator',
    metaDescription: 'Free online weekly time card calculator. Enter clock in and clock out times for Monday through Sunday to compute weekly payroll hours.',
    keywords: ['time card calculator', 'weekly timesheet calculator', 'payroll hours calculator', 'punch card calculator'],
    searchIntent: 'calculator',
    calculatorType: 'time-card',
    formula: 'H_{week} = \\sum_{d=1}^7 (\\text{ClockOut}_d - \\text{ClockIn}_d - \\text{Break}_d)',
    relatedSlugs: ['work-time-calculator', 'hours-calculator', 'time-calculator'],
    faqs: [
      {
        question: 'Does this weekly timecard support decimal export for payroll software?',
        answer: 'Yes, results provide both HH:MM notation and decimal hours ready for payroll processing.',
      },
    ],
  },
  {
    slug: 'business-day-calculator',
    canonicalPath: '/time-date/business-day-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Business Day Calculator',
    shortTitle: 'Business Days',
    metaTitle: 'Business Day Calculator | Count Working Days Between Dates',
    metaDescription: 'Calculate working days and business days between two dates. Exclude Saturdays, Sundays, and public bank holidays.',
    keywords: ['business day calculator', 'working days calculator', 'business days between dates', 'workday counter'],
    searchIntent: 'calculator',
    calculatorType: 'business-days',
    formula: 'D_{bus} = D_{total} - D_{weekend} - D_{holidays}',
    variableDefinitions: [
      { symbol: 'D_{total}', label: 'Calendar Days', description: 'Total elapsed calendar span' },
      { symbol: 'D_{weekend}', label: 'Weekend Days', description: 'Saturdays and Sundays in interval' },
      { symbol: 'D_{holidays}', label: 'Public Holidays', description: 'Recognized non-working holidays falling on weekdays' },
    ],
    workedExample: {
      scenario: 'Calculating business days between Monday, Oct 5 and Friday, Oct 16 with 1 federal holiday.',
      steps: [
        'Total calendar span = 12 calendar days.',
        'Weekend days (Saturday & Sunday) = 2 days.',
        'Federal public holiday on weekday = 1 day.',
        'Net business days = 12 - 2 - 1 = 9 business days.',
      ],
      conclusion: 'There are 9 working business days in this span.',
    },
    relatedSlugs: ['date-difference-calculator', 'days-between-dates-calculator', 'date-calculator'],
    faqs: [
      {
        question: 'Can I customize non-standard workweeks (e.g. 4-day or 6-day weeks)?',
        answer: 'Yes, you can toggle active workdays individually from Monday through Sunday.',
      },
    ],
  },
  {
    slug: 'date-calculator',
    canonicalPath: '/time-date/date-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Date Calculator',
    shortTitle: 'Date Calculator',
    metaTitle: 'Date Calculator | Add or Subtract Days, Weeks, Months & Years',
    metaDescription: 'Comprehensive date calculator to add or subtract days, weeks, months, and years from any calendar date with leap year accuracy.',
    keywords: ['date calculator', 'add days to date', 'subtract days from date', 'future date calculator', 'calendar math'],
    searchIntent: 'calculator',
    calculatorType: 'date-diff',
    formula: 'D_{target} = D_{start} \\pm (Y \\cdot 365.2425 + M \\cdot 30.44 + W \\cdot 7 + D)',
    relatedSlugs: ['date-difference-calculator', 'days-between-dates-calculator', 'days-from-today-calculator'],
    faqs: [
      {
        question: 'How are end-of-month dates handled when adding months?',
        answer: 'Standard calendar pinning applies: adding 1 month to January 31 lands on February 28 (or Feb 29 in leap years).',
      },
    ],
  },
  {
    slug: 'date-difference-calculator',
    canonicalPath: '/time-date/date-difference-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Date Difference Calculator',
    shortTitle: 'Date Difference',
    metaTitle: 'Date Difference Calculator | Exact Time Span Between Two Dates',
    metaDescription: 'Calculate the exact difference between two dates in years, months, weeks, days, hours, and minutes with inclusive/exclusive counting.',
    keywords: ['date difference calculator', 'difference between two dates', 'how many days between dates', 'date span'],
    searchIntent: 'calculator',
    calculatorType: 'date-diff',
    formula: '\\Delta D = D_2 - D_1',
    relatedSlugs: ['days-between-dates-calculator', 'weeks-between-dates-calculator', 'years-between-dates-calculator', 'business-day-calculator'],
    faqs: [
      {
        question: 'What is the difference between inclusive and exclusive counting?',
        answer: 'Exclusive counting measures elapsed span (Monday to Tuesday = 1 day). Inclusive counting counts both end dates (Monday through Tuesday = 2 days).',
      },
    ],
  },
  {
    slug: 'days-between-dates-calculator',
    canonicalPath: '/time-date/days-between-dates-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Days Between Dates Calculator',
    shortTitle: 'Days Between Dates',
    metaTitle: 'Days Between Dates Calculator | Count Total Days Between Two Dates',
    metaDescription: 'Count the exact number of calendar days between any two dates. Supports inclusive and exclusive date counting.',
    keywords: ['days between dates', 'days between dates calculator', 'number of days between dates', 'day counter between dates'],
    searchIntent: 'calculator',
    calculatorType: 'date-diff',
    relatedSlugs: ['date-difference-calculator', 'weeks-between-dates-calculator', 'day-counter'],
    faqs: [
      {
        question: 'Does this calculator account for leap years?',
        answer: 'Yes, the Gregorian leap year algorithm (366 days in leap years) is fully integrated.',
      },
    ],
  },
  {
    slug: 'weeks-between-dates-calculator',
    canonicalPath: '/time-date/weeks-between-dates-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Weeks Between Dates Calculator',
    shortTitle: 'Weeks Between Dates',
    metaTitle: 'Weeks Between Dates Calculator | Count Elapsed Weeks and Days',
    metaDescription: 'Calculate the total number of full weeks, remaining days, and decimal weeks between two calendar dates.',
    keywords: ['weeks between dates', 'weeks between dates calculator', 'how many weeks between dates', 'week counter'],
    searchIntent: 'calculator',
    calculatorType: 'date-diff',
    relatedSlugs: ['days-between-dates-calculator', 'years-between-dates-calculator', 'date-difference-calculator'],
    faqs: [
      {
        question: 'How do you calculate weeks between two dates?',
        answer: 'Find total days between the dates and divide by 7 (e.g. 25 days = 3 weeks and 4 days, or 3.57 weeks).',
      },
    ],
  },
  {
    slug: 'years-between-dates-calculator',
    canonicalPath: '/time-date/years-between-dates-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Years Between Dates Calculator',
    shortTitle: 'Years Between Dates',
    metaTitle: 'Years Between Dates Calculator | Calculate Exact Years & Months',
    metaDescription: 'Compute the exact number of calendar years, months, and days between historical or future dates.',
    keywords: ['years between dates', 'years between two dates calculator', 'how many years between dates'],
    searchIntent: 'calculator',
    calculatorType: 'date-diff',
    relatedSlugs: ['date-difference-calculator', 'age-calculator', 'months-from-today-calculator'],
    faqs: [
      {
        question: 'How does the calculator handle leap day anniversaries (Feb 29)?',
        answer: 'On non-leap years, Feb 29 anniversaries evaluate to Feb 28 (or March 1 depending on jurisdiction rules).',
      },
    ],
  },
  {
    slug: 'day-counter',
    canonicalPath: '/time-date/day-counter',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Day Counter',
    shortTitle: 'Day Counter',
    metaTitle: 'Day Counter | Fast Online Day Counting & Interval Calculator',
    metaDescription: 'Count days from today, calculate elapsed calendar days, and compute countdown intervals in one click.',
    keywords: ['day counter', 'count days', 'day counting tool', 'calendar day counter'],
    searchIntent: 'calculator',
    calculatorType: 'date-diff',
    relatedSlugs: ['days-between-dates-calculator', 'days-from-today-calculator', 'days-since-date-calculator'],
    faqs: [
      {
        question: 'Can I use the Day Counter to track streaks or habits?',
        answer: 'Yes, enter your starting milestone date to see the exact number of days elapsed to date.',
      },
    ],
  },
  {
    slug: 'day-of-week-calculator',
    canonicalPath: '/time-date/day-of-week-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Day of Week Calculator',
    shortTitle: 'Day of Week',
    metaTitle: 'Day of Week Calculator | Find the Day of the Week for Any Date',
    metaDescription: 'Find what day of the week (Monday, Tuesday, etc.) any past or future date falls on using Zeller congruence arithmetic.',
    keywords: ['day of week calculator', 'what day was it', 'find day of week', 'day of week for date'],
    searchIntent: 'calculator',
    calculatorType: 'day-of-week',
    formula: 'h = (q + \\lfloor\\frac{13(m+1)}{5}\\rfloor + K + \\lfloor\\frac{K}{4}\\rfloor + \\lfloor\\frac{J}{4}\\rfloor - 2J) \\bmod 7',
    relatedSlugs: ['date-calculator', 'leap-year-calculator', 'age-calculator'],
    faqs: [
      {
        question: 'What mathematical algorithm is used to find the day of the week?',
        answer: 'Zeller’s Congruence algorithm determines the day of the week for any Gregorian calendar date.',
      },
    ],
  },
  {
    slug: 'days-from-today-calculator',
    canonicalPath: '/time-date/days-from-today-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Days From Today Calculator',
    shortTitle: 'Days From Today',
    metaTitle: 'Days From Today Calculator | Find the Future Date N Days Ahead',
    metaDescription: 'Find what date it will be 30, 60, 90, or N days from today. Fast dynamic calendar calculations updated in real time.',
    keywords: ['days from today', 'days from today calculator', 'what date will it be in days', 'future date from today'],
    searchIntent: 'calculator',
    calculatorType: 'days-from-today',
    relatedSlugs: ['days-since-date-calculator', 'weeks-from-today-calculator', 'months-from-today-calculator'],
    faqs: [
      {
        question: 'What date will it be 90 days from today?',
        answer: 'The calculator automatically adds 90 calendar days to today’s local date, displaying the exact target weekday and month.',
      },
    ],
  },
  {
    slug: 'days-since-date-calculator',
    canonicalPath: '/time-date/days-since-date-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Days Since Date Calculator',
    shortTitle: 'Days Since Date',
    metaTitle: 'Days Since Date Calculator | Count Days Passed Since Past Date',
    metaDescription: 'Count how many days have passed since a specific historical date, birthdate, anniversary, or event.',
    keywords: ['days since date', 'how many days since', 'days since calculator', 'days elapsed since'],
    searchIntent: 'calculator',
    calculatorType: 'days-since',
    relatedSlugs: ['days-from-today-calculator', 'age-calculator', 'day-counter'],
    faqs: [
      {
        question: 'How do you calculate days passed since a specific date?',
        answer: 'Subtract the past date timestamp from current midnight timestamp and divide by 86,400,000 ms.',
      },
    ],
  },
  {
    slug: 'months-from-today-calculator',
    canonicalPath: '/time-date/months-from-today-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Months From Today Calculator',
    shortTitle: 'Months From Today',
    metaTitle: 'Months From Today Calculator | Target Date in N Months',
    metaDescription: 'Calculate what calendar date it will be 1, 3, 6, 9, or 12 months from today with automatic month boundary pinning.',
    keywords: ['months from today', 'months from today calculator', 'date in 6 months', 'date in 3 months'],
    searchIntent: 'calculator',
    calculatorType: 'days-from-today',
    relatedSlugs: ['days-from-today-calculator', 'weeks-from-today-calculator', 'date-calculator'],
    faqs: [
      {
        question: 'What happens if today is August 31 and I calculate 1 month from today?',
        answer: 'September has only 30 days, so 1 month from August 31 pins safely to September 30.',
      },
    ],
  },
  {
    slug: 'weeks-from-today-calculator',
    canonicalPath: '/time-date/weeks-from-today-calculator',
    category: 'date-calculators',
    subcategoryTitle: 'Date & Calendar Calculators',
    name: 'Weeks From Today Calculator',
    shortTitle: 'Weeks From Today',
    metaTitle: 'Weeks From Today Calculator | Target Date in N Weeks',
    metaDescription: 'Determine the exact date N weeks from today. Ideal for pregnancy timelines, sprint planning, and project roadmaps.',
    keywords: ['weeks from today', 'weeks from today calculator', 'date in 2 weeks', 'date in 4 weeks'],
    searchIntent: 'calculator',
    calculatorType: 'days-from-today',
    relatedSlugs: ['days-from-today-calculator', 'months-from-today-calculator', 'business-day-calculator'],
    faqs: [
      {
        question: 'What day of the week will it be N weeks from today?',
        answer: 'Because a week is exactly 7 days, adding any whole number of weeks always lands on the exact same day of the week as today.',
      },
    ],
  },
  {
    slug: 'age-calculator',
    canonicalPath: '/time-date/age-calculator',
    category: 'age-calculators',
    subcategoryTitle: 'Age & Chronological Calculators',
    name: 'Age Calculator',
    shortTitle: 'Age Calculator',
    metaTitle: 'Age Calculator | Calculate Exact Age in Years, Months & Days',
    metaDescription: 'Calculate your exact chronological age today or on any specific date. Provides age in years, months, days, total hours, and birthday countdown.',
    keywords: ['age calculator', 'how old am i', 'exact age calculator', 'chronological age', 'birthday age calculator'],
    searchIntent: 'calculator',
    calculatorType: 'age',
    formula: '\\text{Age} = \\text{Target Date} - \\text{Date of Birth}',
    variableDefinitions: [
      { symbol: 'DOB', label: 'Date of Birth', description: 'Birth calendar date' },
      { symbol: 'T_{target}', label: 'Target Date', description: 'Date to measure age on (default is today)' },
    ],
    workedExample: {
      scenario: 'Calculating exact age on October 15, 2026 for someone born July 22, 1995.',
      steps: [
        'Calculate completed years: 2026 - 1995 = 31 years.',
        'Calculate completed months past birthday: July to October = 3 months.',
        'Calculate remaining days: 22nd to 15th borrows previous month days (September has 30 days) -> 30 - 22 + 15 = 23 days.',
        'Adjust completed months: 3 - 1 = 2 months.',
      ],
      conclusion: 'Exact age is 31 years, 2 months, and 23 days.',
    },
    relatedSlugs: ['age-difference-calculator', 'how-old-was-i-calculator', 'date-difference-calculator'],
    faqs: [
      {
        question: 'Does this age calculator account for leap years lived?',
        answer: 'Yes, every leap year (366 days) in your lifetime is factored into total day, hour, and second calculations.',
      },
    ],
  },
  {
    slug: 'age-difference-calculator',
    canonicalPath: '/time-date/age-difference-calculator',
    category: 'age-calculators',
    subcategoryTitle: 'Age & Chronological Calculators',
    name: 'Age Difference Calculator',
    shortTitle: 'Age Difference',
    metaTitle: 'Age Difference Calculator | Compare Age Gap Between Two People',
    metaDescription: 'Calculate the exact age difference and age gap between two individuals in years, months, days, and total hours.',
    keywords: ['age difference calculator', 'age gap calculator', 'compare ages', 'difference in age between two people'],
    searchIntent: 'calculator',
    calculatorType: 'age-diff',
    formula: '\\Delta \\text{Age} = |\\text{DOB}_1 - \\text{DOB}_2|',
    relatedSlugs: ['age-calculator', 'date-difference-calculator', 'how-old-was-i-calculator'],
    faqs: [
      {
        question: 'How does the age gap calculator work?',
        answer: 'It computes the exact calendar difference between the two birthdates, identifying who is older and the exact interval span.',
      },
    ],
  },
  {
    slug: 'how-old-was-i-calculator',
    canonicalPath: '/time-date/how-old-was-i-calculator',
    category: 'age-calculators',
    subcategoryTitle: 'Age & Chronological Calculators',
    name: 'How Old Was I Calculator',
    shortTitle: 'How Old Was I',
    metaTitle: 'How Old Was I Calculator | Find Your Age on Any Past Date',
    metaDescription: 'Find out exactly how old you were on a historical date, graduation, wedding, historical event, or past milestone.',
    keywords: ['how old was i calculator', 'how old was i on this date', 'past age calculator', 'age on specific date'],
    searchIntent: 'calculator',
    calculatorType: 'how-old-was-i',
    relatedSlugs: ['age-calculator', 'age-difference-calculator', 'date-difference-calculator'],
    faqs: [
      {
        question: 'Can I find out how old I will be on a future date?',
        answer: 'Yes, you can select any past or future date to compute your exact chronological age on that day.',
      },
    ],
  },
  {
    slug: 'leap-year-calculator',
    canonicalPath: '/time-date/leap-year-calculator',
    category: 'calendar',
    subcategoryTitle: 'Calendar & Planetary Reference',
    name: 'Leap Year Calculator',
    shortTitle: 'Leap Year Calculator',
    metaTitle: 'Leap Year Calculator | Is It a Leap Year? Check Any Year',
    metaDescription: 'Check if any year is a leap year under the Gregorian calendar rules. Discover upcoming leap years and historical leap year explanations.',
    keywords: ['leap year calculator', 'is it a leap year', 'next leap year', 'gregorian leap year rule'],
    searchIntent: 'calculator',
    calculatorType: 'leap-year',
    formula: '\\text{LeapYear}(Y) = (Y \\bmod 4 = 0 \\land Y \\bmod 100 \\neq 0) \\lor (Y \\bmod 400 = 0)',
    variableDefinitions: [
      { symbol: 'Y', label: 'Year', description: 'Gregorian calendar year to evaluate' },
    ],
    workedExample: {
      scenario: 'Testing whether the year 2000 and 2100 are leap years.',
      steps: [
        'Test 2000: Divisible by 4 (yes), divisible by 100 (yes), divisible by 400 (yes). -> 2000 IS a leap year (366 days).',
        'Test 2100: Divisible by 4 (yes), divisible by 100 (yes), divisible by 400 (no: 2100 / 400 = 5.25). -> 2100 is NOT a leap year (365 days).',
      ],
      conclusion: 'Century years must be divisible by 400 to qualify as leap years.',
    },
    relatedSlugs: ['date-calculator', 'day-of-week-calculator', 'date-difference-calculator'],
    faqs: [
      {
        question: 'Why do century years have special leap year rules?',
        answer: 'A solar year is approximately 365.2422 days. Adding a leap day every 4 years adds 0.25 days/year (slight overcorrection). Skipping century years unless divisible by 400 keeps the calendar aligned with Earth’s orbit to within 1 day every 3,236 years.',
      },
    ],
  },
  {
    slug: 'month-calculator',
    canonicalPath: '/time-date/month-calculator',
    category: 'calendar',
    subcategoryTitle: 'Calendar & Planetary Reference',
    name: 'Month Calculator',
    shortTitle: 'Month Calculator',
    metaTitle: 'Month Calculator | Days & Working Hours in Any Month',
    metaDescription: 'Calculate the total number of calendar days, weekend days, working days, and standard work hours in any month of any year.',
    keywords: ['month calculator', 'days in month', 'working days in month', 'month calendar stats'],
    searchIntent: 'calculator',
    calculatorType: 'month-calc',
    relatedSlugs: ['business-day-calculator', 'date-calculator', 'leap-year-calculator'],
    faqs: [
      {
        question: 'How many work hours are in a typical month?',
        answer: 'A standard month has between 20 and 23 working days, translating to 160 to 184 work hours at 8 hours per day.',
      },
    ],
  },
];
