import { TimeToolDefinition } from './types';

export const CONVERSION_TIME_TOOLS: TimeToolDefinition[] = [
  {
    slug: 'time-converter',
    canonicalPath: '/time-date/time-converter',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Time Converter',
    shortTitle: 'Time Converter',
    metaTitle: 'Time Converter | Convert Between 12 Units of Time Instantly',
    metaDescription: 'Universal time unit converter. Convert instantly between nanoseconds, microseconds, milliseconds, seconds, minutes, hours, days, weeks, months, years, decades, and centuries.',
    keywords: ['time converter', 'convert time', 'time unit converter', 'seconds to hours', 'minutes to days'],
    searchIntent: 'converter',
    calculatorType: 'unit-converter',
    formula: '\\text{Value}_{to} = \\text{Value}_{from} \\times \\frac{\\text{Factor}_{from}}{\\text{Factor}_{to}}',
    variableDefinitions: [
      { symbol: 'V_{from}', label: 'Input Value', description: 'Quantity in original time unit' },
      { symbol: 'F_{from}', label: 'Source Factor', description: 'Conversion factor to base seconds' },
      { symbol: 'F_{to}', label: 'Target Factor', description: 'Conversion factor from base seconds to target unit' },
    ],
    workedExample: {
      scenario: 'Converting 2.5 days to minutes.',
      steps: [
        'Identify source factor: 1 day = 86,400 seconds.',
        'Multiply input by factor: 2.5 x 86,400 = 216,000 seconds.',
        'Identify target factor: 1 minute = 60 seconds.',
        'Divide seconds by target factor: 216,000 / 60 = 3,600 minutes.',
      ],
      conclusion: '2.5 days is equivalent to exactly 3,600 minutes.',
    },
    referenceTable: {
      title: 'Time Unit Conversion Reference (Base: 1 Hour)',
      headers: ['Unit', 'Equivalent in 1 Hour', 'Scientific Notation'],
      rows: [
        ['Nanoseconds', '3,600,000,000,000 ns', '3.6 × 10¹² ns'],
        ['Microseconds', '3,600,000,000 μs', '3.6 × 10⁹ μs'],
        ['Milliseconds', '3,600,000 ms', '3.6 × 10⁶ ms'],
        ['Seconds', '3,600 s', '3.6 × 10³ s'],
        ['Minutes', '60 min', '6.0 × 10¹ min'],
        ['Days', '0.041667 days', '4.167 × 10⁻² days'],
        ['Weeks', '0.005952 weeks', '5.952 × 10⁻³ weeks'],
        ['Months (avg)', '0.001369 months', '1.369 × 10⁻³ months'],
        ['Years (avg)', '0.000114 years', '1.141 × 10⁻⁴ years'],
      ],
    },
    relatedSlugs: ['hours-to-minutes', 'minutes-to-hours', 'hours-to-seconds', 'military-time-converter', 'hh-mm-ss-to-decimal-hours'],
    faqs: [
      {
        question: 'What is the base SI unit of time?',
        answer: 'The standard International System of Units (SI) base unit for time is the second (s), defined by the fixed numerical value of the cesium frequency.',
      },
    ],
  },
  // Pair conversions
  {
    slug: 'hours-to-minutes',
    canonicalPath: '/time-date/time-conversion/hours-to-minutes',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Hours to Minutes Converter',
    shortTitle: 'Hours to Minutes',
    metaTitle: 'Hours to Minutes Converter | Convert hr to min Instantly',
    metaDescription: 'Convert hours to minutes accurately with step-by-step math and decimal fraction breakdown. 1 hour = 60 minutes.',
    keywords: ['hours to minutes', 'convert hours to minutes', 'hr to min', 'hours to min converter'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'hours',
    toUnit: 'minutes',
    formula: '\\text{Minutes} = \\text{Hours} \\times 60',
    workedExample: {
      scenario: 'Converting 4.75 hours to minutes.',
      steps: ['Multiply 4.75 by 60: 4.75 x 60 = 285 minutes.'],
      conclusion: '4.75 hours = 285 minutes (or 4 hours 45 minutes).',
    },
    relatedSlugs: ['minutes-to-hours', 'hours-to-seconds', 'time-converter', 'hh-mm-ss-to-minutes'],
    faqs: [{ question: 'How many minutes is 1.5 hours?', answer: '1.5 hours multiplied by 60 equals 90 minutes.' }],
  },
  {
    slug: 'minutes-to-hours',
    canonicalPath: '/time-date/time-conversion/minutes-to-hours',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Minutes to Hours Converter',
    shortTitle: 'Minutes to Hours',
    metaTitle: 'Minutes to Hours Converter | Convert min to hr Instantly',
    metaDescription: 'Convert minutes to decimal hours and hours/minutes format. Fast and accurate time conversion.',
    keywords: ['minutes to hours', 'convert minutes to hours', 'min to hr', 'minutes to decimal hours'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'minutes',
    toUnit: 'hours',
    formula: '\\text{Hours} = \\frac{\\text{Minutes}}{60}',
    relatedSlugs: ['hours-to-minutes', 'minutes-to-seconds', 'time-converter'],
    faqs: [{ question: 'How do you convert 45 minutes to decimal hours?', answer: 'Divide 45 by 60 = 0.75 hours.' }],
  },
  {
    slug: 'hours-to-seconds',
    canonicalPath: '/time-date/time-conversion/hours-to-seconds',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Hours to Seconds Converter',
    shortTitle: 'Hours to Seconds',
    metaTitle: 'Hours to Seconds Converter | Convert hr to sec',
    metaDescription: 'Convert hours to seconds. 1 hour = 3,600 seconds. Accurate formula and conversion table.',
    keywords: ['hours to seconds', 'convert hours to seconds', 'hr to sec'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'hours',
    toUnit: 'seconds',
    formula: '\\text{Seconds} = \\text{Hours} \\times 3600',
    relatedSlugs: ['seconds-to-hours', 'hours-to-minutes', 'time-converter'],
    faqs: [{ question: 'How many seconds in 24 hours?', answer: '24 x 3,600 = 86,400 seconds.' }],
  },
  {
    slug: 'seconds-to-hours',
    canonicalPath: '/time-date/time-conversion/seconds-to-hours',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Seconds to Hours Converter',
    shortTitle: 'Seconds to Hours',
    metaTitle: 'Seconds to Hours Converter | Convert sec to hr',
    metaDescription: 'Convert seconds to hours and decimal hours with instant calculations.',
    keywords: ['seconds to hours', 'convert seconds to hours', 'sec to hr'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'seconds',
    toUnit: 'hours',
    formula: '\\text{Hours} = \\frac{\\text{Seconds}}{3600}',
    relatedSlugs: ['hours-to-seconds', 'seconds-to-minutes', 'time-converter'],
    faqs: [{ question: 'How many hours is 7,200 seconds?', answer: '7,200 / 3,600 = 2.0 hours.' }],
  },
  {
    slug: 'hours-to-days',
    canonicalPath: '/time-date/time-conversion/hours-to-days',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Hours to Days Converter',
    shortTitle: 'Hours to Days',
    metaTitle: 'Hours to Days Converter | Convert hr to days',
    metaDescription: 'Convert hours to days and fractional days. 24 hours = 1 day.',
    keywords: ['hours to days', 'convert hours to days', 'hr to days'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'hours',
    toUnit: 'days',
    formula: '\\text{Days} = \\frac{\\text{Hours}}{24}',
    relatedSlugs: ['days-to-hours', 'hours-to-minutes', 'time-converter'],
    faqs: [{ question: 'How many days is 72 hours?', answer: '72 / 24 = 3 days.' }],
  },
  {
    slug: 'days-to-hours',
    canonicalPath: '/time-date/time-conversion/days-to-hours',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Days to Hours Converter',
    shortTitle: 'Days to Hours',
    metaTitle: 'Days to Hours Converter | Convert days to hr',
    metaDescription: 'Convert calendar days to total hours. 1 day = 24 hours.',
    keywords: ['days to hours', 'convert days to hours', 'days to hr'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'days',
    toUnit: 'hours',
    formula: '\\text{Hours} = \\text{Days} \\times 24',
    relatedSlugs: ['hours-to-days', 'days-to-minutes', 'time-converter'],
    faqs: [{ question: 'How many hours in 7 days?', answer: '7 x 24 = 168 hours.' }],
  },
  {
    slug: 'minutes-to-seconds',
    canonicalPath: '/time-date/time-conversion/minutes-to-seconds',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Minutes to Seconds Converter',
    shortTitle: 'Minutes to Seconds',
    metaTitle: 'Minutes to Seconds Converter | Convert min to sec',
    metaDescription: 'Convert minutes to seconds. 1 minute = 60 seconds.',
    keywords: ['minutes to seconds', 'convert min to sec', 'minutes to sec'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'minutes',
    toUnit: 'seconds',
    formula: '\\text{Seconds} = \\text{Minutes} \\times 60',
    relatedSlugs: ['seconds-to-minutes', 'hours-to-minutes', 'time-converter'],
    faqs: [{ question: 'How many seconds in 5 minutes?', answer: '5 x 60 = 300 seconds.' }],
  },
  {
    slug: 'seconds-to-minutes',
    canonicalPath: '/time-date/time-conversion/seconds-to-minutes',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Seconds to Minutes Converter',
    shortTitle: 'Seconds to Minutes',
    metaTitle: 'Seconds to Minutes Converter | Convert sec to min',
    metaDescription: 'Convert seconds to minutes and decimal fractions. 60 seconds = 1 minute.',
    keywords: ['seconds to minutes', 'convert sec to min', 'seconds to min'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'seconds',
    toUnit: 'minutes',
    formula: '\\text{Minutes} = \\frac{\\text{Seconds}}{60}',
    relatedSlugs: ['minutes-to-seconds', 'seconds-to-hours', 'time-converter'],
    faqs: [{ question: 'How many minutes is 180 seconds?', answer: '180 / 60 = 3 minutes.' }],
  },
  {
    slug: 'days-to-minutes',
    canonicalPath: '/time-date/time-conversion/days-to-minutes',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Days to Minutes Converter',
    shortTitle: 'Days to Minutes',
    metaTitle: 'Days to Minutes Converter | Convert days to min',
    metaDescription: 'Convert days to minutes. 1 day = 1,440 minutes.',
    keywords: ['days to minutes', 'convert days to minutes', 'days to min'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'days',
    toUnit: 'minutes',
    formula: '\\text{Minutes} = \\text{Days} \\times 1440',
    relatedSlugs: ['minutes-to-days', 'days-to-hours', 'time-converter'],
    faqs: [{ question: 'How many minutes in 3 days?', answer: '3 x 1,440 = 4,320 minutes.' }],
  },
  {
    slug: 'minutes-to-days',
    canonicalPath: '/time-date/time-conversion/minutes-to-days',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Minutes to Days Converter',
    shortTitle: 'Minutes to Days',
    metaTitle: 'Minutes to Days Converter | Convert min to days',
    metaDescription: 'Convert minutes to days and fractional days. 1,440 minutes = 1 day.',
    keywords: ['minutes to days', 'convert min to days', 'minutes to days calculator'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'minutes',
    toUnit: 'days',
    formula: '\\text{Days} = \\frac{\\text{Minutes}}{1440}',
    relatedSlugs: ['days-to-minutes', 'minutes-to-hours', 'time-converter'],
    faqs: [{ question: 'How many days is 2,880 minutes?', answer: '2,880 / 1,440 = 2 days.' }],
  },
  {
    slug: 'days-to-seconds',
    canonicalPath: '/time-date/time-conversion/days-to-seconds',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Days to Seconds Converter',
    shortTitle: 'Days to Seconds',
    metaTitle: 'Days to Seconds Converter | Convert days to sec',
    metaDescription: 'Convert days to seconds. 1 day = 86,400 seconds.',
    keywords: ['days to seconds', 'convert days to seconds', 'days to sec'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'days',
    toUnit: 'seconds',
    formula: '\\text{Seconds} = \\text{Days} \\times 86400',
    relatedSlugs: ['seconds-to-days', 'days-to-hours', 'time-converter'],
    faqs: [{ question: 'How many seconds in a 7-day week?', answer: '7 x 86,400 = 604,800 seconds.' }],
  },
  {
    slug: 'seconds-to-days',
    canonicalPath: '/time-date/time-conversion/seconds-to-days',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Seconds to Days Converter',
    shortTitle: 'Seconds to Days',
    metaTitle: 'Seconds to Days Converter | Convert sec to days',
    metaDescription: 'Convert seconds to full calendar days and fractions. 86,400 seconds = 1 day.',
    keywords: ['seconds to days', 'convert seconds to days', 'sec to days'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'seconds',
    toUnit: 'days',
    formula: '\\text{Days} = \\frac{\\text{Seconds}}{86400}',
    relatedSlugs: ['days-to-seconds', 'seconds-to-hours', 'time-converter'],
    faqs: [{ question: 'How many days is 172,800 seconds?', answer: '172,800 / 86,400 = 2 days.' }],
  },
  {
    slug: 'weeks-to-days',
    canonicalPath: '/time-date/time-conversion/weeks-to-days',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Weeks to Days Converter',
    shortTitle: 'Weeks to Days',
    metaTitle: 'Weeks to Days Converter | Convert weeks to days',
    metaDescription: 'Convert weeks to calendar days. 1 week = 7 days.',
    keywords: ['weeks to days', 'convert weeks to days', 'weeks to days converter'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'weeks',
    toUnit: 'days',
    formula: '\\text{Days} = \\text{Weeks} \\times 7',
    relatedSlugs: ['days-to-weeks', 'weeks-to-months', 'time-converter'],
    faqs: [{ question: 'How many days in 52 weeks?', answer: '52 x 7 = 364 days.' }],
  },
  {
    slug: 'days-to-weeks',
    canonicalPath: '/time-date/time-conversion/days-to-weeks',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Days to Weeks Converter',
    shortTitle: 'Days to Weeks',
    metaTitle: 'Days to Weeks Converter | Convert days to weeks',
    metaDescription: 'Convert days to full weeks and remaining days. 7 days = 1 week.',
    keywords: ['days to weeks', 'convert days to weeks', 'days to weeks calculator'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'days',
    toUnit: 'weeks',
    formula: '\\text{Weeks} = \\frac{\\text{Days}}{7}',
    relatedSlugs: ['weeks-to-days', 'days-to-months', 'time-converter'],
    faqs: [{ question: 'How many weeks is 28 days?', answer: '28 / 7 = 4 weeks.' }],
  },
  {
    slug: 'years-to-months',
    canonicalPath: '/time-date/time-conversion/years-to-months',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Years to Months Converter',
    shortTitle: 'Years to Months',
    metaTitle: 'Years to Months Converter | Convert yr to months',
    metaDescription: 'Convert calendar years to months. 1 year = 12 months.',
    keywords: ['years to months', 'convert years to months', 'yr to months'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'years',
    toUnit: 'months',
    formula: '\\text{Months} = \\text{Years} \\times 12',
    relatedSlugs: ['months-to-years', 'years-to-weeks', 'time-converter'],
    faqs: [{ question: 'How many months in 3.5 years?', answer: '3.5 x 12 = 42 months.' }],
  },
  {
    slug: 'months-to-years',
    canonicalPath: '/time-date/time-conversion/months-to-years',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Months to Years Converter',
    shortTitle: 'Months to Years',
    metaTitle: 'Months to Years Converter | Convert months to yr',
    metaDescription: 'Convert months to years and fractional years. 12 months = 1 year.',
    keywords: ['months to years', 'convert months to years', 'months to yr'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'months',
    toUnit: 'years',
    formula: '\\text{Years} = \\frac{\\text{Months}}{12}',
    relatedSlugs: ['years-to-months', 'months-to-weeks', 'time-converter'],
    faqs: [{ question: 'How many years is 36 months?', answer: '36 / 12 = 3.0 years.' }],
  },
  {
    slug: 'years-to-weeks',
    canonicalPath: '/time-date/time-conversion/years-to-weeks',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Years to Weeks Converter',
    shortTitle: 'Years to Weeks',
    metaTitle: 'Years to Weeks Converter | Convert yr to weeks',
    metaDescription: 'Convert years to weeks. 1 standard year = 52.1429 weeks.',
    keywords: ['years to weeks', 'convert years to weeks', 'yr to weeks'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'years',
    toUnit: 'weeks',
    formula: '\\text{Weeks} = \\text{Years} \\times 52.1429',
    relatedSlugs: ['weeks-to-years', 'years-to-days', 'time-converter'],
    faqs: [{ question: 'Why is a year 52.14 weeks instead of exactly 52?', answer: '52 weeks x 7 = 364 days. A common solar year has 365 days (365/7 = 52.1429 weeks).' }],
  },
  {
    slug: 'weeks-to-years',
    canonicalPath: '/time-date/time-conversion/weeks-to-years',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Weeks to Years Converter',
    shortTitle: 'Weeks to Years',
    metaTitle: 'Weeks to Years Converter | Convert weeks to yr',
    metaDescription: 'Convert weeks to solar years and fractions.',
    keywords: ['weeks to years', 'convert weeks to years', 'weeks to yr'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'weeks',
    toUnit: 'years',
    formula: '\\text{Years} = \\frac{\\text{Weeks}}{52.1429}',
    relatedSlugs: ['years-to-weeks', 'weeks-to-days', 'time-converter'],
    faqs: [{ question: 'How many years is 104 weeks?', answer: '104 / 52.1429 = ~1.994 years.' }],
  },
  {
    slug: 'years-to-days',
    canonicalPath: '/time-date/time-conversion/years-to-days',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Years to Days Converter',
    shortTitle: 'Years to Days',
    metaTitle: 'Years to Days Converter | Convert yr to days',
    metaDescription: 'Convert solar years to calendar days. 1 Gregorian year = 365.2425 days.',
    keywords: ['years to days', 'convert years to days', 'yr to days'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'years',
    toUnit: 'days',
    formula: '\\text{Days} = \\text{Years} \\times 365.2425',
    relatedSlugs: ['days-to-years', 'years-to-months', 'time-converter'],
    faqs: [{ question: 'How many days in 4 years including a leap year?', answer: '365 x 3 + 366 = 1,461 days.' }],
  },
  {
    slug: 'days-to-years',
    canonicalPath: '/time-date/time-conversion/days-to-years',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Days to Years Converter',
    shortTitle: 'Days to Years',
    metaTitle: 'Days to Years Converter | Convert days to yr',
    metaDescription: 'Convert calendar days to years with Gregorian leap year compensation.',
    keywords: ['days to years', 'convert days to years', 'days to yr'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'days',
    toUnit: 'years',
    formula: '\\text{Years} = \\frac{\\text{Days}}{365.2425}',
    relatedSlugs: ['years-to-days', 'days-to-weeks', 'time-converter'],
    faqs: [{ question: 'How many years is 1,000 days?', answer: '1,000 / 365.2425 = 2.738 years.' }],
  },
  {
    slug: 'months-to-weeks',
    canonicalPath: '/time-date/time-conversion/months-to-weeks',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Months to Weeks Converter',
    shortTitle: 'Months to Weeks',
    metaTitle: 'Months to Weeks Converter | Convert months to weeks',
    metaDescription: 'Convert months to weeks. 1 average month = 4.345 weeks.',
    keywords: ['months to weeks', 'convert months to weeks', 'months to weeks calculator'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'months',
    toUnit: 'weeks',
    formula: '\\text{Weeks} = \\text{Months} \\times 4.3481',
    relatedSlugs: ['weeks-to-months', 'months-to-years', 'time-converter'],
    faqs: [{ question: 'Why isn’t a month exactly 4 weeks?', answer: '4 weeks is 28 days. Only February in common years has 28 days; other months have 30 or 31 days.' }],
  },
  {
    slug: 'weeks-to-months',
    canonicalPath: '/time-date/time-conversion/weeks-to-months',
    category: 'time-conversion',
    subcategoryTitle: 'Time Unit Conversions',
    name: 'Weeks to Months Converter',
    shortTitle: 'Weeks to Months',
    metaTitle: 'Weeks to Months Converter | Convert weeks to months',
    metaDescription: 'Convert weeks to months for project schedules and pregnancy milestones.',
    keywords: ['weeks to months', 'convert weeks to months', 'weeks to months converter'],
    searchIntent: 'converter',
    calculatorType: 'pair-converter',
    fromUnit: 'weeks',
    toUnit: 'months',
    formula: '\\text{Months} = \\frac{\\text{Weeks}}{4.3481}',
    relatedSlugs: ['months-to-weeks', 'weeks-to-days', 'time-converter'],
    faqs: [{ question: 'How many months is 12 weeks?', answer: '12 / 4.3481 = ~2.76 months.' }],
  },
  // Format converters
  {
    slug: '24-hour-to-12-hour-converter',
    canonicalPath: '/time-date/time-conversion/24-hour-to-12-hour-converter',
    category: 'time-conversion',
    subcategoryTitle: 'Time Format Converters',
    name: '24-Hour to 12-Hour Converter',
    shortTitle: '24-Hour to 12-Hour',
    metaTitle: '24-Hour to 12-Hour Converter | Convert 24h Clock to AM/PM',
    metaDescription: 'Convert 24-hour clock time (e.g. 14:30) to standard 12-hour AM/PM time (e.g. 2:30 PM) instantly with explanation.',
    keywords: ['24 hour to 12 hour converter', 'convert 24h to 12h', '24 hour clock converter', 'military time to 12 hour'],
    searchIntent: 'converter',
    calculatorType: 'format-converter',
    formatType: '24-to-12',
    relatedSlugs: ['12-hour-to-24-hour-converter', 'military-time-converter', 'time-converter'],
    faqs: [{ question: 'What is 19:45 in 12-hour AM/PM time?', answer: '19:45 in 24-hour time is 7:45 PM.' }],
  },
  {
    slug: '12-hour-to-24-hour-converter',
    canonicalPath: '/time-date/time-conversion/12-hour-to-24-hour-converter',
    category: 'time-conversion',
    subcategoryTitle: 'Time Format Converters',
    name: '12-Hour to 24-Hour Converter',
    shortTitle: '12-Hour to 24-Hour',
    metaTitle: '12-Hour to 24-Hour Converter | Convert AM/PM to 24h Clock',
    metaDescription: 'Convert 12-hour AM/PM time format to standard 24-hour clock format without ambiguity.',
    keywords: ['12 hour to 24 hour converter', 'convert am pm to 24 hour', '12h to 24h converter'],
    searchIntent: 'converter',
    calculatorType: 'format-converter',
    formatType: '12-to-24',
    relatedSlugs: ['24-hour-to-12-hour-converter', 'military-time-converter', 'time-converter'],
    faqs: [{ question: 'What is 12:00 AM in 24-hour time?', answer: '12:00 AM (midnight) is 00:00 in 24-hour time.' }],
  },
  {
    slug: 'military-time-converter',
    canonicalPath: '/time-date/military-time-converter',
    category: 'time-conversion',
    subcategoryTitle: 'Time Format Converters',
    name: 'Military Time Converter',
    shortTitle: 'Military Time',
    metaTitle: 'Military Time Converter | Convert Standard & Military Clock Time',
    metaDescription: 'Convert standard AM/PM time to 4-digit military time and phonetic military pronunciation (e.g. 0800 hours, 1430 hours).',
    keywords: ['military time converter', 'military clock converter', 'convert military time', 'military time chart'],
    searchIntent: 'converter',
    calculatorType: 'format-converter',
    formatType: 'military',
    relatedSlugs: ['24-hour-to-12-hour-converter', '12-hour-to-24-hour-converter', 'time-converter'],
    faqs: [{ question: 'How do you say 1500 hours in military time?', answer: '1500 hours is pronounced "fifteen hundred hours" and represents 3:00 PM.' }],
  },
  {
    slug: 'hh-mm-ss-to-decimal-hours',
    canonicalPath: '/time-date/time-conversion/hh-mm-ss-to-decimal-hours',
    category: 'time-conversion',
    subcategoryTitle: 'Time Format Converters',
    name: 'HH:MM:SS to Decimal Hours Converter',
    shortTitle: 'HH:MM:SS to Decimal Hours',
    metaTitle: 'HH:MM:SS to Decimal Hours Converter | Time to Decimal',
    metaDescription: 'Convert hours, minutes, and seconds (HH:MM:SS) to decimal hours for timesheet billing and payroll.',
    keywords: ['hh mm ss to decimal hours', 'time to decimal hours', 'convert minutes to decimal hours', 'timesheet decimal converter'],
    searchIntent: 'converter',
    calculatorType: 'format-converter',
    formatType: 'hms-to-decimal',
    formula: '\\text{Decimal Hours} = \\text{Hours} + \\frac{\\text{Minutes}}{60} + \\frac{\\text{Seconds}}{3600}',
    relatedSlugs: ['decimal-hours-to-hh-mm-ss', 'time-card-calculator', 'hours-to-minutes'],
    faqs: [{ question: 'What is 8 hours and 15 minutes in decimal hours?', answer: '8 + (15/60) = 8.25 decimal hours.' }],
  },
  {
    slug: 'hh-mm-ss-to-minutes',
    canonicalPath: '/time-date/time-conversion/hh-mm-ss-to-minutes',
    category: 'time-conversion',
    subcategoryTitle: 'Time Format Converters',
    name: 'HH:MM:SS to Minutes Converter',
    shortTitle: 'HH:MM:SS to Minutes',
    metaTitle: 'HH:MM:SS to Minutes Converter | Convert Clock Time to Total Minutes',
    metaDescription: 'Convert hours, minutes, and seconds to total elapsed minutes with decimal precision.',
    keywords: ['hh mm ss to minutes', 'time to minutes converter', 'clock to total minutes'],
    searchIntent: 'converter',
    calculatorType: 'format-converter',
    formatType: 'hms-to-min',
    relatedSlugs: ['hh-mm-ss-to-decimal-hours', 'hours-to-minutes', 'time-converter'],
    faqs: [{ question: 'How many total minutes is 2:30:00?', answer: '(2 x 60) + 30 = 150 minutes.' }],
  },
  {
    slug: 'hh-mm-ss-to-seconds',
    canonicalPath: '/time-date/time-conversion/hh-mm-ss-to-seconds',
    category: 'time-conversion',
    subcategoryTitle: 'Time Format Converters',
    name: 'HH:MM:SS to Seconds Converter',
    shortTitle: 'HH:MM:SS to Seconds',
    metaTitle: 'HH:MM:SS to Seconds Converter | Convert Clock Time to Total Seconds',
    metaDescription: 'Convert HH:MM:SS timestamps directly to cumulative seconds for video editing, physics calculations, and programming.',
    keywords: ['hh mm ss to seconds', 'time to seconds converter', 'clock to seconds'],
    searchIntent: 'converter',
    calculatorType: 'format-converter',
    formatType: 'hms-to-sec',
    relatedSlugs: ['hours-to-seconds', 'minutes-to-seconds', 'time-converter'],
    faqs: [{ question: 'How many seconds is 1 hour, 15 minutes, and 30 seconds?', answer: '3600 + (15 x 60) + 30 = 4,530 seconds.' }],
  },
  {
    slug: 'decimal-hours-to-hh-mm-ss',
    canonicalPath: '/time-date/time-conversion/decimal-hours-to-hh-mm-ss',
    category: 'time-conversion',
    subcategoryTitle: 'Time Format Converters',
    name: 'Decimal Hours to HH:MM:SS Converter',
    shortTitle: 'Decimal Hours to HH:MM:SS',
    metaTitle: 'Decimal Hours to HH:MM:SS Converter | Decimal to Clock Time',
    metaDescription: 'Convert decimal hours (e.g. 7.75 hours) back into hours, minutes, and seconds (7h 45m 00s).',
    keywords: ['decimal hours to hh mm ss', 'decimal to time converter', 'decimal hours to minutes and seconds'],
    searchIntent: 'converter',
    calculatorType: 'format-converter',
    formatType: 'decimal-to-hms',
    relatedSlugs: ['hh-mm-ss-to-decimal-hours', 'time-calculator', 'time-card-calculator'],
    faqs: [{ question: 'What is 5.4 hours in hours and minutes?', answer: '5.4 hours = 5 hours and (0.4 x 60) = 24 minutes (05:24:00).' }],
  },
];
