import { TimeToolDefinition } from './types';

export const COUNTDOWN_TIME_TOOLS: TimeToolDefinition[] = [
  {
    slug: 'countdown-timer',
    canonicalPath: '/time-date/countdown-timer',
    category: 'countdown',
    subcategoryTitle: 'Event & Target Countdowns',
    name: 'Countdown Timer',
    shortTitle: 'Countdown Timer',
    metaTitle: 'Countdown Timer | Live Real-Time Target Date Countdown',
    metaDescription: 'Free full-screen countdown timer with chime audio synthesizer, iCalendar download, and precise days, hours, minutes, and seconds tracking.',
    keywords: ['countdown timer', 'online countdown', 'live countdown', 'countdown clock', 'event countdown'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownDefaultName: 'Target Event',
    relatedSlugs: ['new-year-countdown', 'christmas-countdown', 'event-countdown', 'birthday-countdown'],
    faqs: [
      {
        question: 'Can I export the countdown event to my calendar?',
        answer: 'Yes, click "Export to Calendar (.ics)" to instantly add the target event to Google Calendar, Apple Calendar, or Outlook.',
      },
      {
        question: 'Does the timer play sound when the countdown reaches zero?',
        answer: 'Yes, an integrated Web Audio harmonic chime sounds when the countdown completes.',
      },
    ],
  },
  {
    slug: 'birthday-countdown',
    canonicalPath: '/time-date/countdown/birthday-countdown',
    category: 'countdown',
    subcategoryTitle: 'Event & Target Countdowns',
    name: 'Birthday Countdown',
    shortTitle: 'Birthday Countdown',
    metaTitle: 'Birthday Countdown | How Many Days Until My Birthday?',
    metaDescription: 'Track how many days, hours, minutes, and seconds until your next birthday. Includes celebratory chime and calendar export.',
    keywords: ['birthday countdown', 'days until birthday', 'how many days until my birthday', 'birthday timer'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownDefaultName: 'Birthday Celebration',
    relatedSlugs: ['age-calculator', 'countdown-timer', 'event-countdown'],
    faqs: [{ question: 'How is the next birthday date computed?', answer: 'The countdown automatically calculates your next upcoming birthday anniversary based on today’s date.' }],
  },
  {
    slug: 'wedding-countdown',
    canonicalPath: '/time-date/countdown/wedding-countdown',
    category: 'countdown',
    subcategoryTitle: 'Event & Target Countdowns',
    name: 'Wedding Countdown',
    shortTitle: 'Wedding Countdown',
    metaTitle: 'Wedding Countdown | Count Down to the Big Day',
    metaDescription: 'Live customizable wedding countdown clock for couples and guests with calendar reminder download.',
    keywords: ['wedding countdown', 'days until wedding', 'wedding timer', 'wedding clock countdown'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownDefaultName: 'Our Wedding Day',
    relatedSlugs: ['event-countdown', 'vacation-countdown', 'countdown-timer'],
    faqs: [{ question: 'Can I share this wedding countdown in full-screen mode?', answer: 'Yes, toggle the full-screen button for distraction-free presentation during wedding planning.' }],
  },
  {
    slug: 'event-countdown',
    canonicalPath: '/time-date/event-countdown',
    category: 'countdown',
    subcategoryTitle: 'Event & Target Countdowns',
    name: 'Event Countdown',
    shortTitle: 'Event Countdown',
    metaTitle: 'Event Countdown | Live Countdown to Any Date or Event',
    metaDescription: 'Create a live countdown timer for concerts, festivals, conferences, product launches, or family gatherings.',
    keywords: ['event countdown', 'countdown to event', 'custom event timer', 'event clock'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownDefaultName: 'Special Event',
    relatedSlugs: ['countdown-timer', 'project-deadline-countdown', 'vacation-countdown'],
    faqs: [{ question: 'Can I set an exact target time down to the minute?', answer: 'Yes, pick both date and time (e.g. 19:30:00) for sub-second precision.' }],
  },
  {
    slug: 'vacation-countdown',
    canonicalPath: '/time-date/countdown/vacation-countdown',
    category: 'countdown',
    subcategoryTitle: 'Event & Target Countdowns',
    name: 'Vacation Countdown',
    shortTitle: 'Vacation Countdown',
    metaTitle: 'Vacation Countdown | How Long Until Vacation & Holiday?',
    metaDescription: 'Count down the days, hours, and minutes until your upcoming holiday, flight, or road trip begins.',
    keywords: ['vacation countdown', 'days until vacation', 'holiday countdown', 'trip countdown'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownDefaultName: 'Vacation Departure',
    relatedSlugs: ['event-countdown', 'countdown-timer', 'project-deadline-countdown'],
    faqs: [{ question: 'How do I add my vacation flight date?', answer: 'Select your departure date and time in the interactive date selector.' }],
  },
  {
    slug: 'exam-countdown',
    canonicalPath: '/time-date/countdown/exam-countdown',
    category: 'countdown',
    subcategoryTitle: 'Event & Target Countdowns',
    name: 'Exam Countdown',
    shortTitle: 'Exam Countdown',
    metaTitle: 'Exam Countdown | Study Deadline & Test Countdown Clock',
    metaDescription: 'Keep track of study time and count down to upcoming academic exams, finals, SATs, GREs, or licensing tests.',
    keywords: ['exam countdown', 'test countdown', 'finals countdown', 'study countdown timer'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownDefaultName: 'Final Exam',
    relatedSlugs: ['project-deadline-countdown', 'countdown-timer', 'timers'],
    faqs: [{ question: 'Can I use this timer alongside Pomodoro study blocks?', answer: 'Yes, check out our 25-minute Pomodoro preset in the Timers section.' }],
  },
  {
    slug: 'project-deadline-countdown',
    canonicalPath: '/time-date/countdown/project-deadline-countdown',
    category: 'countdown',
    subcategoryTitle: 'Event & Target Countdowns',
    name: 'Project Deadline Countdown',
    shortTitle: 'Project Deadline',
    metaTitle: 'Project Deadline Countdown | Sprint & Release Countdown Clock',
    metaDescription: 'Real-time project milestone and sprint deadline countdown for teams, developers, and agile project managers.',
    keywords: ['project deadline countdown', 'sprint countdown', 'release countdown timer', 'deadline tracker'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownDefaultName: 'Project Milestone Deadline',
    relatedSlugs: ['work-time-calculator', 'business-day-calculator', 'countdown-timer'],
    faqs: [{ question: 'Can I calculate remaining business hours until the deadline?', answer: 'Use our Business Day Calculator to exclude non-working weekends from your deadline.' }],
  },
  // Annual Holiday Countdowns
  {
    slug: 'new-year-countdown',
    canonicalPath: '/time-date/countdown/new-year-countdown',
    category: 'countdown',
    subcategoryTitle: 'Holiday Countdowns',
    name: 'New Year Countdown',
    shortTitle: 'New Year',
    metaTitle: 'New Year Countdown | How Long Until New Year?',
    metaDescription: 'Live real-time countdown to New Year’s Day (January 1st) with chime bell synthesizer and midnight celebration display.',
    keywords: ['new year countdown', 'how long until new year', 'days until new year', 'new years eve countdown'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetMonth: 0, // Jan
    countdownTargetDay: 1,
    countdownDefaultName: "New Year's Day",
    relatedSlugs: ['christmas-countdown', 'countdown-timer', 'how-long-until-midnight'],
    faqs: [{ question: 'Does the New Year countdown adjust to my local time zone?', answer: 'Yes, the countdown automatically targets January 1st 00:00:00 in your browser’s local time zone.' }],
  },
  {
    slug: 'christmas-countdown',
    canonicalPath: '/time-date/countdown/christmas-countdown',
    category: 'countdown',
    subcategoryTitle: 'Holiday Countdowns',
    name: 'Christmas Countdown',
    shortTitle: 'Christmas',
    metaTitle: 'Christmas Countdown | How Many Days Until Christmas?',
    metaDescription: 'Track how many days, hours, minutes, and seconds until Christmas Day (December 25). Real-time live countdown.',
    keywords: ['christmas countdown', 'how many days until christmas', 'days until christmas', 'xmas countdown'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetMonth: 11, // Dec
    countdownTargetDay: 25,
    countdownDefaultName: 'Christmas Day',
    relatedSlugs: ['new-year-countdown', 'halloween-countdown', 'countdown-timer'],
    faqs: [{ question: 'What happens when Christmas passes this year?', answer: 'The countdown automatically rolls over to December 25th of the following calendar year.' }],
  },
  {
    slug: 'halloween-countdown',
    canonicalPath: '/time-date/countdown/halloween-countdown',
    category: 'countdown',
    subcategoryTitle: 'Holiday Countdowns',
    name: 'Halloween Countdown',
    shortTitle: 'Halloween',
    metaTitle: 'Halloween Countdown | How Many Days Until Halloween?',
    metaDescription: 'Live countdown to Halloween (October 31st). Find out exact days, hours, and minutes remaining.',
    keywords: ['halloween countdown', 'how many days until halloween', 'days until halloween', 'halloween timer'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetMonth: 9, // Oct
    countdownTargetDay: 31,
    countdownDefaultName: 'Halloween',
    relatedSlugs: ['christmas-countdown', 'new-year-countdown', 'countdown-timer'],
    faqs: [{ question: 'When is Halloween celebrated?', answer: 'Halloween is celebrated annually on October 31st.' }],
  },
  {
    slug: 'valentines-day-countdown',
    canonicalPath: '/time-date/countdown/valentines-day-countdown',
    category: 'countdown',
    subcategoryTitle: 'Holiday Countdowns',
    name: "Valentine's Day Countdown",
    shortTitle: "Valentine's Day",
    metaTitle: "Valentine's Day Countdown | Days Until February 14",
    metaDescription: 'Live countdown to Valentine’s Day (February 14th). Plan your romantic dinner and gifts on time.',
    keywords: ['valentines day countdown', 'days until valentines day', 'february 14 countdown'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetMonth: 1, // Feb
    countdownTargetDay: 14,
    countdownDefaultName: "Valentine's Day",
    relatedSlugs: ['new-year-countdown', 'wedding-countdown', 'countdown-timer'],
    faqs: [{ question: 'When is Valentine’s Day?', answer: 'Valentine’s Day is celebrated on February 14 every year.' }],
  },
  {
    slug: 'easter-countdown',
    canonicalPath: '/time-date/countdown/easter-countdown',
    category: 'countdown',
    subcategoryTitle: 'Holiday Countdowns',
    name: 'Easter Countdown',
    shortTitle: 'Easter',
    metaTitle: 'Easter Countdown | Days Until Easter Sunday',
    metaDescription: 'Track how many days and hours until Easter Sunday based on the Computus lunar-solar calendar calculation.',
    keywords: ['easter countdown', 'days until easter', 'when is easter sunday', 'easter timer'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetMonth: 3, // Apr
    countdownTargetDay: 5,
    countdownDefaultName: 'Easter Sunday',
    relatedSlugs: ['mothers-day-countdown', 'christmas-countdown', 'countdown-timer'],
    faqs: [{ question: 'How is the date of Easter determined?', answer: 'Easter Sunday is celebrated on the first Sunday after the full moon that occurs on or after the vernal equinox.' }],
  },
  {
    slug: 'mothers-day-countdown',
    canonicalPath: '/time-date/countdown/mothers-day-countdown',
    category: 'countdown',
    subcategoryTitle: 'Holiday Countdowns',
    name: "Mother's Day Countdown",
    shortTitle: "Mother's Day",
    metaTitle: "Mother's Day Countdown | Days Until Mother's Day",
    metaDescription: 'Live countdown to Mother’s Day (second Sunday in May in the US/Canada).',
    keywords: ['mothers day countdown', 'days until mothers day', 'when is mothers day'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetMonth: 4, // May
    countdownTargetDay: 10,
    countdownDefaultName: "Mother's Day",
    relatedSlugs: ['fathers-day-countdown', 'birthday-countdown', 'countdown-timer'],
    faqs: [{ question: 'When is Mother’s Day in the US?', answer: 'In the US and Canada, Mother’s Day is held annually on the second Sunday of May.' }],
  },
  {
    slug: 'fathers-day-countdown',
    canonicalPath: '/time-date/countdown/fathers-day-countdown',
    category: 'countdown',
    subcategoryTitle: 'Holiday Countdowns',
    name: "Father's Day Countdown",
    shortTitle: "Father's Day",
    metaTitle: "Father's Day Countdown | Days Until Father's Day",
    metaDescription: 'Live countdown to Father’s Day (third Sunday in June in the US/Canada).',
    keywords: ['fathers day countdown', 'days until fathers day', 'when is fathers day'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetMonth: 5, // Jun
    countdownTargetDay: 21,
    countdownDefaultName: "Father's Day",
    relatedSlugs: ['mothers-day-countdown', 'birthday-countdown', 'countdown-timer'],
    faqs: [{ question: 'When is Father’s Day in the US?', answer: 'In the US and Canada, Father’s Day is celebrated on the third Sunday of June.' }],
  },
  // "How Long Until..." Intra-day milestones
  {
    slug: 'how-long-until-midnight',
    canonicalPath: '/time-date/countdown/how-long-until-midnight',
    category: 'countdown',
    subcategoryTitle: 'Intra-Day Countdowns',
    name: 'How Long Until Midnight?',
    shortTitle: 'Until Midnight',
    metaTitle: 'How Long Until Midnight? | Live Countdown to 12:00 AM',
    metaDescription: 'Live real-time countdown to midnight (00:00:00). Find out exact hours, minutes, and seconds remaining in today.',
    keywords: ['how long until midnight', 'time until midnight', 'countdown to midnight', 'hours until midnight'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetTime: '00:00:00',
    countdownDefaultName: 'Midnight',
    relatedSlugs: ['how-long-until-noon', 'countdown-timer', 'time-calculator'],
    faqs: [{ question: 'How is time until midnight calculated?', answer: 'Midnight is 24:00 (or 00:00 of tomorrow). We compute 86,400 seconds minus the total seconds elapsed today.' }],
  },
  {
    slug: 'how-long-until-noon',
    canonicalPath: '/time-date/countdown/how-long-until-noon',
    category: 'countdown',
    subcategoryTitle: 'Intra-Day Countdowns',
    name: 'How Long Until Noon?',
    shortTitle: 'Until Noon',
    metaTitle: 'How Long Until Noon? | Live Countdown to 12:00 PM (Midday)',
    metaDescription: 'Live countdown clock to 12:00 PM noon. Track hours, minutes, and seconds until lunchtime and midday.',
    keywords: ['how long until noon', 'time until noon', 'countdown to noon', 'hours until 12 pm'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetTime: '12:00:00',
    countdownDefaultName: 'Noon (12:00 PM)',
    relatedSlugs: ['how-long-until-midnight', 'how-long-until-3-00-pm', 'countdown-timer'],
    faqs: [{ question: 'What happens if it is already past 12:00 PM today?', answer: 'The countdown automatically targets 12:00 PM noon of tomorrow.' }],
  },
  {
    slug: 'how-long-until-3-00-pm',
    canonicalPath: '/time-date/countdown/how-long-until-3-00-pm',
    category: 'countdown',
    subcategoryTitle: 'Intra-Day Countdowns',
    name: 'How Long Until 3:00 PM?',
    shortTitle: 'Until 3:00 PM',
    metaTitle: 'How Long Until 3:00 PM? | Live Countdown to 15:00',
    metaDescription: 'Live real-time countdown to 3:00 PM (15:00). Ideal for school dismissal, afternoon meetings, and market close tracking.',
    keywords: ['how long until 3 pm', 'time until 3 00 pm', 'countdown to 3 pm', 'hours until 3 pm'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetTime: '15:00:00',
    countdownDefaultName: '3:00 PM',
    relatedSlugs: ['how-long-until-3-30-pm', 'how-long-until-4-00-pm', 'how-long-until-noon'],
    faqs: [{ question: 'How is 3:00 PM represented in 24-hour clock?', answer: '3:00 PM is 15:00:00 in 24-hour standard time.' }],
  },
  {
    slug: 'how-long-until-3-30-pm',
    canonicalPath: '/time-date/countdown/how-long-until-3-30-pm',
    category: 'countdown',
    subcategoryTitle: 'Intra-Day Countdowns',
    name: 'How Long Until 3:30 PM?',
    shortTitle: 'Until 3:30 PM',
    metaTitle: 'How Long Until 3:30 PM? | Live Countdown to 15:30',
    metaDescription: 'Live real-time countdown to 3:30 PM. Track remaining minutes and seconds until your 3:30 appointment.',
    keywords: ['how long until 3 30 pm', 'time until 3 30 pm', 'countdown to 3 30 pm'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetTime: '15:30:00',
    countdownDefaultName: '3:30 PM',
    relatedSlugs: ['how-long-until-3-00-pm', 'how-long-until-4-00-pm', 'countdown-timer'],
    faqs: [{ question: 'What is 3:30 PM in military time?', answer: '3:30 PM is 1530 hours.' }],
  },
  {
    slug: 'how-long-until-4-00-pm',
    canonicalPath: '/time-date/countdown/how-long-until-4-00-pm',
    category: 'countdown',
    subcategoryTitle: 'Intra-Day Countdowns',
    name: 'How Long Until 4:00 PM?',
    shortTitle: 'Until 4:00 PM',
    metaTitle: 'How Long Until 4:00 PM? | Live Countdown to 16:00',
    metaDescription: 'Live real-time countdown to 4:00 PM (16:00). Track time remaining until US stock market close and end-of-workday.',
    keywords: ['how long until 4 pm', 'time until 4 00 pm', 'countdown to 4 pm', 'hours until 4 pm'],
    searchIntent: 'countdown',
    calculatorType: 'countdown',
    countdownTargetTime: '16:00:00',
    countdownDefaultName: '4:00 PM',
    relatedSlugs: ['how-long-until-3-00-pm', 'how-long-until-midnight', 'countdown-timer'],
    faqs: [{ question: 'Why is 4:00 PM significant in financial markets?', answer: 'In the United States, regular trading on major stock exchanges (NYSE, NASDAQ) closes at 4:00 PM Eastern Time.' }],
  },
];
