import { TimeToolDefinition } from './types';

const DAY_OFFSET_CONFIGS = [
  { days: 7, slug: 'date-7-days-from-today', title: 'Date 7 Days From Today (1 Week)' },
  { days: 14, slug: 'date-14-days-from-today', title: 'Date 14 Days From Today (2 Weeks)' },
  { days: 21, slug: 'date-21-days-from-today', title: 'Date 21 Days From Today (3 Weeks)' },
  { days: 30, slug: 'date-30-days-from-today', title: 'Date 30 Days From Today' },
  { days: 45, slug: 'date-45-days-from-today', title: 'Date 45 Days From Today' },
  { days: 60, slug: 'date-60-days-from-today', title: 'Date 60 Days From Today' },
  { days: 90, slug: 'date-90-days-from-today', title: 'Date 90 Days From Today' },
  { days: 120, slug: 'date-120-days-from-today', title: 'Date 120 Days From Today' },
];

export const REFERENCE_TIME_TOOLS: TimeToolDefinition[] = [
  {
    slug: 'todays-date',
    canonicalPath: '/time-date/calendar/todays-date',
    category: 'calendar',
    subcategoryTitle: 'Dynamic Date & Time Reference',
    name: "Today's Date",
    shortTitle: "Today's Date",
    metaTitle: "Today's Date | Current Date, Day of the Week & Year Info",
    metaDescription: "Live display of today's date in multiple international formats (ISO 8601, US, UK), current week number, and days elapsed this year.",
    keywords: ["today's date", 'current date', 'what is today date', 'today day of the week', 'iso date today'],
    searchIntent: 'reference',
    calculatorType: 'date-reference',
    referenceMetricType: 'today',
    relatedSlugs: ['todays-day-of-the-year', 'current-week-number', 'days-left-in-the-year'],
    faqs: [{ question: "What is today's date in ISO 8601 standard?", answer: "ISO 8601 formats dates as YYYY-MM-DD (e.g. 2026-10-03), avoiding day/month confusion worldwide." }],
  },
  {
    slug: 'todays-day-of-the-year',
    canonicalPath: '/time-date/calendar/todays-day-of-the-year',
    category: 'calendar',
    subcategoryTitle: 'Dynamic Date & Time Reference',
    name: "Today's Day of the Year",
    shortTitle: 'Day of Year',
    metaTitle: "Today's Day of the Year | Day Number Out of 365/366",
    metaDescription: "Find out what day of the year today is (ordinal day 1 to 365/366) and the total percentage of the year completed.",
    keywords: ['day of the year today', 'ordinal day today', 'what day of the year is it', 'day number today'],
    searchIntent: 'reference',
    calculatorType: 'date-reference',
    referenceMetricType: 'day-of-year',
    relatedSlugs: ['todays-date', 'current-week-number', 'days-left-in-the-year'],
    faqs: [{ question: 'How is the day of the year numbered?', answer: 'January 1 is day 1, December 31 is day 365 (or day 366 in leap years).' }],
  },
  {
    slug: 'current-week-number',
    canonicalPath: '/time-date/calendar/current-week-number',
    category: 'calendar',
    subcategoryTitle: 'Dynamic Date & Time Reference',
    name: 'Current Week Number',
    shortTitle: 'Current Week Number',
    metaTitle: 'Current Week Number | ISO Week of the Year Today',
    metaDescription: 'Find out the current ISO 8601 week number (Week 1 to 52/53) and total weeks remaining in the year.',
    keywords: ['current week number', 'what week of the year is it', 'week number today', 'iso week number'],
    searchIntent: 'reference',
    calculatorType: 'date-reference',
    referenceMetricType: 'week-number',
    relatedSlugs: ['todays-date', 'weeks-left-in-the-year', 'todays-day-of-the-year'],
    faqs: [{ question: 'What is the ISO 8601 week definition?', answer: 'An ISO week begins on Monday. Week 1 is the week with the first Thursday of the new year (containing at least 4 days of January).' }],
  },
  {
    slug: 'days-left-in-the-year',
    canonicalPath: '/time-date/calendar/days-left-in-the-year',
    category: 'calendar',
    subcategoryTitle: 'Dynamic Date & Time Reference',
    name: 'Days Left in the Year',
    shortTitle: 'Days Left in Year',
    metaTitle: 'Days Left in the Year | Countdown to New Year’s Eve',
    metaDescription: 'Discover exactly how many calendar days and working days remain in the current year until December 31st.',
    keywords: ['days left in the year', 'how many days left in the year', 'days until end of year', 'remaining days this year'],
    searchIntent: 'reference',
    calculatorType: 'date-reference',
    referenceMetricType: 'days-left-year',
    relatedSlugs: ['weeks-left-in-the-year', 'todays-date', 'new-year-countdown'],
    faqs: [{ question: 'How many days are left in the year?', answer: 'The tool calculates 365 (or 366 in leap years) minus the current ordinal day of the year.' }],
  },
  {
    slug: 'weeks-left-in-the-year',
    canonicalPath: '/time-date/calendar/weeks-left-in-the-year',
    category: 'calendar',
    subcategoryTitle: 'Dynamic Date & Time Reference',
    name: 'Weeks Left in the Year',
    shortTitle: 'Weeks Left in Year',
    metaTitle: 'Weeks Left in the Year | Number of Weeks Remaining',
    metaDescription: 'Calculate how many full weeks and fractional weeks remain in the year for Q4 planning and sprint scheduling.',
    keywords: ['weeks left in the year', 'how many weeks left in the year', 'remaining weeks this year'],
    searchIntent: 'reference',
    calculatorType: 'date-reference',
    referenceMetricType: 'weeks-left-year',
    relatedSlugs: ['days-left-in-the-year', 'current-week-number', 'new-year-countdown'],
    faqs: [{ question: 'How many weeks are in a standard year?', answer: 'A standard calendar year has 52 weeks plus 1 day (or 2 days in leap years).' }],
  },
  {
    slug: 'date-6-months-from-today',
    canonicalPath: '/time-date/calendar/date-6-months-from-today',
    category: 'calendar',
    subcategoryTitle: 'Future Date Offsets',
    name: 'Date 6 Months From Today',
    shortTitle: '6 Months From Today',
    metaTitle: 'Date 6 Months From Today | Future Calendar Date Calculator',
    metaDescription: 'Find out what exact calendar date and day of the week it will be exactly 6 months from today.',
    keywords: ['date 6 months from today', '6 months from today date', 'what date is 6 months from today'],
    searchIntent: 'reference',
    calculatorType: 'days-from-today',
    relativeMonthsOffset: 6,
    relatedSlugs: ['date-12-months-from-today', 'date-90-days-from-today', 'todays-date'],
    faqs: [{ question: 'What date will it be 6 months from today?', answer: 'The tool automatically adds 6 months to today’s local date with end-of-month calendar boundary pinning.' }],
  },
  {
    slug: 'date-12-months-from-today',
    canonicalPath: '/time-date/calendar/date-12-months-from-today',
    category: 'calendar',
    subcategoryTitle: 'Future Date Offsets',
    name: 'Date 12 Months From Today',
    shortTitle: '12 Months From Today',
    metaTitle: 'Date 12 Months From Today | 1 Year Ahead Calendar Date',
    metaDescription: 'Find out what calendar date and weekday it will be exactly 12 months (1 full calendar year) from today.',
    keywords: ['date 12 months from today', '1 year from today date', 'date in 12 months'],
    searchIntent: 'reference',
    calculatorType: 'days-from-today',
    relativeMonthsOffset: 12,
    relatedSlugs: ['date-6-months-from-today', 'todays-date', 'days-left-in-the-year'],
    faqs: [{ question: 'Is 12 months from today always the same date next year?', answer: 'Yes, except on February 29 (leap day), which pins to Feb 28 in non-leap years.' }],
  },
  {
    slug: 'date-x-weeks-from-today',
    canonicalPath: '/time-date/calendar/date-x-weeks-from-today',
    category: 'calendar',
    subcategoryTitle: 'Future Date Offsets',
    name: 'Date X Weeks From Today Calculator',
    shortTitle: 'X Weeks From Today',
    metaTitle: 'Date X Weeks From Today | Custom Weeks Future Date Finder',
    metaDescription: 'Calculate what date it will be 1 to 52 weeks from today with interactive week slider.',
    keywords: ['date x weeks from today', 'weeks from today date', 'future date in weeks'],
    searchIntent: 'reference',
    calculatorType: 'days-from-today',
    relativeWeeksOffset: 4,
    relatedSlugs: ['date-30-days-from-today', 'weeks-between-dates-calculator', 'todays-date'],
    faqs: [{ question: 'How do you calculate a date N weeks away?', answer: 'Multiply the number of weeks by 7 and add that number of days to the start date.' }],
  },
  ...DAY_OFFSET_CONFIGS.map(
    (cfg): TimeToolDefinition => ({
      slug: cfg.slug,
      canonicalPath: `/time-date/calendar/${cfg.slug}`,
      category: 'calendar',
      subcategoryTitle: 'Future Date Offsets',
      name: cfg.title,
      shortTitle: `${cfg.days} Days From Today`,
      metaTitle: `${cfg.title} | Exact Calendar Date & Day of Week`,
      metaDescription: `Find what date and day of the week it will be ${cfg.days} days from today. Updated in real time for your local time zone.`,
      keywords: [`date ${cfg.days} days from today`, `${cfg.days} days from today date`, `what date is ${cfg.days} days from today`],
      searchIntent: 'reference',
      calculatorType: 'days-from-today',
      relativeDaysOffset: cfg.days,
      relatedSlugs: ['todays-date', 'date-30-days-from-today', 'days-from-today-calculator'],
      faqs: [
        {
          question: `What day of the week is ${cfg.days} days from today?`,
          answer: `The tool dynamically calculates the exact future date, weekday name, and calendar quarter ${cfg.days} days ahead.`,
        },
      ],
    })
  ),
  // Guides
  {
    slug: 'gregorian-leap-year-guide',
    canonicalPath: '/time-date/guides/gregorian-leap-year-guide',
    category: 'guides',
    subcategoryTitle: 'Timekeeping & Calendar Guides',
    name: 'Understanding Leap Years & Gregorian Calendar Reform',
    shortTitle: 'Leap Year Guide',
    metaTitle: 'Leap Year Guide | The Science and Math of Gregorian Leap Years',
    metaDescription: 'Learn why leap years exist, the math of the 400-year Gregorian cycle, and why centuries are not always leap years.',
    keywords: ['leap year guide', 'why do we have leap years', 'gregorian calendar rule', 'century leap years'],
    searchIntent: 'educational',
    calculatorType: 'guide',
    relatedSlugs: ['leap-year-calculator', 'date-calculator', 'day-of-week-calculator'],
    faqs: [{ question: 'Who introduced the Gregorian calendar?', answer: 'Pope Gregory XIII promulgated the Gregorian calendar reform in 1582 to correct the Julian calendar drift.' }],
    guideContent: {
      summary: 'The Earth takes approximately 365.2422 solar days to complete one full revolution around the Sun. Without periodic adjustments, human calendars drift out of alignment with the seasons by roughly 1 day every 4 years.',
      sections: [
        {
          heading: '1. The Solar Problem and Julian Drift',
          body: 'Under the ancient Julian calendar established by Julius Caesar in 45 BCE, a leap day was inserted every four years without exception. This created an average year length of 365.25 days—about 11 minutes and 14 seconds longer than the actual astronomical tropical year. Over 1,600 years, this accumulated an error of approximately 10 days, displacing the vernal equinox from March 21 to March 11.',
        },
        {
          heading: '2. The Gregorian Three-Part Rule',
          body: 'In 1582, the Gregorian reform instituted a more precise three-part rule: (1) Any year divisible by 4 is a leap year; (2) EXCEPT years divisible by 100 are common years; (3) UNLESS the year is also divisible by 400, in which case it is a leap year. This gives an average Gregorian year of 365.2425 days, reducing astronomical drift to merely 1 day every 3,236 years.',
        },
      ],
    },
  },
  {
    slug: 'military-time-24-hour-clock-guide',
    canonicalPath: '/time-date/guides/military-time-24-hour-clock-guide',
    category: 'guides',
    subcategoryTitle: 'Timekeeping & Calendar Guides',
    name: 'The Complete Guide to Military Time and the 24-Hour Clock',
    shortTitle: 'Military Time Guide',
    metaTitle: 'Military Time Guide | Reading 24-Hour Clocks and Phonetic Pronunciation',
    metaDescription: 'Master 24-hour clock notation and military time conversion with pronunciation charts and operational examples.',
    keywords: ['military time guide', 'how to read military time', '24 hour clock guide', 'military time pronunciation'],
    searchIntent: 'educational',
    calculatorType: 'guide',
    relatedSlugs: ['military-time-converter', '24-hour-to-12-hour-converter', '12-hour-to-24-hour-converter'],
    faqs: [{ question: 'Why does aviation and emergency medicine use military time?', answer: 'Military time eliminates deadly AM/PM ambiguities in flight plans, surgery schedules, and emergency response.' }],
    guideContent: {
      summary: 'Military time and 24-hour timekeeping eliminate ambiguity across global aviation, emergency services, healthcare, and telecommunications by assigning every minute in a day a unique four-digit identifier from 0000 to 2359.',
      sections: [
        {
          heading: '1. Structure of the 24-Hour Clock',
          body: 'Unlike the 12-hour AM/PM system which recycles numerals twice per day, military time counts continuously from midnight (0000) to 2359. Hours are written without a colon in pure military format (e.g. 1730 hours) or with a colon in standard ISO 8601 notation (17:30:00).',
        },
        {
          heading: '2. Verbal Phonetics and Pronunciation',
          body: 'On-the-hour timestamps are spoken with "hundred" (e.g. 0600 is "zero six hundred hours", 1400 is "fourteen hundred hours"). Split minutes are appended directly (e.g. 1430 is "fourteen thirty hours", 0805 is "zero eight zero five hours").',
        },
      ],
    },
  },
  {
    slug: 'decimal-hours-vs-clock-time-guide',
    canonicalPath: '/time-date/guides/decimal-hours-vs-clock-time-guide',
    category: 'guides',
    subcategoryTitle: 'Timekeeping & Calendar Guides',
    name: 'Decimal Hours vs Clock Time: Converting for Payroll and Invoicing',
    shortTitle: 'Decimal Hours Guide',
    metaTitle: 'Decimal Hours Guide | Clock Time vs Decimal Hours in Payroll',
    metaDescription: 'Learn how to convert minutes to decimal hours for accurate payroll, billing, and freelance timesheets.',
    keywords: ['decimal hours guide', 'payroll hours conversion', 'minutes to decimal hours formula'],
    searchIntent: 'educational',
    calculatorType: 'guide',
    relatedSlugs: ['hh-mm-ss-to-decimal-hours', 'decimal-hours-to-hh-mm-ss', 'time-card-calculator'],
    faqs: [{ question: 'Why does payroll require decimal hours?', answer: 'Accounting software multiplies hours by wage rates using standard base-10 arithmetic, whereas clock minutes operate in base-60 (sexagesimal).' }],
    guideContent: {
      summary: 'Because currency calculations operate in base-10 (decimal) and clock time operates in base-60 (sexagesimal), converting minutes into decimal fractions is essential for accurate payroll and invoicing.',
      sections: [
        {
          heading: '1. The Base-60 to Base-10 Problem',
          body: '30 minutes is 0.5 hours (not 0.3 hours). 15 minutes is 0.25 hours. 45 minutes is 0.75 hours. Miscalculating minutes as decimals leads to significant underpayment or billing errors.',
        },
        {
          heading: '2. The Core Conversion Formula',
          body: 'To convert any minute value to decimal, divide the minutes by 60: Decimal = Minutes / 60. For example, 18 minutes / 60 = 0.30 decimal hours.',
        },
      ],
    },
  },
];
